### ISSUE TITLE
weex 集成到web需要什么工具

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1658]

**Comment by MrRaindrop** [comment]
## Q: What tools I need to use weex in my web pages ?

## A:

I think you mean what tools you need to use **weex-html5** in the web pages on the web platforms like browser environment. Tools mainly includes:

我理解你问题指的是在 web 页面中使用 **weex-html5** 需要哪些工具。主要是如下这些：

### 入口（entrance）

First of all, you should have a entry file, such as the `index.html` of weex's repo: https://github.com/alibaba/weex/blob/dev/index.html

首先你需要一个入口文件，例如这里的 https://github.com/alibaba/weex/blob/dev/index.html

### weex-html5

Second, you should require the weex-html5 library, which you can build it from the weex's repo by running the `npm run build:browser` command and then get it in the path `dist/browser.js`, or just use it as a npm module, by `npm install weex-html5`.

其次，你需要依赖 weex-html5 的库文件，可以是通过主仓库里 npm run build:browser 打包出来的 `dist/browser.js` 也可以是使用现成的 npm package，只需要` npm install weex-html5` 一下即可轻松拥有。

### webpack + weex-loader

use webpack and weex-loader to transform your `.we` file to a `.js` bundle. Maybe you also need a server to publish this bundle file.

使用 webpack 和 weex-loader 将你的 `.we` 文件转换成 `.js` bundle 文件。或许你还需要一个 server 来发布这个 bundle 文件。

### 其他工具 (other stuff)

rollup, babel, etc. Think about weex-html5 as any other web frameworks, and the tools you use are almost the same (front end building engineering). Just hook up with you imagination.

rollup, babel, 等等。把 weex-html5 和其他 web 框架一样使用就可以了，用到的工具基本类似（你项目的前端工程流程体系建设）。这个你可以任意发挥了。

Here is a simple example about integrating to the web. Just have a quick check you will understand: https://github.com/MrRaindrop/weex_extend_demo

这里有一个简单的集成到 web 的例子，看一下就了解怎么集成了：https://github.com/MrRaindrop/weex_extend_demo

### 注意 (NOTE)

You should pay attention to the performance of the page you use weex-html5 in, since the current version is a little bit big, and the loading experience may not be that good.

需要注意一下目前 weex-html5 的包大小比较大，当你考虑用在你的页面里时，需要在加载性能非常小心。

**Comment by WangXiZhu** [comment]
我在自己扩展组件，类似于 weex_extend_demo过程中，当我引入组件
```
var share = require('weex-hello-web');
// import hello from 'weex-hello-web';
``` 
这两种方式都有export的问题，请问是不是需要编译呢？  目前使用的是weex-toolkit这种方法来编译 .we文件。  我认为就是编译的问题，不知道你们有没有遇到类似问题？谢谢

**Comment by vczero** [comment]
@MARCUSW10 也可以了解下weex在初始化功能时做了一件什么事，一个web页面需要html载体，他是如何工作的。https://vczero.github.io/weex-learning/003_init_project.html

**Comment by MrRaindrop** [comment]
@WangXiZhu 是不是没有用 babel 转呢 ？或者你先尝试参考 weex_extend_demo 里的工具配置，用 weex-loader 来转看看，看看有没有问题。另外建议单独开一个 issue 把你遇到的问题详细描述一下。

**Comment by Jinjiang** [comment]
@WangXiZhu 如果还有疑问可以另开一个 issue 我们独立讨论
@MrRaindrop 你的解答非常全面，可以整理出一篇放在 articles 里
