### ISSUE TITLE
<slider-neighbor> 标签问题

### ISSUE THREAD

**Issue by YanyeZhang** [alibaba/weex#1709]
slider-neighbor 
### 在ios 上，有一定几率出现空白请况
期待修复

**Comment by sospartan** [comment]
@wispy316

**Comment by acton393** [comment]
hi @YanyeZhang 
在什么场景下比较复现一点

ps: 这个组件暂时没有对外public ，只作为一个feature

**Comment by YanyeZhang** [comment]
相关代码已经提交到#1708 中， list 滚动离开<slider-neighbor>之后会被销毁

**Comment by acton393** [comment]
slider-neighbor组件暂时还不建议使用,bug确实比较多点，我们也在修改中，会尽快正常的功能和使用的文档~~， 望关注后续进展..

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
