### ISSUE TITLE
编译so后不可用

### ISSUE THREAD

**Issue by xyzlmn** [alibaba/weex#1826]
编译so（ https://github.com/alibaba/weex_v8core ） 后，在android版本的playgroud（下载源码编译）使用，报错， render error :createInstanceReferenceError:callAddElement is not define .编译后的so在 arm下为3.4 M,而SDK下arm的so是3.6 M.

使用的android-ndk-r13b，mac10.12.1 。

**Comment by Jinjiang** [comment]
感觉这个问题和 #1851 有一定关联，都是 callAddElement is not define

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
