### ISSUE TITLE
wxc-tabbar的背景色怎么设置呢

### ISSUE THREAD

**Issue by yaochenfeng** [alibaba/weex#1920]
wxc-tabbar的背景色怎么设置呢

.wxc-tabbarClass{
        background-color:black;
    }
这个会是内容的背景色设为黑色，到时tabbar的背景色没有改变

**Comment by goddkiller** [comment]
<wxc-navpage data-role="none" title="xxxx" title-color="white" background-color="#000000" left-item-color="white"
                     height="{{height}}" left-item-src="{{img_path}}">

**Comment by boboning** [comment]
目前单个tab的背景色是不支持的。wxc-tabbar是通过前端组件搭建而成的，你可以在我们的github上找到wxc-tabbar的源码实现，给予我们的源码添加background-color的支持，这个是我们推荐前端的一种方式。

**Comment by ljuns** [comment]
我的 wxc-tabbar 显示不完整，只显示了一截图片，文字也没了，感觉被挡住了

**Comment by lushang1geren** [comment]
怎样通过js代码去决定去选中哪一个呢？或者直接改变tabbar的样式 （让他处于选中状态）

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
