### ISSUE TITLE
使用<scroller>时出现的问题

### ISSUE THREAD

**Issue by oksimple** [alibaba/weex#1942]
android 模拟器 6.0系统

在android 平台 使用 <scroller> 时 列表最后 会出现加载不全的情况

这里是代码 http://dotwe.org/d02e80668804e4031612ef15df28782d

![default](https://cloud.githubusercontent.com/assets/10106142/21303306/7975d530-c5f8-11e6-9637-205e931e7bc7.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
