### ISSUE TITLE
[feature request]location & history management

### ISSUE THREAD

**Issue by wintercn** [alibaba/weex#1961]
Hi, guys,

history and location apis are very important features for SPA, I hope we could get it in later version of weex.

* location api
    * location.reload
    * location.replace
    * location.assign
* history
    * history.back
    * history.forward
    * history.go
* history state api
    * history.replaceState
    * history.pushState
    * history.popState
    * onpushstate event
* Hash
    * when loading a url only different with current in hash part(after '#'), the page will not reload.
    * onhashchange event: in addition to web standard, I think we should add a "operation" property to specify what action triggered hash change like "back" "forward" "replace" "assign"

**Comment by Jinjiang** [comment]
#2014 related

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
