### ISSUE TITLE
Input 问题

### ISSUE THREAD

**Issue by gxmdboy** [alibaba/weex#1994]
android 上的input如果输入一大段文字后，关闭输入法，想在中间某段插入输入，点击要输入的位置，这时候弹出的是文字段落操作，也就是“选择，复制，剪切”这些，无法在选择的地方插入输入 #

**Comment by gxmdboy** [comment]
更新0.9.4后大部分机型都没这个问题了，但是小米4  还有这个问题
机型：MI 4W 
android版本：android4.4.4KTU84p
MIUI版本：MIUI6.4.3.0(KXDCNCB)稳定版

**Comment by fengmingye** [comment]
我也用到这个问题了，看来需要更新sdk到0.9.4,谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
