### ISSUE TITLE
weex的intellij idea插件在Windows版本上没有任何作用

### ISSUE THREAD

**Issue by puppyhang** [alibaba/weex#2007]
![d4_x6uwd br xlzbtxn717](https://cloud.githubusercontent.com/assets/11493946/21457691/356b3840-c96c-11e6-8be5-4f6238f45dac.png)

**Comment by Darin726** [comment]
Windows 正在适配中

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
