### ISSUE TITLE
wxc-navpage的两个小问题

### ISSUE THREAD

**Issue by kun1988** [alibaba/weex#2013]
1。因为标题栏的高度我需要在安卓设备上设置成为material design规范的高度，高度变大之后文字并没有自动居中。
2。使用了wxc-navpage在浏览器上面滚动的时候会出现内容遮盖标题栏的情况，不知道怎么贴图，见谅。

**Comment by ljuns** [comment]
我也遇见了，还没解决方法

**Comment by haicuan139** [comment]
自定义可以

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
