### ISSUE TITLE
Demo 项目 iOS NSLog 不执行

### ISSUE THREAD

**Issue by btxkenshin** [alibaba/weex#2021]
RT，git clone了整个项目并做好所有配置后，iOS项目成功跑起来，各demo功能都正常，但是日志没有输出，（已设置了日志开和适当的级别)
```
[WXDebugTool setDebug:YES];
[WXLog setLogLevel:WXLogLevelLog];
```

不但WXLog没有，连带NSLog也无效:
直接在didFinishLaunchingWithOptions开头输出NSLog也无效
```
NSLog(@"_______________");
```

补充：check功能并没有发现任何的对NSLog重新define的相关代码

环境：Xcode 8.0

**Comment by acton393** [comment]
hi  @btxkenshin   在 edit scheme 检查下 OS_ACTIVITY_MODE  这个值，可以取消掉选中试试
![image](https://cloud.githubusercontent.com/assets/11631084/21481168/92b746bc-cb9f-11e6-9c51-e0ffdadafc56.png)

**Comment by btxkenshin** [comment]
取消是ok的，但是修改下WXLog的日志输出方式是否更好呢，已发起了一个pull request，check

[refer](https://github.com/alibaba/weex/pull/2024)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
