### ISSUE TITLE
HTML5 升级 JS framework >  0.19 后造成无法渲染dom节点

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#2025]
测试页面的代码，为weex官方示例，一旦升级 JS framework到0.19之后 页面dom节点就无法渲染了，也没有任何提示信息。
如下图所示：#weex 节点的子节点为空，console也没[h5-render] createBody的log

![123](https://cloud.githubusercontent.com/assets/13174847/21481928/62714242-cba8-11e6-8864-5b4160f8075c.jpg)

而降级使用0.17版本的就正常了

![234](https://cloud.githubusercontent.com/assets/13174847/21481960/d39727ac-cba8-11e6-9429-7b09e80eb7a0.jpg)

**Comment by Jinjiang** [comment]
0.19 刚开始迭代，可能还不够稳定，我们会保持跟进
谢谢

**Comment by SimonTal** [comment]
谢谢，那我先降级使用吧

**Comment by Jinjiang** [comment]
@SimonTal 以 dev 中的版本为稳定版本看待吧，感谢理解：）

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
