### ISSUE TITLE
onpullingdown 事件在0.9.4 iOS版本还是不支持啊,是不是被遗漏了？

### ISSUE THREAD

**Issue by haicuan139** [alibaba/weex#2028]
之前有文档说明 onpullingdown 事件在0.9版本会在iOS版本上支持啊。

**Comment by kfeagle** [comment]
貌似安卓已经有了，我跟进下:-)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
