### ISSUE TITLE
[bug] slider cannot swipe back to previous slide when it has only two children

### ISSUE THREAD

**Issue by daxingplay** [alibaba/weex#2044]
If there are only two children in one slider and user swipe to the second one, then he cannot swipe back to the first one. Please checkout this demo: [demo url](http://dotwe.org/1afedc478f3bcf6968f20393e18596f2). The demo code was copied from [examples](http://weex-project.io/doc/components/slider.html) in the docs.

If there are more children, there will be no problem.

You can use Weex Playground iOS App(1.3) to reproduce this issue. 
* OS version: iOS 10.2
* weex version: 0.9.4

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
