### ISSUE TITLE
Scroller水平方向滚动，浏览器支持，安卓不支持？

### ISSUE THREAD

**Issue by DangDangHellen** [alibaba/weex#2045]
将Scroller的scroll-direction设为horizontal，在浏览器中可以实现水平滑动，但在安卓机上还是垂直方向，并且已经不能滑动，有人遇到过这种情况吗？

**Comment by vfasky** [comment]
https://github.com/alibaba/weex/issues/2324

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
