### ISSUE TITLE
[Android] Input 控件赋值 “”时，显示null

### ISSUE THREAD

**Issue by lanceliu** [alibaba/weex#2090]
建议：WXReflectionUtils
line 220 调整成如下内容
```java
return  value == null ? "": value instanceof String ? value : JSON.toJSONString(value);
```

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
