### ISSUE TITLE
希望weex提供类似与MBProgressHUD的功能

### ISSUE THREAD

**Issue by sunzhongliangde** [alibaba/weex#2091]
比如，weex页面里面有一个按钮，点击了之后有一个网络请求，这个网络可能要耗时一段时间，期间又不希望用户再次点击这个button，同时还能看到有一个loading...加载框，
iOS里面的MBProgressHUD 效果挺好的，希望可以在weex里面集成进来。

**Comment by yikee** [comment]
mark

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
