### ISSUE TITLE
android list 控件在下拉刷新的时候，列表不可以滚动

### ISSUE THREAD

**Issue by yuxingfafu** [alibaba/weex#2094]
android list 控件在下拉刷新的时候，列表不可以滚动

**Comment by liujianying** [comment]
可以修改native代码, 可以解决这个问题, 看代码貌似粗暴直接把事件给父控件消耗掉了.导致无法滚动,需要修改部分代码,可以解决这个问题, 不过还是建议官方做下优化

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
