### ISSUE TITLE
ios拓展本地组件问题

### ISSUE THREAD

**Issue by slidoooor** [alibaba/weex#2098]
,ios端拓展组件,因为weex是以库的方式集成的,拓展的组件继承不了weex的组件父类,也取不到weex的协议之类的,请问这种情况要怎么处理呢?问题太小白,麻烦大家了

**Comment by zzyhappyzzy** [comment]
没怎么看明白。
协议只是约定了一组接口而已（面向接口编程），本身并没有做任何事情。具体的实现方法，都在相应的组件里实现。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
