### ISSUE TITLE
请问weex-html5什么时候发布版本

### ISSUE THREAD

**Issue by 1459416736** [alibaba/weex#2107]
因为之前weex-html5有小修改，我只好用源码修改后完成调试，如果weex.js源码用于正式发布文件太大了有1.8M，如果我自己压缩后发布一直会报错，所以问下时间安排

**Comment by MrRaindrop** [comment]
weex-html5 npm 包没有确定的版本发布时间，理论上有 bugfix 或者新 feature 都会做发布的. 另外自己可以通过主仓库的 npm run dist 在 `dist/` 里打包出发布文件.

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
