### ISSUE TITLE
html在tabber中显示list页面时,   <list>中的<text>的text-overflow: ellipsis;不起作用

### ISSUE THREAD

**Issue by wfzgit** [alibaba/weex#2111]
重现步骤 :
在examples\component\list\list-demo.we中添加style
`
  .shopDesc{
    text-overflow:
    ellipsis;lines:2
  }
`

增加data.shopList[0].shopDesc 的数据长度
` shopDesc: 'Genius sdf sdfdsfsd fs fsdfsdfdfa kdfg alfkajhg fkjahg dfkjagd fjhag df jhagf gasdf gakjd ajkdh gafkjd gafjdhg fkjagd jkf only means hard-working all one\'s life',`

重新打包后使用examples\showcase\new-fashion\index.we 打开浏览 效果如下
![gif](https://cloud.githubusercontent.com/assets/18186473/21600641/b500b818-d1ba-11e6-9b6b-4003e724a313.gif)

weex-html 0.4.1

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
