### ISSUE TITLE
使用 playground app 跑 list 的例子，安卓手机头部样式不正确

### ISSUE THREAD

**Issue by YongX** [alibaba/weex#2113]
hello,
我运行官网的 [list](http://dotwe.org/13e8c117b5af140d9ec07e575b1982b4) 的例子，发现固定的 header 头部样式在手机上不正常，具体见截图：

![wechatimg16](https://cloud.githubusercontent.com/assets/7367678/21601622/5b34202e-d1c7-11e6-8a4c-158622f2070c.jpeg)
![wechatimg17](https://cloud.githubusercontent.com/assets/7367678/21601620/5b31ea52-d1c7-11e6-9920-654c206dd7c2.jpeg)
![wechatimg18](https://cloud.githubusercontent.com/assets/7367678/21601621/5b322440-d1c7-11e6-9116-a31a19daf9e3.jpeg)

**Comment by colys** [comment]
我也碰到，而且不仅是样式，有时候根本无法固定顶部

**Comment by shangxinbo** [comment]
遇到同样的问题，本来布局好好的，playground的头会占用屏幕

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
