### ISSUE TITLE
list组件等同于iOS中UITableView吗？支持多个Section吗？

### ISSUE THREAD

**Issue by wangdongabc** [alibaba/weex#2117]
没想明白list如何实现多个section，每个section多条数据？demo中没找到类似的代码。
另外，支持list嵌套吗？

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
