### ISSUE TITLE
自定义组件没有调用期方法的接口（不是标签上的属性）

### ISSUE THREAD

**Issue by colys** [alibaba/weex#2121]
比如一个手势签名的控件，要执行清空和获取图片的方法。
文档中只字未提啊。

**Comment by acton393** [comment]
没太理解，可否给一个具体的case，描述一下~

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
