### ISSUE TITLE
AndroidStudio weex插件导致AS直接奔溃

### ISSUE THREAD

**Issue by tmxdyf** [alibaba/weex#2133]
![image](https://cloud.githubusercontent.com/assets/6415080/21634555/1ad87c42-d293-11e6-80e4-34cf8dd622a3.png)

系统：
![image](https://cloud.githubusercontent.com/assets/6415080/21634669/d1ba6466-d293-11e6-93e2-6e09b1d4344d.png)

AndroidStudio :
![image](https://cloud.githubusercontent.com/assets/6415080/21634604/53fa7fc0-d293-11e6-8f4a-be6864f9b9a1.png)

Weex:
![image](https://cloud.githubusercontent.com/assets/6415080/21634623/6d709d9a-d293-11e6-8beb-056af878e9da.png)

AS异常信息：
![image](https://cloud.githubusercontent.com/assets/6415080/21634702/231236f4-d294-11e6-9261-b6d124c728d1.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
