### ISSUE TITLE
Android 下面 页面中存在list或scroller，并且input在页面底部的时候，键盘会覆盖input

### ISSUE THREAD

**Issue by Hello2015** [alibaba/weex#2145]
```html
<template>
	<div style="position: absolute;left: 0;right: 100;top: 0;bottom: 100;background-color: #F9BE00;">
		<div class="rowdiv">
			<list></list>
		</div>
		<div style="position :fixed ;bottom: 15;height: 100;flex-direction: row;">
			<input placeholder="在此输入" style="width: 750;background-color:#FF9933;"></input>
		</div>
	</div>
</template>
```
按照上述写法进行的时候，点击文本输入框，键盘弹出的时候View不上移，导致键盘盖住了input。去掉list之后就正常了。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
