### ISSUE TITLE
Android registerComponent的时候不能用“progress”作为标签名字吗？ 我用这个作标签名字，weex sdk stackOverFlow了

### ISSUE THREAD

**Issue by 1903514970** [alibaba/weex#2166]
Android registerComponent的时候不能用“progress”作为标签名字吗？ 我用这个作标签名字，weex sdk stackOverFlow了
![image](https://cloud.githubusercontent.com/assets/15099256/21715112/a6fb338a-d43d-11e6-8d5c-dea53f26a59e.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
