### ISSUE TITLE
［新需求］buttongroup/buttonbar

### ISSUE THREAD

**Issue by goldmantis** [alibaba/weex#2172]
详细描述：2-n个按钮并排在一行。按钮组中永远只有1个按钮出于选中状态（类似tab）。如果按钮太多，超过一屏幕显示，则选中某个按钮后，按钮组相应的移动些位置，使得当前状态稍微居中。选中某个按钮后,下面显示对应的页面内容。

应用场景：APP中，某个页面有很多分类，如热门推荐、要问、视频、图片等。这些分类通常放在标题栏稍下的地方。可以参考阿里云APP中“云栖”这个tab下的“推荐”、“聚能聊”、‘博客’、“云栖大会”。

**Comment by beghujam** [comment]
请问你这个需求实现了吗，我现在也有这个需求

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
