### ISSUE TITLE
如何在模板中用全局变量（常量）？

### ISSUE THREAD

**Issue by Mryong** [alibaba/weex#2180]
我想定义一个文件define.js，在这个文件中放置所有的全局常量，比如：
 BASE_ADDRESS = "http://192.168.221.247:12345/"; //从Weex编译后的文件看，这其实不是全局常量,所以我把前面的const去掉了,但这时候又变成了变量,好无奈....
 然后在模板中用{{BASE_ADDRESS}}引用，实验表明这是不行的，那该如何使用呢？

**Comment by CCC2016** [comment]
可以参考 Vue 看能不能实现。

**Comment by xispower** [comment]
我的使用方法，比如在文件define.js中

```
function define(name, value) {
  Object.defineProperty(exports, name, {
    value: value,
    enumerable: true
  });
}

define('BASE_ADDRESS,
  'http://192.168.221.247:12345/');

```

使用方法：
```
var define = require('./../config/define.js');
var base_address = define.BASE_ADDRESS;
```

如果还有其他方法，请@我一下

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
