### ISSUE TITLE
weexpack run android 编译包 tools.jar 未找到

### ISSUE THREAD

**Issue by The-Pursuit-of-Happyness** [alibaba/weex#2184]
搭建好了node,weexpack ,java,android studio, android 模拟器，运行weexpack run adndroid weexpack 编译.we文件完成，启动模拟器后能编译，在编译过程中报错，找不到 tools.jar,下面执行运行命令的完整过程
![image](https://cloud.githubusercontent.com/assets/17919630/21768145/0ad24bb0-d6b3-11e6-8948-4a6b0fba9b2f.png)
![image](https://cloud.githubusercontent.com/assets/17919630/21768157/1b6fbf0c-d6b3-11e6-8ce7-30bf57d55715.png)

![image](https://cloud.githubusercontent.com/assets/17919630/21768179/33e8cd1c-d6b3-11e6-918f-5ae54d1a03a8.png)
![image](https://cloud.githubusercontent.com/assets/17919630/21768199/46f15334-d6b3-11e6-92f8-12ab1671307f.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
