### ISSUE TITLE
加载列表时出现的一个闪退问题

### ISSUE THREAD

**Issue by WHChaw** [alibaba/weex#2190]
<img width="923" alt="qq20170110-0 2x" src="https://cloud.githubusercontent.com/assets/14286720/21792624/108a9f76-d726-11e6-8249-353d63fd03dc.png">

<img width="927" alt="qq20170110-1 2x" src="https://cloud.githubusercontent.com/assets/14286720/21792668/55aff7e0-d726-11e6-9117-40d2a4676c2c.png">

**Comment by cxfeng1** [comment]
@WHChaw  麻烦给一下闪退出现的 Weex版本， iOS版本 以及 机型， 谢谢

**Comment by WHChaw** [comment]
weex版本0.9.4，ios10.2.1 机型iPhone 6s，但不确定是否只在这个版本的系统下出现

**Comment by WHChaw** [comment]
@cxfeng1 weex版本0.9.4，ios10.2.1 机型iPhone 6s，但不确定是否只在这个版本的系统下出现

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
