### ISSUE TITLE
demo在华为手机隐藏虚拟按键，出现白色的边怎么解决

### ISSUE THREAD

**Issue by SSourceFile** [alibaba/weex#2195]
我吧playground跑到华为手机上，但是吧华为的虚拟按键隐藏后就出现白色的一块原来虚拟按键的位置。进去Activity页面后，如果开启了虚拟按键，就会吧底部的导航遮住了。求解决办法。。。。。

**Comment by Jinjiang** [comment]
暂时没有办法解决……SDK 本身无法感知这个变化
想多问一下是 root 之后的手机吗？正常情况手机应该不会遇到这个问题
谢谢

**Comment by huaminghui** [comment]
过年回去了，乡下没网络没上来看，不是root之后的手机，后来在AbstractWeex做了修改判断，通过addOnGlobalLayoutListener监听前后的高度，在用setsize(int width， int height)方法修改高度

**Comment by YorkShen** [comment]
@huaminghui 你是用的哪个api隐藏的底部虚拟案件

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
