### ISSUE TITLE
Android DevTool 调试报错

### ISSUE THREAD

**Issue by fightKen** [alibaba/weex#2208]
Android DevTool 调试报错，一直无法进入调试状态，页面也是空的，具体报错为：Uncaught DOMException: Failed to execute 'getItem' on 'Storage': access is denied for this [document.(见截图)
![a7796442-92c2-40a3-9ea6-73866d974d2f](https://cloud.githubusercontent.com/assets/5284450/21833496/87c48be8-d7ed-11e6-8970-2df04a317d22.png)
求大神指导

**Comment by exolution** [comment]
你用的应该是dev版或者beta版的chrome吧 县换到stable版把
我正在研究这个新版的权限问题

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
