### ISSUE TITLE
如何设置cookie，通过js中的document.cookie无法获得document.

### ISSUE THREAD

**Issue by emmanuelwang** [alibaba/weex#2221]
无论是document,或者window都无法获得，该怎么办呢，但是服务端那边却可以写入cookie

**Comment by Jinjiang** [comment]
抱歉，Weex 里没有 cookie 的概念，如果你想做本地存储，可以考虑使用 Weex 的 storage module
https://weex-project.io/cn/references/modules/storage.html
如果想和服务端共享数据或身份校验，我们一般是利用 App 本身的 native 登录机制，这样也更保险安全一些
谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
