### ISSUE TITLE
slide功能建议

### ISSUE THREAD

**Issue by sunzhongliangde** [alibaba/weex#2232]
比如有一个slide有三页，当滚动至最后一页时，如果用手继续滑动，此时是回到第一页的，
但是我有一个需求是不想让他回到第一页，看了下weex的slide帮助文档，好像没有属性或者方法来限制的，
希望有这个功能，谢谢。

**Comment by yuanzx** [comment]
希望原生支持，目前也遇到这个问题，只有靠自己团队去改源码了

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
