### ISSUE TITLE
CSS 缩写语法支持

### ISSUE THREAD

**Issue by acathur** [alibaba/weex#2240]
建议对CSS缩写语法提供支持 @Jinjiang 

```
{
    margin: 12px; /*已支持*/
    padding: 12px 16px; 
    border: 1px solid #fff;
    background: #ccc;
    font: italic bold 12px/32px;
}
```

**Comment by YongX** [comment]
官网好像有写的，支持缩写语法会影响解析速度，所以暂不提供。

**Comment by Acathur** [comment]
@YongX 在 compile JavaScript 的环节中支持，即扩展webpack weex-loader的能力

**Comment by YongX** [comment]
@Acathur 倒是个好方案。

**Comment by Jinjiang** [comment]
编译时解析 CSS 语法确实是可行的，但没有办法做到特别完备，而且这些样式在 JS 中同样可以通过数据绑定或 native DOM APIs 来修改，这种方法就照顾不到了，很难跟广大的开发者解释，这是我们一直纠结的原因
这个问题我们可以保留，如果有更好的方案和建议，我们随时可以尝试

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
