### ISSUE TITLE
***BUG*** E2e tests don't work

### ISSUE THREAD

**Issue by miherlosev** [alibaba/weex#2241]
I ran `npm run e2e` and got the error:
![e2e run error](https://cloud.githubusercontent.com/assets/4133518/21891390/7db46488-d8e3-11e6-8982-42381bbd3438.png)

**Comment by Jinjiang** [comment]
Could you please apply some details about your environment?
Thanks.

**Comment by miherlosev** [comment]
`node --version`
`v6.9.1`
`npm --version`
`3.10.8`

Windows 8.1

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
