### ISSUE TITLE
关于新版weex引用module方式设计的讨论

### ISSUE THREAD

**Issue by acathur** [alibaba/weex#2242]
最新版weex (0.9.5) 使用 `weex.requireModule(x)` 的方式来引用模块，从前端模块化开发角度来看似乎原来的设计: `var x = require('@weex-module/x')` / `import x from '@weex-module/x'` 似乎更合理一些。请问weex未来会移除旧版的引用方法吗？

**Comment by uxiya** [comment]
文档是不是回退了？vue版的没了，什么情况

**Comment by Jinjiang** [comment]
主要是两个原因：

1. 现在太多名字叫 `require` 的东西，很多包管理模型本身都有 `require`，Weex 里的 native module 本身都不是一个实体的 js 模块，所以我们逐渐觉得不太合适
2. `require('@weex-module/xxx')` 在一般的 js 里没机会被识别，是我们最初设计上的一个死穴

所以我们决定改名叫 `weex.requireModule('xxx')`

**Comment by MrFuFuFu** [comment]
@Jinjiang 麻烦修改一下，你们的文档!!! [cuszomize-native-apis](https://weex-project.io/cn/v-0.10/advanced/cuszomize-native-apis.html)，[Module 扩展](https://weex-project.io/cn/v-0.10/advanced/extend-to-android.html)   弄了一下午...结果发现...死活不行....

**Comment by Jinjiang** [comment]
@MrFuFuFu 你好，你贴的那两份文档是旧版的语法，require 是可以工作的。如果遇到具体不工作的问题，可以另外发起讨论，并附上重现的内容
谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
