### ISSUE TITLE
weexpack这个构建工具中的weex落后于官网weex0.9.4？examples示例在weexpack中跑IOS，新增效果picker没有出现

### ISSUE THREAD

**Issue by Erwin11** [alibaba/weex#2243]
我把官网0.9.4源码的（https://github.com/alibaba/weex/archive/v0.9.4.zip）中的examples拷贝到用weexpack init 的新建项目的src目录中，然以后weexpack run ios，在input 中查看date新属性picker，效果不一致。
还是说大家现在都是把开发项目放在weex 源码中的example目录中开发的？

**Comment by uxiya** [comment]
我的也是的，

**Comment by exolution** [comment]
请帖一下你们weexpack的版本

**Comment by exolution** [comment]
或者更新到最新版本的weexpack后尝试

**Comment by Erwin11** [comment]
weexpack --version
0.3.2

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
