### ISSUE TITLE
迁移至vue2.x版本后，slider的change事件的index无法获取

### ISSUE THREAD

**Issue by jaylinwang** [alibaba/weex#2249]
迁移至vue2.x版本后，监听slider的change事件，event中无法获取到index

## 版本

- weex 0.9.5
- vue 2.1.8

**Comment by chaucerling** [comment]
weex --version 
v1.0.1-beta.5
 - weex-devtool : v0.2.76
 - weexpack : v0.3.4

vue 2.1.8

同样有这个问题

**Comment by Jinjiang** [comment]
http://dotwe.org/vue/dafd44e1e83694dce1bf3804bfc5f874
我试了一下，Native 端 event 是有 index 的，html5 版本似乎没有正常工作 @MrRaindrop @Hanks10100 可以一起看一下

**Comment by zhaowangdaren** [comment]
weex-vue-render slideMixin.js:
```js
      if (newIndex !== this._preIndex) {
        this.$emit('change', weex.utils.createEvent(this.$el, 'change', {
          index: newIndex
        }))
      }
```

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
