### ISSUE TITLE
ios本地客户端组件实现

### ISSUE THREAD

**Issue by slidoooor** [alibaba/weex#2270]
小弟现在想在ios本地实现一个自定义组件给服务端调用,但是看了系统的组件实现,里边有协议,自己实现的话,还引用不到协议,直接把组件定义到weex文件夹还会报错,求组这种问题大概解决方向应该怎么弄呢`万分感谢

**Comment by acton393** [comment]
@slidoooor  可以具体描述一下么，没打理解， 哪个组件的啥协议..

**Comment by slidoooor** [comment]
@acton393  就是想自定义一个搜索栏,但是看weex源码定义的控件例如textfield之类的都遵守了协议,,就有点乱..

**Comment by acton393** [comment]
hi @slidoooor  weex 源码里面input (系统组件textfield) 应该没有实现啥协议，你如果需要自定义一个搜索栏组件，就直接继承WXComponent 就可以，不需要实现啥协议

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
