### ISSUE TITLE
filter blur

### ISSUE THREAD

**Issue by gxmdboy** [alibaba/weex#2272]
android上
如果图片给的是矩形，需要显示为圆形（例如头像），使用filter:blur(100)，但原生代码里限制最多为10。
这个数值应该由使用人来决定，不应限制

**Comment by gxmdboy** [comment]
还有个和ios兼容的问题
在ios上可以用BorderRadius来设置圆角，但是在android上这个是设置background这层的圆角
和ios不统一。
暂时的解决办法是将image控件里的代码：
`imageStrategy.blurRadius = getDomObject().getStyles().getBlur();`
改成
`imageStrategy.blurRadius = (int)getDomObject().getStyles().getBorderRadius();`
然后在adapter获取使用
这块请统一设计下

**Comment by zjfandroid** [comment]
filter:blur(10) 安卓毛玻璃效果无效

**Comment by starfalling** [comment]
模糊效果是需要在 ImageAdapter 中进行支持的，如果使用 weex create 生成的项目，有这部分代码；如果是接入到已有的项目里面，可以先建一个空的项目然后参考里面的代码

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
