### ISSUE TITLE
【新需求】给手势操作开放更多的控制权

### ISSUE THREAD

**Issue by YongX** [alibaba/weex#2273]
说明：以下描述是在`wxsdk 0.9.4`版本上进行测试的，新版的`0.9.5`应该未对手势做升级。

**需求描述：**
目前的手势系统提供的方法从文档上看不能阻止内嵌滚动元素的默认滚动事件。考虑一种页面结构：
```
<template>
  <div class="list-wrap" ontouchmove="handleTouchmove">
    <list class="menu-left" id="menu">
      <cell class="menu-item" repeat="menu">
        <text class="menu-name">{{ name }}</text>
      </cell>
    </list>
  </div>
</template>
```
期望能做到可以在`handleTouchmove`方法中控制是让整个`view`滚动，还是让`list`滚动。

**应用场景：**
一个典型的应用场景是在饿了么App的商品列表页：
![wechatimg37](https://cloud.githubusercontent.com/assets/7367678/21926291/168fc070-d9bc-11e6-9dc7-6cc16703c95e.jpeg)

图中我主要分成了3大块区域。红色区域1为一个`view`包含两列`list`，绿色区域2为`list`组件，黑色区域3为头部。
这里的一个交互细节是在截图所示的状态下，对区域2做上划操作实际上滑动的是整个区域1，直到滑动的高度为当前区域3所在的高度后，区域2里面的`list`才重新响应滑动操作。下拉的过程则相反。

**Comment by yong-chen04** [comment]
Any updates?

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
