### ISSUE TITLE
slide里面嵌list或者scroll，web可以显示，android不行

### ISSUE THREAD

**Issue by colys** [alibaba/weex#2281]
试了几种布局都不能显示，list的背景倒有，简单的放个text文本到list也显示不了。

**Comment by colys** [comment]
补充：如果slide显示后，再显示list（settimeout+if来实现），可以显示，但一定要设置一个高度，不会自适应，高度比较麻烦。而且还发现一个问，在slide里面的list下拉刷新或者上拉加载，多拉几次，并且切换几次，上下拉的控件会不显示，web上正常。不在slide中也会正常。

**Comment by Jinjiang** [comment]
可以在 http://dotwe.org/ 给个在线的例子吗？是什么样的场景？我们这边几乎没有这样的使用场景，所以想多确认一下
谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
