### ISSUE TITLE
V0.9.5.1动画问题BUG

### ISSUE THREAD

**Issue by luoei** [alibaba/weex#2288]
iOS 0.9.4上面稍微好点，在0.9.5.1上面完全是另外一个展现方式。
```
animationTest:function(obj){
      var duration=0;
      var deg=0;
      if (left) {
        duration=2000;
        deg='rotate(-30deg)';
      }else {
        duration=2000;
        deg='rotate(30deg)';
      }
      var self=this;
      left=!left;
      animation.transition(obj, {
          styles: {
            transform: deg
          },
          duration: duration,
        }, function () {
          self.animationTest(obj);
        });
    }
```

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
