### ISSUE TITLE
没必要每个文件里都写完整版的LICENSE

### ISSUE THREAD

**Issue by markzhai** [alibaba/weex#2290]
Weex 项目的源码文件每个都写了几百行的LICENSE，开源项目除了顶层的LICENSE文件，其他只需要十几行写简略版的就够了。

见：
![2017-01-17 11 38 05](https://cloud.githubusercontent.com/assets/1106500/22006864/933b1fda-dca9-11e6-9851-263bdb91dce3.png)
![2017-01-17 11 38 21](https://cloud.githubusercontent.com/assets/1106500/22006868/9a19e9f8-dca9-11e6-8a85-c2c2aa1a07a2.png)

而Weex的：
![2017-01-17 11 39 54](https://cloud.githubusercontent.com/assets/1106500/22006884/ae18ecce-dca9-11e6-81d4-afe7c3f486d5.png)

**Comment by Jinjiang** [comment]
好建议， @sospartan 我们要不要简化一下？

**Comment by sospartan** [comment]
@Jinjiang 可以的 这是android编译的时候 插件自动实现的

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
