### ISSUE TITLE
Android "netword error" 

### ISSUE THREAD

**Issue by HpWens** [alibaba/weex#2298]
Android 平台
你好！
       按着 github 步骤，程序部署到手机上，更改了本地 IP 地址，点击列表出现 “netword error”。
       我手机和电脑连接的是公司的 WIFI ，我回家试了也不行。我关闭了其他的网络连接也不行，后来我关闭了防火墙测试还是不行。非常感谢你能够帮助我分析下问题出现在哪了？

**Comment by acton393** [comment]
hi @HpWens  保证手机和 当前电脑在同一个网段， 尝试 ping 看下可以通不

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
