### ISSUE TITLE
Does weex support flex order?

### ISSUE THREAD

**Issue by Gcaufy** [alibaba/weex#2299]
I tried order, but it does not work.
but when I manually added it in DevTool, it works well.

**Comment by Gcaufy** [comment]
and also `row-reverse`

**Comment by DoranYun** [comment]
flex order is not supported right now.

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
