### ISSUE TITLE
flex bug in weex playground 

### ISSUE THREAD

**Issue by jfw10973** [alibaba/weex#2300]
用ipad打开 weex playground 在flex demo中的显示有断开的部分

设备型号：ipad Air 2 
设备版本：iOS 10.2
App版本：playground 1.3
截图如下：

![img_0298](https://cloud.githubusercontent.com/assets/7921930/22014039/d86c4c96-dcd6-11e6-8bf9-048941fe112d.PNG)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
