### ISSUE TITLE
Weex组件WXComponent能否像Module那样暴露出方法在Weex调用？

### ISSUE THREAD

**Issue by air1120** [alibaba/weex#2325]
如题，Weex调用原生的方法，能不能直接通过WXComponent调用，而不是通过Module调用？感觉组件和Weex的交互还非常不方便。

**Comment by acton393** [comment]
hi @air1120   已经支持了，可以参考 [web 组件](https://github.com/alibaba/weex/blob/ios-feature-20170118/ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m#L52)


调用方法:  [这里](https://github.com/alibaba/weex/blob/ios-feature-20170118/examples/component/web-demo.we#L54)

直接可以换成

```
   var webElement = this.$el('webview');
   webElement.goForward()
```

可以尝试一下

**Comment by colys** [comment]
@acton393 前几天我拉的代码，好像还没有支持，web组件是另外定义了一个moudule还调用里面的方法的

**Comment by air1120** [comment]
@acton393  谢谢，是支持的，写成class了。怪不得没调起来。还以为不支持呢。

**Comment by acton393** [comment]
hi @colys   没有新定义，现在允许把组件相关的方法直接暴露给js 调用，例如 web组件方法的 goforward  back  和refresh

**Comment by kfeagle** [comment]
Input 的focus和blur也是类似实现的

**Comment by colys** [comment]
@acton393 可以用@JSMethod(uiThread = true),但无法获取返回值 ,也传不了参数

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
