### ISSUE TITLE
dom.scrollToElement 失效

### ISSUE THREAD

**Issue by vfasky** [alibaba/weex#2326]
试了下， 官方 examples 也不行 https://weex-project.io/examples/dom-scroll.html

**Comment by kfeagle** [comment]
的确失效了，我帮你看看

**Comment by sunorry** [comment]
@kfeagle 最新 SDK 的**横向**滚动也是跪的，还有滚动条。 #2324

**Comment by kfeagle** [comment]
@vfasky 这个demo是vue的，目前0.9.5的sdk暂时不支持.vue的编译，你可以用playground扫码运行

**Comment by DoranYun** [comment]
@vfasky Hi，这个例子是 vue 的版本，需要使用支持该版本的 palyground 扫码才可以。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
