### ISSUE TITLE
使用weex开发出来的app怎样可以通过UiAutomatorviewer抓取元素的resource-id

### ISSUE THREAD

**Issue by evongaf** [alibaba/weex#2329]
we里定义了id，但是不知道和最终渲染出来的 控件属性的映射关系，使用UiAutomatorviewer抓取元素的resource-id为空，请教下如何能够实现增加resource-id或者name等？另外weex自动化采用何种自动化工具比较好？

**Comment by sospartan** [comment]
目前脚本里的id还没办法跟native的id 对应起来  我们也正在开发自动化测试的工具 目前会使用macaca框架

**Comment by evongaf** [comment]
macaca也是需要通过id或者 name等属性去定位元素的吧？这个工具可以使用脚本里的id去定位吗？

**Comment by sospartan** [comment]
@evongaf 目前还没不能  我们也还在想办法  目前可以通过xpath和文本来定位

**Comment by vivian2011** [comment]
@sospartan  我想知道，现在这个问题解决了吗？

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
