### ISSUE TITLE
android集成weex时由于multidex分包导致的集成后不能渲染weex页面

### ISSUE THREAD

**Issue by breg-jjb** [alibaba/weex#2333]
android 一个apk里面的dex文件只有65k个方法，app做大之后方法超过了就用multidex多分包打包，会生成两个dex文件，这样引入的weex库就会被分在两个dex文件里，这样打出来的apk无法渲染出weex的页面。
（0.8以上的可能多了很多方法，用了multidex之后就没法渲染成功）

请问这个问题怎么解决呢？

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
