### ISSUE TITLE
最新weexpack运行出错

### ISSUE THREAD

**Issue by wzj583585700** [alibaba/weex#2342]
用weexpack 运行 TypeError: Cannot read property 'join' of undefined
at utils.checkAndInstallForIosDeploy.then.then.then.then.then.then.then.then.then.catch.e (/usr/local/lib/node_modules/weexpack/src/run/iOS.js:32:33) 什么情况

**Comment by JackPu** [comment]
@wzj583585700  您安装下最新版本的weexpack试一下？

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
