### ISSUE TITLE
ios模拟器显示效果不一样怎么办？

### ISSUE THREAD

**Issue by pengzai123** [alibaba/weex#2348]
模拟器 ios10.2（14c89）  真机也是10.2(14c92) 

![20170120152920](https://cloud.githubusercontent.com/assets/18717303/22140101/53680764-df25-11e6-86d9-a07516212821.png)

**Comment by acton393** [comment]
hi @pengzai123  case可以提供一下，我们这边看看

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
