### ISSUE TITLE
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '@loadmore' is not a valid attribute name.

### ISSUE THREAD

**Issue by ggchxx** [alibaba/weex#2359]
weexpack create 项目以后运行weex-project.io的list例子报这个错误。
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '@loadmore' is not a valid attribute name.
问下 weexpack的项目如果需要编译vue版本 还需要添加什么插件嘛？

**Comment by dongfanghu** [comment]
weex和vue有一定的语法差异,官方链接[https://weex-project.io/cn/references/migration/difference.html](url)

**Comment by DoranYun** [comment]
@ggchxx 你好，weexpack 构建 vue 的版本正在努力开发中，还需要一点时间，谢谢理解。不过你可以自己尝试打包 Weex Playground。

**Comment by FrankFan** [comment]
遇到了同样的问题， 请问解决了么？

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
