### ISSUE TITLE
slider index属性不起作用

### ISSUE THREAD

**Issue by chenyunecjtu** [alibaba/weex#2366]
we：
![image](https://cloud.githubusercontent.com/assets/6322749/22179832/61f677f0-e099-11e6-9be6-bfd5a9275151.png)

设置index=1,slider 还是从0开始显示。

找java源码slider的实现，发现在
![image](https://cloud.githubusercontent.com/assets/6322749/22179815/131aa96c-e099-11e6-85d3-257744c12c15.png)
在addsubview 时mViewPager.setCurrentItem(0); 这句代码导致的。如果mViewPager.setCurrentItem(index); 就可以正常工作了，希望吧这个bug更新掉

**Comment by aoping** [comment]
这个bug还没修复吗？

**Comment by snailyuan** [comment]
这个bug还在。。。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
