### ISSUE TITLE
Provide WeexActivity as BaseActivity

### ISSUE THREAD

**Issue by markzhai** [alibaba/weex#2375]
Like what facebook provides in react-native:

- https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java

**Comment by markzhai** [comment]
Like what https://github.com/alibaba/weex/blob/dev/android/playground/app/src/main/java/com/alibaba/weex/WXPageActivity.java does, as if user only follows what https://weex-project.io/cn/guide/integrate-to-your-app.html guides, the activity can only provide a basic function, while it cannot even render new page when js sides does bundle navigation.

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
