### ISSUE TITLE
[需求] 希望 navigator 增加 replace 方法

### ISSUE THREAD

**Issue by vfasky** [alibaba/weex#2380]
如果用 push， 在需要登录的场景，登录完成后，后退还会退回登录界面

**Comment by markzhai** [comment]
这个确实应该是要的

**Comment by alex-zhang** [comment]
强烈需求。

**Comment by CoderSunnyLau** [comment]
對對，我也有這樣的需求。。(⊙ω⊙)

**Comment by alex-zhang** [comment]
。。。

**Comment by markzhai** [comment]
@alex-zhang 他们已经不管这里的issues了，忘了weex吧

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
