### ISSUE TITLE
完成动作的方式

### ISSUE THREAD

**Issue by benbenwang** [alibaba/weex#2382]
# 请问为什么为唤起两个app让去选择？怎么设置
![qq 20170123101133](https://cloud.githubusercontent.com/assets/14870451/22189585/6207129e-e158-11e6-9fba-8714d27466e2.jpg)

**Comment by Jinjiang** [comment]
这是因为 Weex Playground App 的 openURL 是通过 Android 里的 Intent 进行路由控制的，如果你的手机当中出现了相同名称的 Intent name，就会提示用户进行选择。
是不是 Demo03 这个应用同样配了和 Weex Playground 相同的 Intent name？建议把名字区分一下就好了。
谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
