### ISSUE TITLE
border-radius在android4.4设备上圆角无效

### ISSUE THREAD

**Issue by 13754327232** [alibaba/weex#2390]
border-radius在android4.4设备上圆角没有效果，还是直角

**Comment by DoranYun** [comment]
麻烦提供更多信息，WeexSDK 版本、示例代码等

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
