### ISSUE TITLE
[android] [iOS] 有点严重的bug

### ISSUE THREAD

**Issue by vfasky** [alibaba/weex#2416]
重现： http://dotwe.org/vue/30b28a3567397231b6cbe42b5b79d5a4

android：点击 `click me` 直接变白

iOS： 点击 `click me` ， 期望是

``` click me << last ```

实际

``` << last click me ```

last 直接替换了 fast

**Comment by vfasky** [comment]
官方是不能重现问题还是怎么滴？如果描述不清，请告知

**Comment by acton393** [comment]
hi @vfasky  可以提供一下SDK的版本号信息么，或者告知一下使用的SDK的分支信息, thx~~~

**Comment by vfasky** [comment]
android 同 iOS 都是 0.9.5

**Comment by acton393** [comment]
hi @vfasky  iOS 如果是使用cocoaPods 的话尝试一下 0.9.5.2

**Comment by vfasky** [comment]
用 `dev` 分支上的 SDK, 问题依然存在。

**Comment by vfasky** [comment]
最新的 Weex Playground 0.10.0 （android iOS）依然有问题
这是很低层的渲染 bug 啊？ 没人管吗？！

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
