### ISSUE TITLE
modal高度问题？

### ISSUE THREAD

**Issue by daizheng521** [alibaba/weex#2425]
modal在实际使用过程中，调用toast方法，出现高度几乎铺满全屏？想问下，toast的位置可以设置吗？

**Comment by CoderSunnyLau** [comment]
我測試的結果是出現在屏幕正中央，是否可以自定義toast出現在屏幕偏下的位置？

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
