### ISSUE TITLE
sticky元素在首屏之外时显示位置会偏离原有位置

### ISSUE THREAD

**Issue by lanmerry** [alibaba/weex#2427]
一个position为sticky的元素，显示在首屏之外，元素初始位置会离开原有位置

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
