### ISSUE TITLE
0.9.4 支持了image 访问本地图片的方式 但是文档里面没有更新。

### ISSUE THREAD

**Issue by HJ-StevenSun** [alibaba/weex#2430]
能提供一下具体代码和实现方式吗？ 有询问过你们的开发人员，开发人员说文档不在他们那边所以希望能够将文档和SDK 能够尽快同步。thks

**Comment by zcl0001** [comment]
https://weex-project.io/cn/faq.html
常见问题里面有说明，但是很简单

**Comment by erguotou520** [comment]
> Weex 暂时还不支持加载你工程中的图片文件

然而作为一个前端，我并不知道Android/IOS的本地图片资源如何放置位置，如果取路径。。。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
