### ISSUE TITLE
[ios] vue模式下，传递到 native 的 attribute 没有从 kebab-case 变成  camelCase

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#2438]
iOS sdk为 0.9.5.1。
例如：scroller的 `scroll-direction` 属性，传递到 native 后还是 `scroll-direction`，期望的应该是`scrollDirection`

**Comment by Hanks10100** [comment]
是个已知问题，参考 https://github.com/weexteam/weex-vue-framework/issues/21 。可能会通过修改编译工具来修复，原生代码不用修改。

**Comment by Neeeo** [comment]
请问这个编译工具修复这个功能有计划了吗？

**Comment by Hanks10100** [comment]
Fixed in [weex-loader@0.4.3](https://www.npmjs.com/package/weex-loader) .

Also make sure the following dependencies have a correct version:

+ [weex-vue-loader](https://www.npmjs.com/package/weex-vue-loader): **^0.2.10**
+ [weex-template-compiler](https://www.npmjs.com/package/weex-template-compiler): **^2.1.10-weex.1**
