### ISSUE TITLE
关于渲染界面时候参数问题

### ISSUE THREAD

**Issue by daifengming** [alibaba/weex#2499]
渲染界面时候，这个参数是干嘛用的，前端能接收到这个map值吗
![default](https://cloud.githubusercontent.com/assets/2859264/22776870/51034e6c-eeec-11e6-8dc6-43191798aeb1.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
