### ISSUE TITLE
iOS 下 toast 不显示

### ISSUE THREAD

**Issue by nyrf** [alibaba/weex#2504]
苹果7 iOS 10, 在web下显示，但在ios下不显示，其它像alert类的都能显示

**Comment by acton393** [comment]
hi @nyrf  麻烦提供一下你的例子, 还有iOS 版本号， sdk版本号，




ps: 如果可能的话也借下你的手机...

**Comment by nyrf** [comment]
直接weexpack生成的，代码直接用的官网的modal的例子，xcode编译，ios 10.2 iphone 7， weexsdk版本最新版

**Comment by dongfanghu** [comment]
我在ios中也不显示,但是在安卓都好,modal的其他都是可以的

**Comment by nyrf** [comment]
@dongfanghu 是的，我发现这个问题有人提过了https://github.com/alibaba/weex/issues/2183

**Comment by xiaohuapunk** [comment]
weex官方提供的modal其实只是个例子，自己项目中应该需要自己实现一波吧，我们是自己实现了弹窗类的module

**Comment by xubodreamsky** [comment]
html5 的 modal 弹框太小了

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
