### ISSUE TITLE
Navigator 组件和 event组件，应该用哪个打开新页面

### ISSUE THREAD

**Issue by segatecm** [alibaba/weex#2524]
我看index.vu页面用的是event.OpenURL，但是又看到有个navigator组件，到底用哪个？

**Comment by dongfanghu** [comment]
第二个 event是给你用来拓展新的交互方法的,获取userID这些啊token啊

**Comment by segatecm** [comment]
那么请问，event的文档，在哪个地方有，官网的页面上没有说明。https://weex-project.io/

**Comment by segatecm** [comment]
@dongfanghu 另外发现还有个东西叫router，这个又是什么。router.push也是单页跳转吗？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
