### ISSUE TITLE
了解到阿里有weex分发和预加载机制，请问这个方面后面有开源或开放计划吗，现在做的项目weex页面加载还是比较慢

### ISSUE THREAD

**Issue by alex1226** [alibaba/weex#2526]

**Comment by xiaohuapunk** [comment]
weex页面每次加载的时候确实比较慢，尤其list页面，明显的延时，希望后期改进

**Comment by hayvane** [comment]
同样遇到了这个问题！

**Comment by hodgevk** [comment]
我也知道这个方面能否给出解决方案，现在url加载是会有很明显的卡顿。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
