### ISSUE TITLE
【性能问题】weex页面每次加载的时候有明显的卡顿，尤其是用到list标签的页面

### ISSUE THREAD

**Issue by xiaohuapunk** [alibaba/weex#2527]

**Comment by sunorry** [comment]
同遇到这个问题，能明显看到先出现几条，后面的再出来。希望给优化下 list 的渲染性能问题。

**Comment by xiaohuapunk** [comment]
iOS 端官方提供的 list 组件 最终会渲染成原生的UITabview控件，但是没有用到cell的复用机制，望改进

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
