### ISSUE TITLE
[Android修改实现]自然滑动到底部加载更多的list，希望能帮助到有需要的朋友

### ISSUE THREAD

**Issue by HomHomLin** [alibaba/weex#2528]
效果图如下：

![Screenshot](https://github.com/HomHomLin/weex/blob/dev/list_load_1.gif)

![Screenshot](https://github.com/HomHomLin/weex/blob/dev/list_load_2.gif)

直接使用fork即可。

[https://github.com/HomHomLin/weex](https://github.com/HomHomLin/weex)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
