### ISSUE TITLE
不支持 input type=radio 吗?

### ISSUE THREAD

**Issue by sunorry** [alibaba/weex#2529]
是不支持还是我使用的不对？
```js
<input type="radio" name="sex" value="woman" />
<input type="radio" name="sex" value="man" />
```

**Comment by CCC2016** [comment]
看文档应该是不支持[<input> ](https://weex-project.io/cn/references/components/input.html)、[Web 标准 ](https://weex-project.io/cn/references/web-standards.html)；
试试[<switch> ](https://weex-project.io/cn/references/components/switch.html) 能否实现需求😁

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
