### ISSUE TITLE
【内存问题】iOS UIViewController 已经销毁 但是内存没有释放

### ISSUE THREAD

**Issue by xiaohuapunk** [alibaba/weex#2532]
```
// 页面返回 每个控制器的dealloc方法已经触发 _instance 也掉了 destroyInstance 方法
// 但是内存没有释放，一直在飙升 期望尽快解决一下 谢谢！！！
- (void)dealloc
{
    [_instance destroyInstance];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}
```

**Comment by acton393** [comment]
hi @xiaohuapunk  麻烦提供一下SDK的版本号

**Comment by xiaohuapunk** [comment]
@acton393 我是引用的最新源码，dev分支
```
#define WX_SDK_VERSION @"0.9.5"
```

**Comment by acton393** [comment]
hi @xiaohuapunk  如果源码引用的话，建议在运行一段时间以后，出现内存飙升问题后，可以用instrument 查看下memory leak

另外富文本组件已经开发完成，在 `0.10` 版本，预计这周发布，可以关注一下

**Comment by xiaohuapunk** [comment]
Hi @acton393 我们已经更新了 `0.10` 版本，但是没有看到新增的富文本组件，我们尝试在 `<text>`，标签里面使用 `<span>`标签，没有效果，编译器报错： `[fg255,165,0; <Weex>[warn]WXComponentFactory.m:173, No component config for name:span, use default config [;` 盼望回复谢谢！！！

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
