### ISSUE TITLE
Animation 位置不能复原

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#2549]
weex: 0.9.5
模拟机没有此问题
iphone 6s真机测试发生此问题

动画一： 把一个DIV的高度增加200px, 同时 translateY(-200)
动画二： 把DIV高度复原， 同时 translateY(200)

连续重复动画一和动画二多次

期望的结果： DIV的底部不动，向上伸缩

实际结果： 每次DIV的底部都有一个向下的微小位移， 重复次数多后就很明显偏离原位

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
