### ISSUE TITLE
ios refresh 和loading 不隐藏bug

### ISSUE THREAD

**Issue by chenyunecjtu** [alibaba/weex#2550]
在list里面使用refresh 和loading，如果list没数据或数据不足一屏时，refresh和loading控件隐藏不了，只有数据足够多时，这个两个控件可以正常的显示与隐藏。

通过debug，发现 refresh 和loading 控件是更加UITableView 的contentSize来控制refresh和loading的，不是根据列表的frameSize 来控制。希望阿里能修复这个bug

**Comment by chenyunecjtu** [comment]
没人回复~~~~

**Comment by chenyunecjtu** [comment]
ios list标签，在数据为空时，refresh 和loading 怎么一直显示呀，我设置成hide 也没用

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
