### ISSUE TITLE
0.9.5版本的weex 还不支持页面重新加载吗

### ISSUE THREAD

**Issue by wqd0214** [alibaba/weex#2552]
你好，之前安卓平台不能二次调用render方法渲染js文件，请问现在可以了吗？

**Comment by MrFuFuFu** [comment]
Hi, 我好像碰到跟你一样的问题，你说的这个重新加载是什么表现？

我表现是这样的，应用第一次运行的时候，加载数据是没有问题的。我退出应用后（未强行停止）再进入应用，就加载不出来了，所有跟JS this 相关的数据绑定操作都不行。但是把应用强行停止后，再进去，加载就又没有问题了

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
