### ISSUE TITLE
Weex  Tabbar 集成到iOS项目中的时候，切换页面，页面效果不展示

### ISSUE THREAD

**Issue by hengqingsheer** [alibaba/weex#2553]
Weex  Tabbar 集成到iOS项目中的时候，切换页面，页面效果不展示，playground也没有效果，单个页面调试的时候页面是正常的，一旦加入wxc-tabbar控件的时候，效果就没有展示出来，
但是同样的代码，放在安卓项目里面是正常展示的。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
