### ISSUE TITLE
weex.config取不到bundleUrl，但可以取到env

### ISSUE THREAD

**Issue by sai10cean** [alibaba/weex#2574]
**环境版本：**
android studio版本2.0
android编译SDK是23.0.2
当前使用的是weex-toolkit：1.0.1，weex_sdk:0.9.5

**问题：**
1. 实测this.$getConfig已经取不了
2. weex.config可以取到env，但是app运行时候，weex.config.bundleUrl始终没有值

请问最新版究竟如何取到bundleUrl

**Comment by dongfanghu** [comment]
weex.config.env.bundleUrl?

**Comment by MacSzh** [comment]
请问解决了？我也遇到类似的问题

**Comment by jiyinyiyong** [comment]
我们也遇到过 `bundleUrl` 没有值, 后来发现是 Native 代码里调用 SDK 时没有正确设置.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
