### ISSUE TITLE
当还在刷新过程中，滑动到最底部后，刷新部分会一直显示，不会消失，也不能刷新了。

### ISSUE THREAD

**Issue by 1903514970** [alibaba/weex#2577]
版本号：0.9.5
![image](https://cloud.githubusercontent.com/assets/15099256/22965657/8e0a3260-f399-11e6-8cc0-df3b539259bd.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
