### ISSUE TITLE
为毛PC playground 和移动端显示差别这么大？

### ISSUE THREAD

**Issue by codedart2018** [alibaba/weex#2584]
不多说 看图吧 今天做了官网两个示例 modal 位置在太坑了！
http://static.ycoto.cn/weex_issue/1.jpg
http://static.ycoto.cn/weex_issue/2.png

还有个轮播图上图 在手机上不自动轮播 下面我加了一个文本条在playground上面显示 正常移动端下不显示。
http://static.ycoto.cn/weex_issue/3.jpg
http://static.ycoto.cn/weex_issue/4.png

**Comment by DoranYun** [comment]
第一个问题，H5 和 native 没有抹平的差异，我们会继续优化。
第二个问题，目前已知 bug，编译 jsBundle 时未将标签属性转换为驼峰式，这个bug已经在修复中，目前可以使用驼峰式书写标签属性进行兼容 `<slider autoPlay="true">`。
文本条不现实的问题，麻烦贴出源码。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
