### ISSUE TITLE
有两个问题： weex的if用法 和数据更新问题

### ISSUE THREAD

**Issue by 1021727984** [alibaba/weex#2591]
目前遇到两个问题：
1.查看了官方文档，weex和vue 2.x的区别，里面明确讲到weex 的if用法的不同
  weex： if="{{!foo}}"	vue： v-if="!foo"
但是使用过程中，发现weex的用法会报错，http://dotwe.org/vue/0040e7e269ae3d9d5082bf008f7e8def   这是在playground运行的代码，如果用vue 2.0的用法使用就正常
2. 在手机端的playground中运行，数据更新了，但是绑定数据的dom 却没更新，但是在web端的是正常的，
我的代码http://dotwe.org/vue/5ee62f9e8a9eb7cd102fd76ca74e6fe2

**Comment by DoranYun** [comment]
第一个问题，你选择的语法模式是 vue，但代码第四行使用了旧语法 `if="{{shown}}"`。
第二个问题，我这边测试了一下是可以的。你debugger一下看看有什么报错。

**Comment by 1021727984** [comment]
@DoranYun 请问官网上的文档所说的与vue2.0的区别是都指旧语法的吗，http://weex.incubator.apache.org/cn/references/migration/difference.html，新语法完全按vue2.0的写法吗

**Comment by DoranYun** [comment]
是的，新语法直接参考 vue 2.0

**Comment by 1021727984** [comment]
好的，谢谢，建议官网文档要整理下，我们这些初学者很是混乱

**Comment by 1021727984** [comment]
第二个问题还在看，请先不要把问题关闭

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
