### ISSUE TITLE
android中image标签中placeholder不管用

### ISSUE THREAD

**Issue by 13754327232** [alibaba/weex#2595]
使用了placeholder和place-holder都不管用，求解答，weexsdk是0.9.5

**Comment by xkli** [comment]
@13754327232 placeholder不是直接可用的和图片下载一样，是需要用户自己进行下载实现的。
1. Weex用类imageStrategy中的属性placeholder来标示placeholder的URL地址
2. 使用图片库的对placeholder进行下载。

**Comment by 13754327232** [comment]
@xkli 我用了adapter中的imageStrategy的placeholder，但是为null
![2](https://cloud.githubusercontent.com/assets/25242004/23008096/48396f9e-f448-11e6-8406-65d7d4144bc1.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
