### ISSUE TITLE
[html5]list组件header在html5无效

### ISSUE THREAD

**Issue by huixisheng** [alibaba/weex#2601]
demo地址: http://dotwe.org/vue/ff9e307c67e63ccd7218c1dc3642f2af

html5预览的时候没有看到header的内容,ios扫码正常

**更新了Weex Playground 安卓崩溃问题已经修复**
~~安卓扫码直接崩溃如下图:~~
![wechatimg236](https://cloud.githubusercontent.com/assets/1518967/23011037/8b72292a-f459-11e6-85e3-50024f77dce0.jpeg)

版本信息:
![wechatimg237](https://cloud.githubusercontent.com/assets/1518967/23011039/8bc43706-f459-11e6-9b01-4be57ca8a00e.jpeg)

手机型号: 华为PE-UL00

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
