### ISSUE TITLE
weex scroller  没有横向滚动？

### ISSUE THREAD

**Issue by dericgit** [alibaba/weex#2608]
scroller 能否提供一个横向滚动的方式？
例：
```
<scroller class="scroller"  :direction="row">
      <div class="row" v-for="(name, index) in rows" :ref="'item'+index">
        <text class="text" :ref="'text'+index">{{name}}</text>
      </div>
    </scroller>
```

**Comment by linfuxiang** [comment]
可以用flex布局手写一个，就几行代码

**Comment by happybobo** [comment]
@linfuxiang 属性不被支持啊

**Comment by happybobo** [comment]
scroll-direction {string}：可选为 horizontal 或者 vertical，默认值为 vertical 。定义滚动的方向

**Comment by 1903514970** [comment]
@happybobo 我设置了scroll-direction = 'horizontal' ，虽然是横向的，但是不可以滑动，你知道怎么回事吗？

**Comment by happybobo** [comment]
@1903514970 这个属性能在iOS平台上可滚动，但是在web上不行

**Comment by 1903514970** [comment]
@happybobo 谢谢，我再看看是不是我写错了。我是android端。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
