### ISSUE TITLE
通过playground扫描vue文件生成的二维码显示不出来

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2611]
写了一个简单的vue格式的文件，通过weex test.vue 可以运行起来，并且在浏览器中也看得是正常的。但是通过playground扫描二维码的时候就显示不出来，我的网络没问题，因为同样的we文件就可以显示出来。

**Comment by Hanks10100** [comment]
请确认你 playgroud 中 WeexSDK 的版本，需要 0.9.5 或以上才支持 Vue。

![weex-env](https://cloud.githubusercontent.com/assets/8401776/23029219/b706b51a-f4a4-11e6-9285-8c9ee4ac79cf.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
