### ISSUE TITLE
style color custom value

### ISSUE THREAD

**Issue by li6185377** [alibaba/weex#2615]
由于我们应用有换肤功能，所以我们的色值都是用key来表示，webpack 编译阶段，好像有对 color值 做验证，由于是自定义 value 所以color 样式就被忽略了

有什么办法关闭 webpack 的color值验证吗？

```
<text class="xx">Hello Weex!</text>
<style>
  .xx {
    color: Key;
    font-size:42;
  }
</style>
```

生成的 js

```
module.exports = {
	  "xx": {
                "fontSize": 42
	  }
```

weex 页面只用手机应用内部，不会生成网页，在 SDK 层，我们会对 key 转换成 color

**Comment by karynsong** [comment]
转到 vue，可以使用 Sass 语法来支持

**Comment by li6185377** [comment]
webpack 是在哪里对 color 值做判断的呢？ 我可以直接去改源码

**Comment by hayvane** [comment]
@karynsong  现在我已经使用vue了，如何对sass 支持，能给个demo吗？

**Comment by xxxxxMiss** [comment]
@karynsong vue如何支持sass，去看vue官方文档即可

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
