### ISSUE TITLE
父与子通信取值undefined

### ISSUE THREAD

**Issue by 13754327232** [alibaba/weex#2618]
父与子通信通过this.$([String id])不对吗，获取出来是undefined
![3](https://cloud.githubusercontent.com/assets/25242004/23050879/fcb2df52-f4ff-11e6-9db2-3ddd83ccea49.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
