### ISSUE TITLE
使用weexpack构建iOS项目图片加载不了

### ISSUE THREAD

**Issue by DoubleDa** [alibaba/weex#2624]
使用weexpack构建iOS项目
运行命令：
weexpack run ios
之后选择mac自带模拟器
请求API接口成功
就是图片加载不了
求解

**Comment by Snoopy008** [comment]
图片需要指定宽和高，不能用百分比设置。

**Comment by karynsong** [comment]
真机上做了代理图片也会加载不出来

**Comment by Cedric-song** [comment]
同样的问题，iOS存在这个问题

**Comment by jasonhe88** [comment]
在和IOS集成时遇到同样的问题， 用官方例子也出不来， 高宽已设置

**Comment by jasonhe88** [comment]
对了， 版本号是0.10.0

**Comment by Snoopy008** [comment]
img标签用了不起作用，需要用image标签

**Comment by jasonhe88** [comment]
img 和 image 都试过， 没用

**Comment by ijry** [comment]
需要安装插件或者自己实现图片下载协议

**Comment by sjbwylbs** [comment]
用webpack打包的图片地址比较特殊。有两种方案：
1. 设置output的子属性 publicPath
2. 使用绝对地址

**Comment by ijry** [comment]
publicPath怎么设置

**Comment by keepJion** [comment]
这个已经无解了么?

**Comment by keepJion** [comment]
@DoubleDa 你已经解决了么???

**Comment by karynsong** [comment]
用 charles 就可以访问图片了。代理 ip 和端口都设置一下，就可以访问图片了

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
