### ISSUE TITLE
关于0.10 wx web端如何进行转换 

### ISSUE THREAD

**Issue by Roxyhuang** [alibaba/weex#2629]
目前尝试了0.10的wx单位可以在客户端生效，但是web无法识别该单位，是否有支持文档或者转换方法

升级了：   "weex-loader": "^0.4.4", weex-vue-loader": "^0.2.11"  "weex-devtool": "^0.2.77",

根据pr 查看 weex-vue-html5 更新 weex-vue-render 并未更新 ，项目中引入的为 weex-vue-render

**Comment by markzhai** [comment]
any updates？

**Comment by Roxyhuang** [comment]
any updates or solution  @acton393

**Comment by MrRaindrop** [comment]
web 端已支持. 参见这个例子： http://dotwe.org/vue/303bd8736037d1ced41b5f39eb10d744  在右边 preview 是看不出来差别的，因为是在 iframe 里. 在新页面打开：http://dotwe.org/raw/htmlVue/303bd8736037d1ced41b5f39eb10d744?1513837200372&p=true 然后打开 chrome devTool 模拟移动端可以看到 px 和 wx 的差别.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
