### ISSUE TITLE
在iOS下 sliced image 居然可以包含子组件

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#2644]
官方文档里说image组件不能包含任何子组件， 今天由于一个TYPO, 意外发现在iOS下， 如果image图片是本地sliced图片 (即局部可拉伸图片) 的话，包含的文字子组件完美包含在图片里，误打误中解决了一个大问题， 希望官方不要关掉这个特性 ：-）

补充，没有设置resize属性， 也没有设置宽和高，这个IMG标签是我自己扩展的，因为官方的image 说是有local:///path, 但是用在image上不管用， 所以自己扩展了一下

**Comment by jasonhe88** [comment]
还没试过ANDROID版， 希望也能如此  :-)

**Comment by xiaohuapunk** [comment]
Hi @jasonhe88 能否贴一下你的代码，参考一下谢谢!

**Comment by jasonhe88** [comment]
<img><text></text></img>

就这样，:-)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
