### ISSUE TITLE
]WXBridgeContext.m:285, No send queue for instance:3, may it has been destroyed so method:fireEvent is ignored [;

### ISSUE THREAD

**Issue by solaronke** [alibaba/weex#2645]
在真机调试的时候，页面跳转出现这个错误信息：
2017-02-18 21:01:21.120 WeexDemo[20166:1822415] [fg100,149,237; <Weex>[info]WXBridgeContext.m:285, No send queue for instance:3, may it has been destroyed so method:fireEvent is ignored [;

急！！！

**Comment by solaronke** [comment]
这个错误是因为路径不对，改过来了

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
