### ISSUE TITLE
no <audio> component

### ISSUE THREAD

**Issue by coronaz** [alibaba/weex#2647]
I found the <video> component, but no <audio>. when to release according to the plan? if my app needs audio, can I use weex now?

**Comment by zk0301** [comment]
you can write a custom module.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
