### ISSUE TITLE
用 weex home.vue  运行，chrome console  输出 Uncaught TypeError: weex.requireModule is not a function

### ISSUE THREAD

**Issue by fantengfei** [alibaba/weex#2648]
- weex version: v1.0.1-beta.6
- weex-loader: weex-loader@0.4.4

.vue 文件中引入：`var navigator = weex.requireModule('navigator')`，
用 `weex home.vue` 打包，报如下错误：

<img width="482" alt="2017-02-19 23 58 16" src="https://cloud.githubusercontent.com/assets/8567951/23103974/95e64eba-f6ff-11e6-808b-5b667d5fc29b.png">

但是用 `npm run build` 打包没有问题。

**Comment by fantengfei** [comment]
如果需要更多信息，我随时提供，谢谢

**Comment by JackPu** [comment]
@fantengfei  你运行文件预览的时候你在chrome console试着输入`weex`试下，看打出什么信息？

![image](https://cloud.githubusercontent.com/assets/4744967/23794859/6389da18-05cd-11e7-85b1-06261605251f.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
