### ISSUE TITLE
npm run dev报错。

### ISSUE THREAD

**Issue by includeleec** [alibaba/weex#2650]
win10 64位 在git bash
![image](https://cloud.githubusercontent.com/assets/3683190/23109194/b285348a-f751-11e6-8c1f-60e49246c1f4.png)

根据教程执行到这里，就不动了。强制ctrl+C。
cnpm install 没有问题。但是执行npm run dev就报错了。
![image](https://cloud.githubusercontent.com/assets/3683190/23109296/d0584b4a-f752-11e6-91c8-9cca5c3e6a92.png)

**Comment by sjbwylbs** [comment]
用的是cnpm install 是吧？请执行如下步骤:
1. npm install 
2. npm run dev

就可以了。

基本上用cnpm 命令安装的依赖，都是需要用npm 重新install一次才能安装好依赖。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
