### ISSUE TITLE
iOS  0.9.5.3版本的SDK怎么增加请求头

### ISSUE THREAD

**Issue by ZeroJson** [alibaba/weex#2652]
__attribute__ ((deprecated("Use WXResourceRequestHandler instead")))
找不到WXResourceRequestHandler这个类

**Comment by captain-black** [comment]
我也是找不到，感觉是头文件没导出来，然而就这样发布到cocoapods了

**Comment by acton393** [comment]
hi  @ZeroJson  `WXResourceRequestHandler` 这个是public 的，SDK有一份default的handler， 你也可以覆盖 它的实现

**Comment by ZeroJson** [comment]
怎么覆盖实现，可以详细告诉我吗？ 覆盖那个类？之前我重写过WXNetworkProtocol的sendRequest方法来实现增加请求头的内容的，现在我该怎么做

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
