### ISSUE TITLE
[android] ui render error

### ISSUE THREAD

**Issue by zhoukekestar** [alibaba/weex#2664]
Android SDK version: 0.9.4 (latest apk)

```html
<template>
  <div>
    <div>
      <text>hello world</text>
    </div>
    <div>
      <input type='hidden' style='height: 0; width: 0' name='hidden-key' value='hidden-value'>
      <text>hello world #2</text>
    </div>
    <div>
      <input type='hidden' name='hidden-key' value='hidden-value'>
      <text>hello world #3</text>
    </div>
  </div>
</template>
```

| Android screenshot: (error) | iPhone screenshot: (correct) |
| --- | --- |
| ![835565565304764269](https://cloud.githubusercontent.com/assets/7157346/23115832/59073f30-f782-11e6-8d62-3bd328ac3775.png) | ![803468317663195454](https://cloud.githubusercontent.com/assets/7157346/23115833/5907feca-f782-11e6-8438-afd7020a4578.jpg) |

Web screenshot: (correct)
![qq 20170220153612](https://cloud.githubusercontent.com/assets/7157346/23115834/591b5696-f782-11e6-9b5a-91f7dbb9ebf9.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
