### ISSUE TITLE
onScroll 事件被移除了？？？？

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#2665]
更新0.10.0的SDK，发现list的onScroll方法无效不再调用了，然后在文档中也没有发现list和scroll有onScroll事件，想问一下onScroll是否被移除了，如果被移除了 该用什么方法监听list滚动事件

**Comment by misakuo** [comment]
将会在0.11版本中提供

**Comment by emptywalker** [comment]
0.11 这个feature现在可以用了吗？  大概需要多久会出？
这个事件升级也不用先移除啊 -_-

**Comment by misakuo** [comment]
我查了下代码，以前只有slider组件有scroll事件，其他两个组件是最近添加的，在这里https://github.com/alibaba/weex/pull/2450

**Comment by emptywalker** [comment]
之前list 和 scroll都有这个onScroll方法，我们app中之前在list中有这个方法，结果发现更新sdk后，这个效果没有了

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
