### ISSUE TITLE
无法安装week-toolkit

### ISSUE THREAD

**Issue by 9kill** [alibaba/weex#2669]
![image](https://cloud.githubusercontent.com/assets/7374500/23117509/02826c3a-f78b-11e6-8950-ba924f2abe5b.png)
window7系统gost版本，是系统的原因吗

**Comment by JackPu** [comment]
@bethebest  您能提交下你的错误信息么？截个图什么的？😁💐

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
