### ISSUE TITLE
0.10.0的demo 启动start报错

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#2671]
![image](https://cloud.githubusercontent.com/assets/6778148/23117875/c1992540-f78c-11e6-9424-c017e04c7274.png)
0.10.0的demo，启动start报错，已经npm install了
![image](https://cloud.githubusercontent.com/assets/6778148/23117908/e5a0fc10-f78c-11e6-8f7b-f5a4d77b3e54.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
