### ISSUE TITLE
几个小问题想了解一下

### ISSUE THREAD

**Issue by walid1992** [alibaba/weex#2676]
有几个小问题想咨询一下：
1、现在基于vue2.0 ，有一个成熟的开发方案了吗？
2、vue是单页模式，在原声中会是单页形态吗？weex-hackernews 看上去有些卡顿
3、weex-pack 多久会支持vue文件打包？
4、文档建设和web标准化还在进行吗？
5、与vue2.0生态互通到什么程度了呢？

**Comment by hetz** [comment]
我觉得最奇怪的是为什么不把语法做得一致呢，就这个页面看来，很多语法其实只是字面的意思，不知道为什么weex非得特殊化。
https://weex-project.io/cn/references/migration/difference.html

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
