### ISSUE TITLE
click事件中app中返回的事件对象与H5返回的事件对象不同

### ISSUE THREAD

**Issue by fromIRIS** [alibaba/weex#2677]
H5中使用vue2 click事件返回的事件对象为原生的事件对象，如下图
![image](https://cloud.githubusercontent.com/assets/8492963/23120369/08b30144-f797-11e6-8200-3fcd266dbe0e.png)

而在app中click事件返回的事件对象是weex处理过的，两者表现不同

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
