### ISSUE TITLE
2个bug反馈

### ISSUE THREAD

**Issue by goodyorkye** [alibaba/weex#2678]
一、ios版本0.9.5.2经常出现崩溃，error是 component not exists , 0.9.5.3 修复了，但是升级到0.10.0又出现了。
二、android版本we文件中div的样式，设置了 border-radius ，并且设置了background-color 为红色，但是显示出来后除了中间是红色，周围全是黑色，加上opacity < 1的值才正常

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
