### ISSUE TITLE
在iOS上面，如何在native端调用页面上面的js

### ISSUE THREAD

**Issue by emmanuelwang** [alibaba/weex#2679]
我在a页面push到b页面，然后从b页面pop回a了以后，想让a去刷新一下界面上的数据，在vue文件中，viewappear事件只能在a-b的时候，b页面才会调用，然后想在controller里面，通过globalevent来调用，但是由于我的主页是用tabbar做的，所以那个WXSDKInstance并不是我那个页面的,也掉不到，不知道又没什么好一点的方法能够解决这个问题

**Comment by weivea** [comment]
同问

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
