### ISSUE TITLE
android list loadmoreoffset 属性 没有触发loadmore事件

### ISSUE THREAD

**Issue by chenyunecjtu** [alibaba/weex#2684]
代码：http://dotwe.org/weex/b3562ee639eac0c4db60e3a75dc4a2e1
在浏览器上表现正常，在android手机上测试，loadmore事件不起作用

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
