### ISSUE TITLE
touch事件改变div位置，改变style.top和style.left属性不起作用

### ISSUE THREAD

**Issue by 13754327232** [alibaba/weex#2685]
改变style.top和style.left
![2](https://cloud.githubusercontent.com/assets/25242004/23149834/bd90e634-f829-11e6-990f-85ef26479080.png)
属性不起作用

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
