### ISSUE TITLE
exception:TypeError: Object [object Object] has no method 'registerModule'

### ISSUE THREAD

**Issue by lorcanluo** [alibaba/weex#2686]
按照官方文档
```
weex.registerModule('guide', {
  greeting () {
    console.log('Hello, nice to meet you. I am your guide.')
  },
  farewell () {
    console.log('Goodbye, I am always at your service.')
  }
})
```
在android端调用出现如下错误：

![image](https://cloud.githubusercontent.com/assets/4537749/23149859/ebb63a64-f829-11e6-9c87-4affb06f56fe.png)

**Comment by parrotdance** [comment]
出现了类似的错误
entry.js 中已引入 weex-vue-render, 在组件中使用 weex.registerModule 注册组件时提示如下:
<code>weex.registerModule is undefined</code>

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
