### ISSUE TITLE
对list进行分组有没有进一步的解决方案

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#2687]
### 对于在订单列表管理的模块中，通常是一个店铺一个订单，一定订单中会出现多个商品，这时候就需要分组来区分订单，然后复用显示商品的cell，如下图，一个是多个商品的订单，一个是单个商品的订单。
![demo2](https://cloud.githubusercontent.com/assets/12522809/23149943/768b63e4-f82a-11e6-9ddf-bdb8f5518b18.png)
![demo1](https://cloud.githubusercontent.com/assets/12522809/23149949/7bd87684-f82a-11e6-8c2f-eed8ebe2bbd6.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
