### ISSUE TITLE
vue写的导航条，键盘出来后上移

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#2688]
![image](https://cloud.githubusercontent.com/assets/6778148/23150105/cc1306ea-f82b-11e6-8491-565328de6c52.png)
![image](https://cloud.githubusercontent.com/assets/6778148/23150107/d063e980-f82b-11e6-9266-a40ebb9771e7.png)
vue写的导航条，键盘出来后上移超出屏幕了，对于这种情况，请问有人知道有什么解决方案吗，iOS的sdk做了rootview的上移处理。

**Comment by dongnaebi** [comment]
建议做fixed元素不跟着上移的处理

**Comment by acton393** [comment]
hi @yfldj  如 @dongnaebi  所说的，尝试下 fixed 元素

**Comment by yfldj** [comment]
@acton393 试过fixed也是不行的。我看了sdk的源码，iOS是整个weex的rootview的y都改变了。

**Comment by dongnaebi** [comment]
@acton393 建议是给你的 :-D，这个确实很影响体验，只能把输入框写在顶上。

**Comment by acton393** [comment]
@yfldj  @dongnaebi  fixed 元素是挂在 rootView 上， 现在input 框在弹出键盘的时候，是会把rootView往上拉，考虑到键盘会挡住地下的input框

**Comment by dongnaebi** [comment]
@acton393 有个方案可以考虑下，`<div role='fixed'></div>`，取到`role=fixed`的话，输入框聚焦时rootView上移多少，fixed元素就在原基础上下移多少。或者把`role=navbar`扩展的灵活一点。。。安卓也有这个问题

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
