### ISSUE TITLE
能否给list加一个视图更新完后的回调？

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#2689]
场景是这样的：

给list绑定的数组添加一项后list自动更新， 需要在更新完后有个回调做一些动作，比如scroll to end

谢谢

**Comment by jasonhe88** [comment]
现在的方案是用setTimeout设个定时器做scrollToElement的动作

**Comment by YongX** [comment]
这个应该可以不止用于 list，所有新增加的元素如果成功渲染到页面后都可以有一个回调可以供操作就很赞了。

我这边之前遇到的场景也类似，是点击按钮后需要动态新增一个元素，对这个元素做动画操作。

比如点击加入购物车，会有一个元素飞入购物车的动画。

**Comment by zhzhy** [comment]
是的，这种场景确实不少，尤其是在复杂交互下。

**Comment by jasonhe88** [comment]
@YongX 对于你的这个问题我的解决办法是把这个元素先创建好，放在屏幕之外，需要动画是先用我自己扩展的办法设置position后再做动画，供参考

**Comment by liuzhiyi1992** [comment]
目前list加入元素后无回调支持，如果立刻scrollToElement到最后一个元素立刻越界闪退，设timeout及时性不好，也有crash风险

**Comment by jasonhe88** [comment]
@liuzhiyi1992  那咋办呢，，，，？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
