### ISSUE TITLE
为何在playground里可以看到背景颜色渐变效果，在真机里看不到呢？

### ISSUE THREAD

**Issue by solaronke** [alibaba/weex#2692]
在playground里可以看到背景颜色渐变效果，但是我把我的项目放在真机里测试，发现背景没有渐变效果？如何解？

**Comment by DoranYun** [comment]
线性渐变在 0.10 才开始支持。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
