### ISSUE TITLE
url-loader生成的图片地址不能直接显示

### ISSUE THREAD

**Issue by nicefan** [alibaba/weex#2697]
```js
_c('img', { 
  staticStyle: {"width": "200px", "height": "200px"},  
  attrs: {  
    "src": "http://192.168.253.109:8079/dist/img/logo.82b9c7a.png"  //图片可以显示 
  }  
})
```

```js
_c('img', {
  staticStyle: { "width": "200px", "height": "200px" },
  attrs: {
    "src": __webpack_require__(58) // 图片不能显示
  }
}) 
```

```js
_c('img', {
  staticStyle: { "width": "200px", "height": "200px"  },
  attrs: {
    "src": _vm.logo // 图片可以显示。
  }
 })
  exports.default = {
    data: function data() {
    return {
    logo: __webpack_require__(58),
       msg: 'Welcome to Your Vue.js App！！！'
    };
  }
};
```
以上代码webpack编译生成，在使用url-loader时，如果图片地址写在标签中，编译后不能显示，只能够写在data中，用require引用。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
