### ISSUE TITLE
arm64-v8 Android 初始化报错

### ISSUE THREAD

**Issue by wangweiqi23** [alibaba/weex#2707]
com.taobao.weex.bridge.WXBridgeManager.initFramework(SourceFile:1033)
com.taobao.weex.bridge.WXBridgeManager.invokeInitFramework(SourceFile:1013)

**Comment by wangweiqi23** [comment]
版本0.8.0.6

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
