### ISSUE TITLE
wxc-navpage如何添加自定义样式?

### ISSUE THREAD

**Issue by tangjion** [alibaba/weex#2708]
wxc-navpage组件无法渲染自定义的class样式，加style也不行，请问应该怎么添加怎么定义的样式呢？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
