### ISSUE TITLE
android中js回调执行时序滞后

### ISSUE THREAD

**Issue by xxiiaass** [alibaba/weex#2710]
android,week sdk 0.9.4, 页面初始化时没问题，但是运行了一会儿（也有可能是weex的页面间切换了多次后），回调执行变慢。

比方说，抓包看到，网络请求很早就返回数据了，但是，网络请求注册的回调，却要等待1秒钟（这个时间随着运行时间会递增，200ms-几秒钟不等）后才执行。

还有就是，通过注册module的方式，java代码执行js注册的一个回调函数，也是同样的情况，

js代码中的异步操作，都是通过await async 写的。

同一份代码，在ios中并没有这个问题。

不是机器的问题，2500的旗舰机和500的低端机都存在这个问题。

**Comment by zk0301** [comment]
用的是0.10.x，没遇到过。

**Comment by jimmyrogue** [comment]
@xxiiaass 我也遇到类似的情况，请问你有找到什么解决方案吗？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
