### ISSUE TITLE
weex plugin jar以及资源文件引用

### ISSUE THREAD

**Issue by saky0542** [alibaba/weex#2711]
weex plugin怎么把jar包以及资源文件在插件安装的时候copy过去，应该在plugin.xml里面怎么配置，采用cordova的配置方法有误，非常感谢。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
