### ISSUE TITLE
Playground App第一扫描可以呈现，第二次扫描或者刷新不再显示

### ISSUE THREAD

**Issue by Snoopy008** [alibaba/weex#2713]
今天早晨出现的问题，第一次扫描界面可以在App上展示，可是后面刷新或者再次扫描，App内都不呈现界面。然后将js文件直接copy到iOS或Android项目内部运行是可以跑起来的，主要还是playground的问题，请问是什么问题？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
