### ISSUE TITLE
0.10SDK ios中使用broadcast channel无法正常运行

### ISSUE THREAD

**Issue by emmanuelwang** [alibaba/weex#2715]
照着官方的文档，在created中创建了 const Stack = new BroadcastChannel('Avengers')

但是在iOS中运行的时候却报了

eferenceError: Can't find variable: BroadcastChannel
created
xe@main.js:3:17532
_init@main.js:3:20155
a@main.js:3:21254

__webpack_require__

anonymous
Dt@main.js:3:31731
main.js:7:1153 [;

**Comment by hodgevk** [comment]
安卓0.10.0也是同样报错

**Comment by luckcoding** [comment]
使用weex语法没有问题，但用vue语法，有同样错误。

**Comment by yans67** [comment]
请问解决了吗？我的 weex 是0.10版本也遇到这个问题，vue 是2.1.10。

**Comment by angelozhou** [comment]
我也是遇到这个问题， 可是官方文档说9.0版本以上就可以通用3端的， 这文档是怎么回事

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
