### ISSUE TITLE
Unhandled promise rejection {"ok":false} 

### ISSUE THREAD

**Issue by TuDoudong** [alibaba/weex#2722]
模拟器运行ok 真机运行出现error  
[fg255,0,0; <Weex>[error]WXJSCoreBridge.m:86, jsLog: Unhandled promise rejection {"ok":false}  [;

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
