### ISSUE TITLE
ios端 weex跳weex界面,导航栏隐藏不掉

### ISSUE THREAD

**Issue by slidoooor** [alibaba/weex#2725]
更新了新版本,多出了一个系统默认的导航栏,而且用尽了所有方法也隐藏不掉,,求解决...

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
