### ISSUE TITLE
:active伪类不生效

### ISSUE THREAD

**Issue by chenzefeng09** [alibaba/weex#2726]
我的.we文件里有如下样式

     .rebuy_button {
        color: #00ac8b;
        border-color: #00ac8b;
        margin-left: 24;
        border-width: 1;
        font-size: 28px;
        flex: 1;
        padding-top: 18px;
        padding-bottom: 18px;
        text-align: center;
        border-radius: 2;
        margin-top: 36px;
        margin-right: 24;
        margin-bottom: 28;
        background-color: white;
    }
    .rebuy_button:active {
        color: white;
        background-color: #00ac8b;
    }

在使用weex debug命令调试时，生成的js文件是正常的，包含:active部分
![image](https://cloud.githubusercontent.com/assets/7556537/23204311/069428bc-f921-11e6-85f0-fa9ad6e02143.png)

但是在使用./start脚本或者weex debug -m transformer时，生成的js都没有:active
![image](https://cloud.githubusercontent.com/assets/7556537/23204377/5a9abf7a-f921-11e6-8a70-60cb0cc50bad.png)

weex dev-tool 版本:0.2.77

**Comment by kfeagle** [comment]
@exolution

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
