### ISSUE TITLE
执行了weex hello.we却无法页面访问

### ISSUE THREAD

**Issue by jingxiawl** [alibaba/weex#2728]
新手接触weex，看了教程，建了一个最简单的hello.we 文件，
内容如下:
![image](https://cloud.githubusercontent.com/assets/11657532/23208250/4019e578-f92f-11e6-8044-e42d891de354.png)
执行了weex hello.we执行也成功了：
![image](https://cloud.githubusercontent.com/assets/11657532/23208382/c0aeb3c6-f92f-11e6-9bba-29091d9814e2.png)
却没有自动打开浏览器，访问该地址也没得任何东西，看了半天都没找到怎么解决。：
![image](https://cloud.githubusercontent.com/assets/11657532/23208426/ebe992a4-f92f-11e6-8b27-32896e2fb1fb.png)
我看很多教程都是这样写的，但是为什么我的执行不出来呢？求问，新人急需支持

**Comment by JackPu** [comment]
@jingxiawl 表示端口已经被占用了，你可以试下weex hello.we --port 8088 --wsport 8089 修改下端口。如果不行，你也可以重启电脑就ok啦，这是最粗暴的方法，

**Comment by jingxiawl** [comment]
@JackPu  谢谢，已经解决，主要是没有报错我也一脸懵逼==。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
