### ISSUE TITLE
wxc-tabbar不见了？

### ISSUE THREAD

**Issue by yongningfu** [alibaba/weex#2730]
在文档中没看到 wxc-tabbar 是将要被被移除的意思？

**Comment by DoranYun** [comment]
自定义组件不再维护，可自己实现：参考 https://github.com/weexteam/weex-components/blob/master/src/wxc-tabbar.we

**Comment by dailc** [comment]
官方那个基于vue的tabbar组件 在web端提示   "embed组件"不支持，请问还需要做其他处理的么?应该怎么样去解决？多谢！
![image](https://cloud.githubusercontent.com/assets/6134890/23351481/60d3f4cc-fcfc-11e6-8679-61bcb6cc2c77.png)

**Comment by jinyb09017** [comment]
请问什么在vue里面支持embed呀，不然现在的tabbar如何做实现呢

**Comment by totzcc** [comment]
@dailc 
我解决了在H5 不能显示 tabbar embed 的问题. 同时兼容 iOS 和 Android

https://github.com/totzcc/weex-tabbar

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
