### ISSUE TITLE
market上的插件只能装在weexpack create的工程里面吗

### ISSUE THREAD

**Issue by huahmj** [alibaba/weex#2734]
有没有什么具体的说明文档？

**Comment by JackPu** [comment]
@AugHua  只能通过weexpack工具安装，安装插件的说明移步[这里](https://github.com/weexteam/weex-pack)

**Comment by AugHua** [comment]
@JackPu 那请问  是必须装在通过weexpack create搭建的工程中吗？

**Comment by JackPu** [comment]
@AugHua 嗯，目前是这样的，必须在create里的目录进行创建

**Comment by AugHua** [comment]
@JackPu OK  多谢指导

**Comment by JackPu** [comment]
谢谢支持，我们后面会想办法支持非标准目录的使用，😄💐。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
