### ISSUE TITLE
* [ios] sdk 0.10.1 版会重置用户设置的 handler

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#2738]
比如设置了 `WXNavigationProtocol` 的handler，再 push 进一个新界面的时候都被重置成默认值了。
参考这个 pr： https://github.com/alibaba/weex/pull/2555

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
