### ISSUE TITLE
weex编译文件没有生成任何文件

### ISSUE THREAD

**Issue by jingxiawl** [alibaba/weex#2739]
我看了官方文档，文档说编译成js文件的时候执行
![image](https://cloud.githubusercontent.com/assets/11657532/23248990/1472f776-f9dd-11e6-8dc2-f36f90885087.png)

我执行了代码却没有生成任何文件啊。怎么回事，搞不懂。直接打开浏览器了，跟执行weex hello.we一样的效果
![image](https://cloud.githubusercontent.com/assets/11657532/23248954/e8e4c6ac-f9dc-11e6-8df2-95078ad7c428.png)
浏览器打开效果
![image](https://cloud.githubusercontent.com/assets/11657532/23248967/f61015a2-f9dc-11e6-93e3-d4308a4c4db6.png)
到底要怎么打包啊

**Comment by zk0301** [comment]
weex版本的问题。我也遇到过，坑死。beta版本的weex会有这个问题，后来我换成alpha的了。

**Comment by jingxiawl** [comment]
@zk0301   怎么切换版本啊。才接触weex感觉到处都是坑。资料也不好找，完全觉得不好用。这个还有必要用么？

**Comment by jingxiawl** [comment]
@zk0301  而且不知道怎么完整的搭建一个项目。你有相关资料么？

**Comment by zk0301** [comment]
哥们你问题太多了，我也是新手，加我QQ吧 723425361

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
