### ISSUE TITLE
weex加载本地本地沙盒中的JS文件,不能渲染.iOS

### ISSUE THREAD

**Issue by MrPotatoSun** [alibaba/weex#2748]
从服务器上获取js文件,下载到本地沙盒中,在没有网络的时候加载沙盒的JS文件,但是会出现问题,加载单个的刻意渲染到页面,但是如果是多个js文件,就不能渲染,打开的页面是空白的.这些js文件是有关联的,应该怎么处理,

**Comment by zk0301** [comment]
跳转传入的bundleurl有问题。

**Comment by YanLYM** [comment]
@zk0301  
bundleurl,应该怎么传呢？可以详细说一下吗

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
