### ISSUE TITLE
求<transition>过渡标签使用demo

### ISSUE THREAD

**Issue by xxiiaass** [alibaba/weex#2749]
官网文档上只写了说支持这个标签的使用，但是没有任何例子。
weex之前的动画都是animation这个模块函数调用的，现在改用标签，怎么使用根本没头绪啊。使用了一段vue的代码，很明显报错。
先谢谢了。

**Comment by greyhu** [comment]
调试时会报错：
WXComponentFactory error type:[transition] class not found
另外源码里也没有transition这个component的实现。所以文档肯定有问题

**Comment by GeoffZhu** [comment]
应该是不支持，文档够烂

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
