### ISSUE TITLE
weex ios端input组件问题

### ISSUE THREAD

**Issue by slidoooor** [alibaba/weex#2758]
因为想要写一个搜索框,但是weex本身的input没有search这个属性,于是自己定义了一个拓展,基本就是把weex源码拷贝了一下,然后改了一下returnkeytype,但是发现即使给input的属性,就是returnkeytype设置成nsreturnkeysearch,弹出来的键盘返回按钮还是默认的前往,麻烦问下大家有遇到过这种情况吗?要如何解决

**Comment by acton393** [comment]
hi @slidoooor  麻烦提供一下cocoaPods 上SDK的版本号，或者使用的分支

**Comment by kfeagle** [comment]
@slidoooor returnkeytype 这个功能还在测试中，目前还只能在https://github.com/alibaba/weex/tree/0.11-dev 分支生效，建议这个版本正式发版后使用，功能上的建议可以直接告诉我们 https://github.com/alibaba/weex/pull/2516

**Comment by liuzhiyi1992** [comment]
目前没有returnkeytype，那么只能点击联想条中的完成进行结束输入？

**Comment by kfeagle** [comment]
@liuzhiyi1992 新版本即将支持 https://github.com/alibaba/weex/pull/2516

**Comment by cristaltina** [comment]
@kfeagle 
你好，在做ios11适配，发现.we文件中使用<input>控件就会报错  Main Thread Checker: UI API called on a background thread:
请问知道这个原因嘛？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
