### ISSUE TITLE
正在渲染组件时，无法响应Click事件。

### ISSUE THREAD

**Issue by supersoho** [alibaba/weex#2766]
使用Embed动态加载远程js文件或者为list动态添加多个cell的时候。正在渲染的过程中，页面上的其它控件无法响应Click事件，严重影响用户体验，请问该如何解决？

**Comment by acton393** [comment]
hi  @supersoho  麻烦提供一下 在哪个平台， SDK版本号， 最好提供一下可以验证问题的demo，方便我们排查  thx ~~

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
