### ISSUE TITLE
weex-toolkit@beta  支持vue文件，在自定义的module使用返回值变成undefined

### ISSUE THREAD

**Issue by kcaj008** [alibaba/weex#2767]
使用的weex-toolkit@beta  版本如下：
v1.0.1-beta.6
weex-builder : v0.2.2

BUG:
新增 的自定义module的方法，返回值String , 都变成了undefined   

把  XX.vue 文件  改写成 XX.we   就正常了。  初步确定是支持VUE不好。

**Comment by jack20000** [comment]
vue 中 是这样引用  weex.requireModule('XXModule');
we   中是这样引用  require('@weex-module/XXModule');
不知道是否跟引用方法有关。

**Comment by jack20000** [comment]
测试发现是@JSMethod(uiThread = false)失效，变成了异步，没有同步拿到值。

**Comment by acton393** [comment]
hi  @jack20000  在Android 的上问题么？

**Comment by jack20000** [comment]
是在android上出现的

**Comment by fkysly** [comment]
vue framework 暂时不支持这个特性，后续迭代版本会和 legacy framework 对齐这个特性。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
