### ISSUE TITLE
How to build android app ?

### ISSUE THREAD

**Issue by simon-tannai** [alibaba/weex#2773]
Hi everyone ! 

I would like to know: How I can build an Android app' with Weex ?
The documentation is currently in writting, but maybe it's already possible to build app for Android ?

**Comment by F-loat** [comment]
an example: [weex-hackernews](https://github.com/weexteam/weex-hackernews)

**Comment by simon-tannai** [comment]
Hey F-loat !
Thank you for your reply.

According to your example and if I understand right, I must:

- Add script: `"copy:android": "cp dist/app.weex.js android/app/src/main/assets/index.js"` inside package.json (I have not index.weex.js but app.weex.js)
- Create android folder inside my Weex project: `mkdir -p android/app/src/main/assets`
- Run `npm run build`
- Run `npm run copy:android`
- Open android folder into Android Studio

That is good ?

**Comment by shinriyo** [comment]
it is
```
yarn pack:android
```

but no sign

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
