### ISSUE TITLE
请教关于gcanvas的一些问题

### ISSUE THREAD

**Issue by huahmj** [alibaba/weex#2775]
1.因为工程是非标准的weexpack目录，所以直接将gcanvas的module和component放在工程中，然后build.gradle添加了1.2.3的依赖，发现绘制图片的时候总是会报空指针的错，升级了1.2.5之后，问题解决了。请问是之前是bug吗？

2.gwebgl.js中
![image](https://cloud.githubusercontent.com/assets/12036023/23305167/724edb84-fad8-11e6-8f44-88b5e1b6ac61.png)

这个util是不存在的吧，应该是gutil？这点请指教。

**Comment by AugHua** [comment]
@kfeagle 这个说明无法解答我的问题呀

**Comment by kfeagle** [comment]
@AugHua 需要通过插件集成，可以给我发邮件sunjjbobo@163.com 我们进一步讨论

**Comment by q757571446** [comment]
请问gcanvas每个界面只能放一个吗

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
