### ISSUE TITLE
关于ios中navigator跳转的生命周期

### ISSUE THREAD

**Issue by zjalen** [alibaba/weex#2776]
在使用跳转的时候有一些疑问，我在viewwillappear中注册了通知观察，在viewwilldisappear中移除观察，openurl方式没有问题，换成navigator之后收不到通知，调试发现viewwilldisappear之后viewdiddisappear，居然没有执行appear和load方法。想请教navigator跳转的生命周期，我该如何放置通知观察者。

**Comment by myyeshang** [comment]
说明一下，我用了tabbar，在tabbar的子页面里openurl不能用手势返回，所以选择用navigator。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
