### ISSUE TITLE
请问,WeexSDK中的main.js的源代码在哪

### ISSUE THREAD

**Issue by xoxhk** [alibaba/weex#2779]
请问,WeexSDK中的main.js的源代码在哪

**Comment by zk0301** [comment]
assets有啊，一堆乱乱的，你找它干嘛。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
