### ISSUE TITLE
input 等元素 没有结束标签 会显示不出来

### ISSUE THREAD

**Issue by CREATE-AI** [alibaba/weex#2781]
错误写法:
`<input type="text">`
正确写法：
`<input type="text"/>`

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
