### ISSUE TITLE
请问IDrawableLoader是用来加载本地图片的吗，该如何使用？

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2787]
我实现了这个接口，复写了一个类，通过init设置进去了，但是不知道在weex文件中该如何使用他

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
