### ISSUE TITLE
自定义module获取到UIImage对象，如何使用在<Img>上？

### ISSUE THREAD

**Issue by liuzhiyi1992** [alibaba/weex#2802]
获取到的UIImage对象以回调Block方式回传，请问而后如何将图片应用到Img标签上？

**Comment by liuzhiyi1992** [comment]
WXImgLoaderDefaultImpl回调也是传UIImage对象，应该没有任何差别才对

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
