### ISSUE TITLE
Android中weex怎么通知native去关闭页面？

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2804]
看这篇文章（https://weex-project.io/cn/references/path.html） 中提到了可以加载res资源，但是我试的有问题，不知道是不是我自己写的有问题，请问是按下面这样加载吗？

`<img class = "back_btn_style" src="local://back_black_arrow"></img>`

我的sdk版本是0.9.5

**Comment by hanliuxin5** [comment]
到底是哪个问题？
加载本地drawable的话，需要在你自己实现的
```
public class ImageAdapter implements IWXImgLoaderAdapter {
  public ImageAdapter() {
  }
  @Override
  public void setImage(final String url, final ImageView view,
                       WXImageQuality quality, WXImageStrategy strategy) {}}
```
这样你取得的url就是你写的
`src="local://back_black_arrow"`
最后在自己读取指定位置的资源文件

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
