### ISSUE TITLE
weex v0.10 list控件用 loading子控件不会显示和触发loading的事件

### ISSUE THREAD

**Issue by simonwu-os** [alibaba/weex#2810]
在weex v0.10中，list控件使用 @loadmore可以触发loading. 但无法显示 loading.
如果把 list控件的 @loadmore去掉， loading控件不会调用@loading的方法。scroller可以。
是不是后面list控件不包含loading? 我看源代码里面是有包含的loading.
这是目前的bug？还是我的用法有错误。loading控件里面的例子也是scroller控件。
h5的版本不能运行。
`<list class=“discount-list”  @loadmore=“onloading”  loadmoreoffset=“30” >
<cell> … </cell>
<loading class=“loading” @loading=“onloading” :display=“showLoading”>
</list>`

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
