### ISSUE TITLE
weex vue2.0beta input组件、display属性问题

### ISSUE THREAD

**Issue by kobsucTam** [alibaba/weex#2811]
问题1：官方文档明确说‘Flexbox 是默认且唯一的布局模型’、‘Weex 不支持 display: none;，因此也不支持 v-show 指令’，但是在官方提供的modal模块demo中，alert提示框，.weex-modal-wrap {display:none}，弹窗出现时加了display:block，如果这样的话是不是说明weex又支持v-show指令了，display是不是可以为none和block了，还是文档更新有问题？
   问题2：input组件，因为weex不支持click事件，如果不加autofocus=‘true’，在web中将无法获取焦点；同一个页面中如果有多个input组件，只能有一个input获取焦点，其它input无法获取焦点，

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
