### ISSUE TITLE
模态推出页面

### ISSUE THREAD

**Issue by wzj583585700** [alibaba/weex#2815]
weex怎么像iOS一样，从下面推出一个页面，就模态推出页面，而不是push，weex可以实现吗

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
