### ISSUE TITLE
weex中webview的src相对地址 安卓不对

### ISSUE THREAD

**Issue by zhe-he** [alibaba/weex#2817]
用weex编写的 webview插件中，src的地址是一个相对地址 './xxx.html',
放在ios的APP中没有问题，
放在安卓的APP中，程序会在这个地址前加上`/` 变成了 '/./xxx.html'. （只有写http地址和`/`开头的地址程序才不会加。 ）

**Comment by zhe-he** [comment]
仓库地址： https://github.com/zhe-he/weex-demo
把 dist 文件夹的所有文件 放入App 即可运行， 入口文件 dist/app.weex.js.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
