### ISSUE TITLE
富文本什么时候发布

### ISSUE THREAD

**Issue by karynsong** [alibaba/weex#2818]
上次说 0.10 上线富文本，已经等了这么久了，什么时候能才上呀。

iOS list 的首次渲染性能稍差，这个会想要优化么

**Comment by jinyue-rdj** [comment]
现在线上的0.10版本已经支持富文本了，可以试一下

**Comment by karynsong** [comment]
@jinyue-rdj 怎么使用的呢？求教

**Comment by xubodreamsky** [comment]
如何使用富文本？

**Comment by Somnusochi** [comment]
同问，有demo么？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
