### ISSUE TITLE
[ios] scroll横屏滚动 子元素宽度异常 iphone5 ios8.4

### ISSUE THREAD

**Issue by lansee** [alibaba/weex#2823]
ios8.4，子元素非固定宽度
![image](https://cloud.githubusercontent.com/assets/7961271/23445443/56e8f5fe-fe76-11e6-8206-755e9daf0b59.png)

ios10  正常图
![image](https://cloud.githubusercontent.com/assets/7961271/23445428/33c8c504-fe76-11e6-8048-b2aacc225038.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
