### ISSUE TITLE
weex可以实现像popupwindow样式的弹窗吗

### ISSUE THREAD

**Issue by huoyabingqian** [alibaba/weex#2824]
我们现在正在做一个weex项目，在项目当中有一个功能是做成像android 当中popupwindow像式的从底部向上弹窗的功能，不知道weex能不能实现，最近找了找，没有发方法和实现的功能

**Comment by JackPu** [comment]
@huoyabingqian  参考插件[weex-action-sheet](https://github.com/weex-plugins/weex-action-sheet),类似底部弹出的效果。

Demo: https://weex-plugins.github.io/weex-plugin-actionSheet/

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
