### ISSUE TITLE
集成weex_sdk后，渲染容器的位置怎么设置？大小可以通过setSize

### ISSUE THREAD

**Issue by tonyyls** [alibaba/weex#2825]
请教各位，集成weex_sdk后，渲染容器的位置怎么设置？大小可以通过setSize。
尝试自定义RenderContainer，设置 RelativeLayout.LayoutParams，代码如下：

        RenderContainer container=new RenderContainer(this);
        RelativeLayout.LayoutParams layoutParams=new RelativeLayout.LayoutParams(300,300);
        layoutParams.addRule(RelativeLayout.BELOW,R.id.layoutHeader);
        container.setLayoutParams(layoutParams);
        container.setBackgroundColor(Color.BLUE);
        mWXSDKInstance.setRenderContainer(container);

目标是想放在某个控件的下面，如上设置无效。求解！

**Comment by tonyyls** [comment]
绕一点的做法是，将渲染容器包裹在Fragment里面，之后Activity里面就可以随意放置位置了。 估计官方也是推荐这么做吧。
<fragment
        android:id="@+id/frag1"
        android:name="bingosoft.linkweex_android.BingoWeexFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/layoutHeader">
</fragment>

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
