### ISSUE TITLE
webview组件能不能自动横屏呢

### ISSUE THREAD

**Issue by solaronke** [alibaba/weex#2829]
webview 不是调用的自身的浏览器吗，自身的浏览器可以自动横屏的，怎么在app里嵌入的不行呢，已经把手机的竖排方向锁关闭了也还是不行，望解答哦。

**Comment by zk0301** [comment]
webview 不是调用的自身的浏览器，跳到第三方打开的写法才是。

**Comment by solaronke** [comment]
@zk0301 就是想在app里打开的，可行不？是iOS的

**Comment by zk0301** [comment]
没看过ios sdk的源码，不知道跳转处理页面是不是wxpageActivity之类的。 
还有其他的方法，js调用一个自定义的module，然后module再打开一个VC，这个VC是横屏的，里面有个webview空间。

**Comment by likenow** [comment]
横竖屏自己处理，和webview 没关系。
实现一下这几个方法：
- (BOOL)shouldAutorotate;
- (UIInterfaceOrientationMask)supportedInterfaceOrientations;
- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation;

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
