### ISSUE TITLE
weex设计怎么引用第三方插件呢，import都报语法错误 

### ISSUE THREAD

**Issue by alex1226** [alibaba/weex#2831]
怎么用第三方插件呢？ 下面参考代码weex 编译都报语法错误 ！！ （weex已经升级到最新1.0.3版本了 ）
<script>
    import 'Nat' from 'weex-nat';
    module.exports = {
        data: {
            total: '9527',
       },
。。。。。。

运行命令 weex **.we  报错：
BabelLoaderError: SyntaxError: E:/weextest/ucoindetail/src/ucoindetail-head.we: Unexpected token, ex
pected ; (1:13)

参考网址：http://market.dotwe.org/ext/list.htm#29

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
