### ISSUE TITLE
iOS  navigator.push方法 ，新界面为空白，sdk中加断点也不执行

### ISSUE THREAD

**Issue by limeidong** [alibaba/weex#2834]
js 文件中 使用 navigator.push方法 跳转到一个新的界面 加载URL，但是跳转过去后的界面是空白的；我在weex 的 sdk 中的 WXNavigatorModule 中- (void)push:(NSDictionary *)param callback:(WXModuleCallback)callback方法 加了断点；调试的时候  并没有进入方法，这是什么原因？

**Comment by zk0301** [comment]
push都不走？没道理啊。难道他是调用了openUrl或其他？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
