### ISSUE TITLE
安卓样式切换报数字格式的异常

### ISSUE THREAD

**Issue by karynsong** [alibaba/weex#2840]
当样式发生改变时，一下属性会抛数字格式异常，borderRaduis、left、top、left、right、bottom、flex

我们在做很多 active 状态的时候都会使用  :class[true ? 'active' : '' ]，当 active 中含有上面这些属性时就会抛数字格式异常

setTimeout 不传时间时安卓也会抛异常

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
