### ISSUE TITLE
0.10.0版本的weex-vue-render viewport错误

### ISSUE THREAD

**Issue by fromIRIS** [alibaba/weex#2841]
![image](https://cloud.githubusercontent.com/assets/8492963/23496624/201557cc-ff5a-11e6-94b1-cf6a0607ada7.png)

0.10.0版本支持设置viewport，请问要在哪里设置？

另外使用`0.10.0`版本的`weex-vue-render`，页面初始化后viewport设置失败，导致页面宽度不正常，如下图：

![image](https://cloud.githubusercontent.com/assets/8492963/23496634/297719c2-ff5a-11e6-9abd-a79bd57506b9.png)

是需要手动设置viewport吗，另外，这一块的文档在哪里？？好像找不到..

`0.2.0的weex-vue-render`是正常的。

**Comment by dongnaebi** [comment]
0.10.0问题很多啊

1. 扩展组件和模块后打包的文件在报错
2. slide组件报错
3. image组件resize属性不管用
4. scroll组件滚动很卡
5. 用到window和deviceWidth的地方都报错

以上问题都是升级之后出现的问题，0.2.0下是好的

**Comment by ShowJoy-com** [comment]
你这些问题我都遇到了...@dongnaebi

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
