### ISSUE TITLE
weex-vue-render的a标签不支持flex布局

### ISSUE THREAD

**Issue by fromIRIS** [alibaba/weex#2844]
![image](https://cloud.githubusercontent.com/assets/8492963/23499222/3709a1ac-ff66-11e6-8e46-28a53893be3b.png)
0.2.0 版本的weex-vue-render默认对a标签应用了如上图所示的样式，不支持flex布局。

div标签的样式默认是支持flex的。
![image](https://cloud.githubusercontent.com/assets/8492963/23499288/8084f624-ff66-11e6-9659-009f05306993.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
