### ISSUE TITLE
slot支持 vue.js 2.1.0新增的作用域插槽吗？

### ISSUE THREAD

**Issue by 1903514970** [alibaba/weex#2845]

**Comment by 1903514970** [comment]
@mazhao 大佬知道这个怎么做吗？

**Comment by milan-hwj** [comment]
同问，如若不支持，是否有优雅的替代方案?

**Comment by yukiyang0729** [comment]
支持。
组件内传出testData
```
 <slot :data="testData"></slot>
```

父组件解构拿到data ，也就是testData

```
 <div slot-scope="{data}">
         <text>{{data.x}}</text>
 </div>
```
或者拿到全部数据
```
 <div slot-scope="{props}">
         <text>{{props.data.x}}</text>
 </div>
```

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
