### ISSUE TITLE
dom 可以直接调用updateAttributes这个方法吗

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#2846]
this.$refs.inputid.updateAttrs({'attr': 20})没有调到sdk的updateAttrs方法。

![image](https://cloud.githubusercontent.com/assets/6778148/23545219/599a33d8-0035-11e7-91ef-cb1ca4850cc5.png)
在vue 用dom这个模块调用不了这个API

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
