### ISSUE TITLE
子标签宽度自适应过大溢出父标签

### ISSUE THREAD

**Issue by liuzhiyi1992** [alibaba/weex#2848]
在一个宽度自适应的Text标签里，当内容超出parent，内容溢出，不会自动换行。

问题主要提现在sub标签宽度不受parent标签限制，不支持max-width属性。

请教目前如何应对这个case

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
