### ISSUE TITLE
iOS 【BUG】WXWebView dealloc的时候Crash

### ISSUE THREAD

**Issue by LouisLWang** [alibaba/weex#2849]
WXWebView在销毁的时候self.delegate是弱引用

- (void)dealloc
{
    if (self) {
        self.delegate = nil;
    }
}
不能将self.delegate 置空

**Comment by acton393** [comment]
hi @LouisLWang   麻烦贴一下相关 crash堆栈

**Comment by LouisLWang** [comment]
log:
2017-03-04 09:43:44.885186 WeexDemo[3286:1353727] WF: _WebFilterIsActive returning: NO
objc[3286]: Cannot form weak reference to instance (0x1014eebe0) of class WXWebView. It is possible that this object was over-released, or is in the process of deallocation.

![image](https://cloud.githubusercontent.com/assets/14959387/23574952/35696a48-00c0-11e7-882f-5b1e9a430ee8.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
