### ISSUE TITLE
装了toolkit,没有devtool

### ISSUE THREAD

**Issue by wxxcarl** [alibaba/weex#2853]
weex-toolkit已经安装了，不是说包括devtool的吗？当我运行 weex debug的时候，提示

`This command need to install weex-devtool. Install now? (Y/n) `

我确认安装，结果权限不对，我要用sudo装的，这种情况怎么解决？？另外我试着重新sudo npm install weex-devtool -g，运行weex-debug还是一样的提示，什么鬼？？！！！

**Comment by JackPu** [comment]
@wxxcarl  你能贴下你的错误信息，如果是权限问题你改下你当前用户目录的权限.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
