### ISSUE TITLE
背景线性渐变，在通过api改变元素宽度的情况下会丢失线性背景

### ISSUE THREAD

**Issue by CTOSPACE** [alibaba/weex#2854]
定义一个元素的线性渐变属性，然后通过api，如 $btn.setStyle('width', "100px")的情况下，该元素的线性背景色会丢失，并且通过api设置线性渐变也无效，如$btn.setStyle('backgroundImage', 'linear-gradient(to top,#a80077,#66ff00);') 无法设置元素的线性背景。

此处应该是个bug？还是有什么需要注意的地方？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
