### ISSUE TITLE
我想让webview横屏，一点方向都没有，求指点

### ISSUE THREAD

**Issue by solaronke** [alibaba/weex#2857]
项目里要用webview打开h5页面的游戏，需要横屏，可是我不知道怎么入手，几天了还是一点进展都没有，之前提的issue也没回复，求指点。

**Comment by CCC2016** [comment]
如果是通过 SDK集成的修改对应的 Activity，如果是weexpack那就。。。

**Comment by zk0301** [comment]
安卓的话，在WXPageActivity的onCreate判断传入bundleUrl是否包含“game”，在这里设置该页面横屏。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
