### ISSUE TITLE
weex-vue-render0.10.0 image标签v-if切换报错

### ISSUE THREAD

**Issue by fromIRIS** [alibaba/weex#2860]
目前http://dotwe.org/vue/eb8a8bb727811e55a7222f7c962a3532 示例是没有问题的，看了weex-vue-render应该不是0.10.0版本。

在0.10.0版本下通过`v-if`切换image标签会报错

![image](https://cloud.githubusercontent.com/assets/8492963/23600091/c827dc00-027f-11e7-843c-63d514160e4c.png)

通过源码发现是取有个字段报错，

![image](https://cloud.githubusercontent.com/assets/8492963/23600109/e20b719a-027f-11e7-9c57-891490f5267c.png)

暂时的解决办法是给image标签加上style属性，并设置width.height。 

望解决这个bug

**Comment by hphua** [comment]
我使用的是"weex-vue-render": "^0.1.8"

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
