### ISSUE TITLE
slider如何根据index滚动到指定的 frame，或者如何实现手势切换页面的效果，比如网易新闻那样。

### ISSUE THREAD

**Issue by CTOSPACE** [alibaba/weex#2861]
@slider组件如何根据index的值，滚动到指定的frame上面，实现如网易新闻那样可以同通过手势频道页面切换，并且可以点击频道名，滚动到slider指定的iframe上面。

**Comment by 501956430** [comment]
手动触发onchange事件

**Comment by suface** [comment]
如何初始化  直接切换到 到指定的index

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
