### ISSUE TITLE
navpage ios下出现navbar被屏幕上方ios原有信息挡住的问题。

### ISSUE THREAD

**Issue by CTOSPACE** [alibaba/weex#2865]
如图：
![aa](https://cloud.githubusercontent.com/assets/1892162/23605362/63bc592c-0297-11e7-91e2-91511a1419c0.png)

这样的问题应该怎么破。

**Comment by 501956430** [comment]
根据分辨率动态设置navpage高度，就可以解决了。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
