### ISSUE TITLE
weex-toolkit 升级以后 debug不能用

### ISSUE THREAD

**Issue by zfha** [alibaba/weex#2871]
今天，weex-toolkit 升级以后 debug不能用
```
wee-demo git:(develop) weex debug
? This command need to install weex-devtool. Install now? Y
es
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "weex-devtool" "--loglevel=error"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /Users/zhoufan/.xtoolkit/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/zhoufan/.xtoolkit/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/Users/zhoufan/.xtoolkit/node_modules'
npm ERR!     at Error (native)
```

**Comment by JackPu** [comment]
@zfha  权限问题，你执行下这个命令后
``` bash
chomd -R 777 /Users/zhoufan/.xtoolkit
```
重新输入weex debug吧

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
