### ISSUE TITLE
键盘会遮挡住 与键盘弹出高度差不多位置的input控件

### ISSUE THREAD

**Issue by hayvane** [alibaba/weex#2873]
iOS 使用的vue，sdk :0.10.1
场景如下，
list 中有多个cell，每个cell中都有一个input控件，如果一个input 的位置 在键盘弹出高度差不多的位置，list不会向上偏移，导致键盘会遮挡住该input控件二分之一或三分一。
其它cell中的input（比如偏下一点的input 在foucs，list 会向上移动），键盘不会遮挡住，

**Comment by acton393** [comment]
@hayvane  这个应该已经解决掉了，如果未解决，麻烦提供一下case

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
