### ISSUE TITLE
WXSDKInstance 中 onActivityResult 的resultCode 传错了

### ISSUE THREAD

**Issue by 1903514970** [alibaba/weex#2880]
![image](https://cloud.githubusercontent.com/assets/15099256/23699244/60974214-0429-11e7-864d-ce32aad30573.png)

**Comment by zk0301** [comment]
看了一下0.10.x的源码，还真是这样

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
