### ISSUE TITLE
slider-neighbor 左侧滑动右侧出现空白

### ISSUE THREAD

**Issue by lyboy2012** [alibaba/weex#2883]
slider-neighbor 左侧滑动右侧最后子项个出现空白，向右滑动没有这个问题
![111](https://cloud.githubusercontent.com/assets/3926781/23731601/932dc858-04a9-11e7-8d43-180adfcb7f2e.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
