### ISSUE TITLE
请问一下在weex的vue文件中如何引入外部js

### ISSUE THREAD

**Issue by fyuu2016** [alibaba/weex#2886]
在weex的vue文件中如何引入外部js
如果用相对路径好像生成的JSBundle在移动端会找不到对应资料
远程的绝对路径如何加载

**Comment by 501956430** [comment]
var apis = require('./common/api');

**Comment by leenannan** [comment]
想问是怎么解决的引入了么

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
