### ISSUE TITLE
weex cell 中 input 未重新赋值问题

### ISSUE THREAD

**Issue by zfha** [alibaba/weex#2888]
使用情况：
使用了List， Cell机制，每个Cell中包含一个input, 每个Cell有一个CellItem的props。
现象描述:
Cell重用导致Input里面的value消失，并且未触发props的更新
```
watch: {
    cellItem(){ 
         //此处未调用
    }
}
```
猜想：
Cell重用机制应该没有问题，问题应该出现在Vue对Input的复用问题上。

**Comment by ErHu1993** [comment]
同样遇到这个问题, 在类似cell复用的过程中 界面上无法显示原来的值, 但实际数据中值是存在的

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
