### ISSUE TITLE
[html5] weex-vue-render 0.10.2 indicator组件错误

### ISSUE THREAD

**Issue by dongnaebi** [alibaba/weex#2890]
错误：`TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'`

打印了一下看，是因为传入的node没有children（length=0）

还有，样式reset(*{margin:0;padding:0})是故意干掉了么？

reset样式优先级比自己写的样式还高。。。

![image](https://cloud.githubusercontent.com/assets/6902417/23744616/e120ad8c-04ef-11e7-87e5-4d47cbf61ac4.png)

`.weex-text{white-space: pre}`导致text组件不会换行

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
