### ISSUE TITLE
不知道有没计划实现绘制相关的组件如 react-native-art

### ISSUE THREAD

**Issue by xiaozi4624** [alibaba/weex#2892]
不知道有没计划实现绘制相关的组件如 react-native-art？

**Comment by AugHua** [comment]
@xiaozi4624 不是gcanvas插件吗

**Comment by Boljing** [comment]
发错了不要再发了


boling@126.com
 
发件人： AugHua
发送时间： 2017-03-10 17:11
收件人： alibaba/weex
抄送： Subscribed
主题： Re: [alibaba/weex] 不知道有没计划实现绘制相关的组件如 react-native-art (#2892)
@xiaozi4624 不是gcanvas插件吗

**Comment by zfha** [comment]
@xiaozi4624 请查看weex-chart 插件

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
