### ISSUE TITLE
vue页面间通信

### ISSUE THREAD

**Issue by zhushangwei** [alibaba/weex#2893]
在安卓 weex0.10.0版本中使用 BroadcastChannel 会报BroadcastChannel is not defined错误，在网上找资料说是vue不支持BroadcastChannel  we文件可以支持，有什么好的解决方案让vue也支持没？

**Comment by karynsong** [comment]
iOS 0.10.0 也是一样的。什么时候能给解决一下

**Comment by jasonhe88** [comment]
同样问题， 我用的是Vue

**Comment by zk0301** [comment]
@Hanks10100

**Comment by BabyCY** [comment]
@Hanks10100 等着开饭呢

**Comment by duqian291902259** [comment]
android同一个activity中，用两个WXSDKInstance渲染两个weex view，采用BroadcastChannel实现两者之间的通信无效，android报BroadcastChannel is not defined。。。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
