### ISSUE TITLE
animation.transition 中第一个参数如果不符合预期类型，iOS app 会闪退

### ISSUE THREAD

**Issue by QingWei-Li** [alibaba/weex#2894]
线上地址：http://dotwe.org/vue/957f651655a6a02f7222c9e012994a40

代码：
```html
<template>
  <div></div>
</template>

<script>
  var animation = weex.requireModule('animation')
  
  export default {
    mounted() {
     // 传入一个不符合预期的参数
      animation.transition('xxx', () => {})
    }
  }
</script>
```

iOS SDK 0.10.0

**Comment by zk0301** [comment]
类似的，比如toast传个浮点数，安卓只会报错，不会闪退。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
