### ISSUE TITLE
执行 npm run build 报错

### ISSUE THREAD

**Issue by langxianfu** [alibaba/weex#2895]
![image](https://cloud.githubusercontent.com/assets/12893281/23752503/8778c118-0510-11e7-84b2-7306e525fa7c.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
