### ISSUE TITLE
嵌套  slider   ->  list  -> cell 

### ISSUE THREAD

**Issue by kcaj008** [alibaba/weex#2897]
slider 嵌套 list，list  嵌套 cell 后第一次进入页面，滑动list，出现重影；滑动slider后，再滑动list正常。

运行环境：HUAWEI CUN-TL00 android 5.1,API 22 出现的情况。

**Comment by jack20000** [comment]
vue 文件中会出现这个问题。
<slider class="slider" interval="3000" auto-play="false" @change="onchange">
      <div class="frame" v-for="img in imageList" >
        
          <list class="list">
            <cell v-for="(v,i) in rows"
                  :index="i"
                  class="row1"
                  @appear="onappear"
                  @disappear="ondisappear">
....

**Comment by wjizy** [comment]
+1

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
