### ISSUE TITLE
android 偶尔会包错，导致点击无效或卡顿 instance destroy JFM must stop callNative

### ISSUE THREAD

**Issue by chenyunecjtu** [alibaba/weex#2901]
E/jsengine: instance destroy JFM must stop callNative
E/jsengine: instance destroy JFM must stop callNative
E/jsengine: instance destroy JFM must stop callNative
E/jsengine: instance destroy JFM must stop callNative
E/jsengine: instance destroy JFM must stop callNative
E/jsengine: instance destroy JFM must stop callNative
E/jsengine: instance destroy JFM must stop callNative
E/jsengine: instance destroy JFM must stop callNative
E/jsengine: instance destroy JFM must stop callNative

这是什么原因导致的

**Comment by zk0301** [comment]
没遇到过

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
