### ISSUE TITLE
require(./xxx/xxx.we) 不同级别的目录出问题

### ISSUE THREAD

**Issue by MacSzh** [alibaba/weex#2902]
![1967d8d4-1501-479b-b0d6-8674836f6228](https://cloud.githubusercontent.com/assets/3241745/23787553/970e553c-05ad-11e7-9a09-71643fccdc29.png)

如果在同级目录是没有问题的
我把这个文件躲到 上面去  然后require  到list-demo 里面去 就出问题怎么回事
require('./common/wxc-item-loading-more.we')
求大神指教下
![a1be9a05-7ae4-4a81-a8a4-48999536e684](https://cloud.githubusercontent.com/assets/3241745/23787574/ac2e42ce-05ad-11e7-87b1-da83ef725e17.png)

**Comment by edwinbest** [comment]
我也是同样的问题,请教官方

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
