### ISSUE TITLE
v-if导致元素的层级关系不对

### ISSUE THREAD

**Issue by lili21** [alibaba/weex#2904]
> Weex 目前不支持 `z-index` 设置元素层级关系，但靠后的元素层级更高，因此，对于层级高的元素，可将其排列在后面。

```
<template>
  <div v-if="open" class="text-1"><text>1</text></div>
  <div class="text-2"><text>2</text></div>
</template>
<script>
    export default {
      data () {
        return { open: false }
      }
    }
</script>
<style scoped>
  .text-1 {
     position: fixed;
     top: 0;
     bottom: 0;
     right: 0
     left: 0;
     background-color: rgb(0, 255, 0)
   }
   .text-2 {
     position: fixed;
     top: 0;
     bottom: 0;
     right: 0
     left: 0;
     background-color: rgb(0, 255, 0)
   }
</style>
```

`v-if`指令导致text-1层级更高。

**Comment by fa-ge** [comment]
你试一下两个元素都设置v-if,效果更奇妙，偶尔第一个层级高，偶尔第二个层级高。我都快疯了。

**Comment by yoyou** [comment]
有解决这个问题的方案吗？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
