### ISSUE TITLE
vue 编写的子组件无法使用v-for进行列表渲染

### ISSUE THREAD

**Issue by pp1232** [alibaba/weex#2905]
使用vue编写的子组件在使用v-for进行列表渲染时候会出现页面一片空白的现象，并且没有报错信息出现。
同样的embed这个native标签也有同样的问题

**Comment by zk0301** [comment]
平台差异真气人啊

**Comment by XImoon** [comment]
用v-for渲染列表，同样的js不同的数据，会出现第一屏加载出来之后完全空白或者直接报错Cannot read property 'State' of undefined

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
