### ISSUE TITLE
发现一个数据 view同步更新的bug

### ISSUE THREAD

**Issue by CTOSPACE** [alibaba/weex#2913]
当使用navbar组件的时候，或者也许是其他组件的时候，如果当前页面上有数据与view同步更新操作时，比如 [http://dotwe.org/vue/eafe8d0001e94a065e31abd8dec80c87](http://dotwe.org/vue/eafe8d0001e94a065e31abd8dec80c87)
view更新就会出错，debug看xcode后台能看到错误提示： 
![image](https://cloud.githubusercontent.com/assets/1892162/23833288/3ffe3852-077e-11e7-8c62-6e5162edbe9e.png)

可以运行dotwe例子，有navbar的时候点击黑色区域无法更新显示的数字，删除掉navbar就可以了。

我想了下应该时数据更新的时候，框架在查找数据绑定的view时报错，可能是在查找组件生成的view时报错。当取出navbar组件的时候就没有问题，我试过自定义的其他组件，也会引起这个错误。

希望能够确定下问题，目前weex工程中基本上所有设计交互更新的页面都没有导入组件，导致很多重复的代码。

**Comment by 7nights** [comment]
例子里，你并没有在 `methods` 中定义 `categoryBtnClick` 方法啊？

**Comment by CTOSPACE** [comment]
啊，难道是因为这个？ 我试试看.

**Comment by xiaohuapunk** [comment]
@CTOSPACE Hi 我也遇到同样问题，具体什么原因还没找到，你找到具体是什么原因引起的吗？

**Comment by xiaohuapunk** [comment]
确定了，确实是因为vue里面方法没有实现导致的

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
