### ISSUE TITLE
在Android中使用weex的input控件放在页面底部会使页面全部顶上去

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2914]
当键盘弹出来的时候会让页面整体上移，包括title部分，有没有什么办法让title不上移？

weex使用的是0.10.0

**Comment by misakuo** [comment]
看起来像是weex页面所在的Activity被设置了`android:windowSoftInputMode="adjustPan"`属性

**Comment by 501956430** [comment]
用 wxc-navpage做原生header

**Comment by zk0301** [comment]
整体上移没什么不好的啊，那么挑剔。哈哈。

**Comment by warryy** [comment]
主要是上移后取消输入也不会下移回来

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
