### ISSUE TITLE
weex debug main.we 涉及多个文件依赖404

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#2920]
weex debug src -V -e src/main.we
有没遇到相同问题的？ 

![kp rts g 074ula yx3du](https://cloud.githubusercontent.com/assets/20204491/23884517/10491aca-08a8-11e7-9f2a-11d9b7da3ed6.jpg)

![zs8p 9d vy 2gn_ l v q](https://cloud.githubusercontent.com/assets/20204491/23884510/023c20d0-08a8-11e7-9b4b-2ab04fdf1ec0.png)

![3k_ovuxg 3m p 3gqybbeu](https://cloud.githubusercontent.com/assets/20204491/23884529/2214a116-08a8-11e7-8567-de09682e7dbb.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
