### ISSUE TITLE
H5版本的refresh功能，tips出现后无法隐藏

### ISSUE THREAD

**Issue by segatecm** [alibaba/weex#2921]
照着官方的Demo做的，无法隐藏。官方Demo也是不能隐藏。

**Comment by segatecm** [comment]
不能隐藏的原因是refresh 函数没有回调。没有回调的原因是_event里面没有注册refresh消息进去。但是不知道为什么没有注册进去。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
