### ISSUE TITLE
android stream cookie

### ISSUE THREAD

**Issue by zk0301** [alibaba/weex#2922]
同样的js，在安卓上测试发现登录后没有自动保存cookie；在苹果手机上测试发现没问题。是什么原因。streammodule难道要设置什么吗？

**Comment by zk0301** [comment]
查了一些资料，说ios的NSURLConnection可以自动存取cookie。 查了android的，貌似没有。

**Comment by dongnaebi** [comment]
希望安卓stream也实现自动存取cookie

**Comment by zk0301** [comment]
测试发现，ios的NSURLConnection虽然可以自动存取cookie，但是只是存在内存中，没有存文件。抹掉app后cookie就没有了。项目有需要的话还是要自己存取cookie。

**Comment by Z-Janp** [comment]
@zk0301 hi. 能分享一下解决方案吗？thx

**Comment by hygit54321** [comment]
博主，可以分享一些你的解决方案吗？真的被这个问题整得头疼

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
