### ISSUE TITLE
Weex中native主动发送事件到weex?

### ISSUE THREAD

**Issue by xiaoboJoin** [alibaba/weex#2925]

**Comment by likenow** [comment]
Native与weex通信问题 #1337
Weex中native主动发送事件到JS #866
参考这两个 issues

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
