### ISSUE TITLE
js有没有resume之类的方法

### ISSUE THREAD

**Issue by zk0301** [alibaba/weex#2926]
我的需求是   Aactivity渲染a.js , Bactivity渲染b.j，   从A跳到B，  然后BfinishActivity。 
A怎么刷新页面。

要求： Aactivity不能重新渲染a.js，因为这样A页面会白一下，不好看。

**Comment by zk0301** [comment]
在A页面onrestart的时候，fireGlobalEventCallback。

**Comment by coderminer** [comment]
@zk0301 遇到同样的需求，请问这个问题怎么解决的

**Comment by zk0301** [comment]
@coderminer 最后用js的broadcastchannel完成了。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
