### ISSUE TITLE
在iOS上，当scroller上的contentSize没有超出height时，scroller是不能滑动的。造成就算设置了下拉刷新也不能触发

### ISSUE THREAD

**Issue by xiaozi4624** [alibaba/weex#2929]
在iOS上，当scroller上的contentSize没有超出height时，scroller是不能滑动的。造成就算设置了下拉刷新也不能触发

**Comment by xispower** [comment]
上拉也是一样

**Comment by acton393** [comment]
这个暂时还没有支持

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
