### ISSUE TITLE
安卓版下拉刷新和上拉加载更多的时候偶尔一直显示加载中

### ISSUE THREAD

**Issue by ljz16** [alibaba/weex#2930]
安卓版下拉刷新和上拉加载更多的时候，在没加载完毕的时候滑动就会一直显示加载中无法消除。望修复该问题

**Comment by ljz16** [comment]
没人吗

**Comment by yangjianjun198** [comment]
我和你发现了同样的问题，我们是下拉时，如果未加载完就向上滑动list，list会卡住一直下拉刷新


发自我的 iPhone

**Comment by yangjianjun198** [comment]
我们也遇到同样的问题

发自我的 iPhone

**Comment by ljz16** [comment]
勾股在吗

**Comment by yuxingfafu** [comment]
+1,同样有这个问题，官网的demo也会的

**Comment by hongfeiliuxing** [comment]
@sospartan 下拉时，如果未加载完就向上滑动list，list会卡住一直下拉刷新；这个问题，什么时候版本可以修复？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
