### ISSUE TITLE
页面出错后，导致所有页面不能渲染正常

### ISSUE THREAD

**Issue by zfha** [alibaba/weex#2934]
案例：
使用Vue，页面嵌套逻辑： A 页面， 使用了 B，C component，如果C JS出错，A, B能正常渲染出来，onFailed onException均未调用。。。
结果很严重：会导致app中所有的weex页面不能渲染。 （Android，iOS均会出现这个问题）

调试：
当A页面出现如上问题后，退出A页面，发现调用callJS，destroyInstance 出现错误，具体错误如下：
```
TypeError: undefined is not an object (evaluating 'e.child._isDestroyed')
Z@main.js:3:8926
m@main.js:3:25355
m@main.js:3:25455
m@main.js:3:25455
main.js:3:27816
$destroy@main.js:3:17432
$t@main.js:3:31872
main.js:1:7895
main.js:7:1153
```

怀疑：
页面destroyed出错导致之后instance渲染全部出问题。。

请问各位大神怎么解决？
急急急！

**Comment by fkysly** [comment]
请贴个可以复现的 demo 吧。

**Comment by supersoho** [comment]
遇到同样的问题，比如在js中访问一个不存在的dom对象，debug窗口中会打印js错误信息，之后app中所有的weex页面不能渲染(即便是创建一个新的instance也一样)，貌似是js call native的相关bridge事件队列中断执行了。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
