### ISSUE TITLE
weex动画库支持

### ISSUE THREAD

**Issue by wangying3426** [alibaba/weex#2936]
weex现在有没有一些支持的比较好的纯js动画库？或者简单移植过来就能用的？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
