### ISSUE TITLE
android singletask无效

### ISSUE THREAD

**Issue by zk0301** [alibaba/weex#2937]
渲染的是settings.js，点击按钮，调用了自定义module的logout()。logout代码如下：
mWXSDKInstance.getContext().startActivity(new Intent(mWXSDKInstance.getContext(), LoginActivity.class));

其中LoginActivity是singletask。

问题：singletask没有起作用。虽然跳到Login，但之前的页面并没有出栈。

**Comment by zk0301** [comment]
是我搞错了。singletask是可以的。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
