### ISSUE TITLE
https://weex-project.io/cn/references/ios-apis.html

### ISSUE THREAD

**Issue by LanCat** [alibaba/weex#2938]
https://weex-project.io/cn/references/ios-apis.html 打不开啊

**Comment by QingWei-Li** [comment]
http://weex.apache.org/cn/references/ios-apis.html

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
