### ISSUE TITLE
iOS listView 卡顿问题

### ISSUE THREAD

**Issue by likenow** [alibaba/weex#2941]
List 最佳实践 -- 饮源
2）尽可能细粒度的拆分cell
3）尽可能减少首次加载内容，多用懒加载
4）尽可能复用List 组件（多tab 切换场景）
5）尽可能使用 a 链接跳转，而不是通过响应click
第二条，细粒度的拆分cell
代码
  ```
<list>
    <cell>
      <text class="p-index-notice">公告通知</text>
    </cell>

    <cell>
      <ptop></ptop>
    </cell>

    <cell>
      <prank></prank>
    </cell>
  </list>
```
下拉滚动会出现卡顿，反而
```
<list>
    <cell>
      <text class="p-index-notice">公告通知</text>
      <ptop></ptop>
      <prank></prank>
    </cell>
  </list>
```
下拉滚动不会卡顿
是我理解错了吗？

**Comment by likenow** [comment]
希望有同学回复下

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
