### ISSUE TITLE
点击事件无法触发

### ISSUE THREAD

**Issue by ghost** [alibaba/weex#2942]
```
<template>
  <div>
     <text @click="click" style="font-size:50px">{{msg}}</text>
  </div>
</template>


<script>
export default {
    data:function() { return {
       msg:'click'
    }},
    methods:{
       click:function(){
             this.msg = "clicked"
    }
  }
}
</script>
```
在游览器中有效，在playgroundApp中点击后经常没有反应？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
