### ISSUE TITLE
app_name修改无效

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#2944]
修改后，桌面应用名称显示还是"WEEX" ，而查看应用管理器的应用信息，显示的是修改后的名称。

![image](https://cloud.githubusercontent.com/assets/20204491/24230784/d005ba98-0fbb-11e7-925b-6d5eede60601.png)
  
![image](https://cloud.githubusercontent.com/assets/20204491/24230724/76595234-0fbb-11e7-8194-e7a20c46fc5e.png)
![image](https://cloud.githubusercontent.com/assets/20204491/24230748/980dd8b4-0fbb-11e7-9bc0-3e21c5294d8c.png)
![image](https://cloud.githubusercontent.com/assets/20204491/24230755/9fba88c8-0fbb-11e7-810a-2e8554d8bd98.png)

**Comment by 501956430** [comment]
应用是通过：weex run/build android 打包运行的

**Comment by linyuang** [comment]
要在app/src/main/res/values-zh-rCN/strings.xml里修改

**Comment by Flying-Snail** [comment]
补充一下是在platform/***/app/src/main/res/values-zh-rCN/strings.xml

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
