### ISSUE TITLE
Android 混淆weex 怎么配置？

### ISSUE THREAD

**Issue by wincentytg** [alibaba/weex#2951]

**Comment by wincentytg** [comment]
Android 混淆weex 怎么配置？

**Comment by hanliuxin5** [comment]
# Weex
-keep class com.taobao.weex.** {*;}
-keep public class * extends com.taobao.weex.common.WXModule{*;}
-keep public class * extends com.taobao.weex.ui.component.WXComponent{*;}

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
