### ISSUE TITLE
页面 viewappear 触发的时机

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#2952]
平台： iOS (Android 还未试过）

根据文档， 页面的 viewappear 的触发时机应该是 " ViewWillAppear":

"viewappear 事件会在页面就要显示或配置的任何页面动画被执行前触发......"

但是实际是在 "ViewDidAppear" 时触发

**Comment by jasonhe88** [comment]
~/Controller/WXBaseViewController.m

``object-c
- (void)viewWillDisappear:(BOOL)animated
{
    [_instance fireGlobalEvent:WX_APPLICATION_WILL_RESIGN_ACTIVE params:nil];
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    [_instance fireGlobalEvent:WX_APPLICATION_DID_BECOME_ACTIVE params:nil];
    [self _updateInstanceState:WeexInstanceAppear];
}
``

**Comment by acton393** [comment]
@jasonhe88    viewWillAppear 事件跟Instance 相关， 也就是跟当前页面相关，

你这个地方贴的不是 viewAppear 事件， 是支持前后台事件的一个通知，

**Comment by ZombieTerminator** [comment]
的确是在渲染之后触发的

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
