### ISSUE TITLE
<wxc-navpage>组件怎样改变title字体大小和粗细？

### ISSUE THREAD

**Issue by ghost** [alibaba/weex#2953]
<wxc-navpage>组件怎样改变title字体大小和粗细？只能是默认的大小和粗细吗？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
