### ISSUE TITLE
ios打包证书设置：Profile  CodeSign

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#2954]
![default](https://cloud.githubusercontent.com/assets/20204491/24338516/92b6692e-12d8-11e7-9421-e613745238a9.png)

如何设置Profile  CodeSign: 
是在xcode中配置还是只需要在ios.config.json配置好签名和指定秘钥所在文件？

**Comment by Anchorite-e** [comment]
摸索了好久，对于一个前端配置这些真难！
1、首先你得有证书（别问什么是证书，找ios开发要一个）我要到的是一个文件"CodeSign.p12"，双击安装。然后去mac的"钥匙串访问"，找到"我的证书" ->右键 "显示简介"，复制"常用名称"，这就得到了CodeSign
2、下载文件"mobileprovision_UUID.sh"（别问我怎么下），再找ios开发要到文件"*.mobileprovision"(这就是个文件），最好两个文件放在一起，命令行：./mobileprovision_UUID.sh *.mobileprovision，就得到了Profile
weex run ios 没问题
weex build ios 还有问题，只能说“大爷的！”

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
