### ISSUE TITLE
text 宽度不定换行问题

### ISSUE THREAD

**Issue by yanxlg** [alibaba/weex#2955]
text自动换行需要指定text的宽度，在flex布局模式下通常宽度是不定的，weex并没有进行处理，希望提供解决方案

**Comment by 452MJ** [comment]
指定一个max-width即可

**Comment by Juice007** [comment]
可以使用`flex:1`让text宽度撑满剩下的位置，text即可自动换行

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
