### ISSUE TITLE
Tabbar 点击时，怎么重新加载页面或者怎么更新数据

### ISSUE THREAD

**Issue by coderminer** [alibaba/weex#2956]
Tabbar 每一个页面的内容只会加载一次，之后点击如何重新加载或者更新数据

**Comment by coderminer** [comment]
Tabbar 每一个页面的内容只会加载一次，之后点击如何重新加载或者更新数据

**Comment by hanliuxin5** [comment]
可以自定义一个标签，然后加上一个自定义事件

**Comment by xutingqun** [comment]
请问实现了吗

**Comment by hanliuxin5** [comment]
@xutingqun 可以用广播机制，点击tabar发出制定广播，然后在其子vue实例里做你的业务处理

**Comment by faimin** [comment]
@hanliuxin5 你可以参考下@JNTian 的这篇 [博文](http://jerrytian.com/2016/01/07/%E7%94%A8Reveal%E5%88%86%E6%9E%90%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E7%9A%84%E5%AF%BC%E8%88%AA%E6%8E%A7%E5%88%B6%E5%99%A8%E5%88%87%E6%8D%A2%E6%95%88%E6%9E%9C/)，里面说的思路与这个框架是一致的。

**Comment by xutingqun** [comment]
@hanliuxin5  有没有例子呀，新手菜鸟一枚，有点懵

**Comment by hanliuxin5** [comment]
@xutingqun  https://weex.apache.org/cn/references/modules/globalevent.html

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
