### ISSUE TITLE
Vue 2.0 对text 标签 transform时候未做trim处理 

### ISSUE THREAD

**Issue by acton393** [alibaba/weex#2958]
Vue 2.0 对text 标签 transform时候未做trim处理, 1.0 trim过

这样会导致文本未居中，如下case

case： http://dotwe.org/vue/ef555b8e05cc83177ad496bf063f8f6e

**Comment by xiaolongyuan** [comment]
题主这个case 不只是未居中这么严重啊 

```
            <text @click="update">
              
              
              
              发送消息
              
              
              </text>

```



```
    <text @click="update">发送消息</text>
```

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
