### ISSUE TITLE
@click.native Android上触发两次bug

### ISSUE THREAD

**Issue by yanxlg** [alibaba/weex#2959]
在Android端使用@click.native 会触发两次，在Web上只触发一次，IOS中未验证

**Comment by StanNing** [comment]
我也碰到了同样的问题，奇怪的是运行仓库里面的demo示例是没有问题的。

**Comment by Nick742037091** [comment]
你们的问题解决了吗

**Comment by motcwang** [comment]
提供一下代码

**Comment by 15136356361** [comment]
改为@touchend.native   可当作点击事件使用  并且只会触发一次

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
