### ISSUE TITLE
list数据多的时候滚动直接crash

### ISSUE THREAD

**Issue by yanxlg** [alibaba/weex#2960]
list在数据多的时候（35条），滚动直接crash

**Comment by zk0301** [comment]
不应该啊，我的测试数据上百条，都不会闪退。看看日志，看是哪里崩了。

**Comment by acton393** [comment]
麻烦提供一下crash 的日志

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
