### ISSUE TITLE
在iOS上tableView Component 滑动异常的问题

### ISSUE THREAD

**Issue by JohnWilley** [alibaba/weex#2961]
用tableView作为Component时滑动时会超出边界范围 滑动时会在js设置的范围外继续滑动一段距离 
请问这个应该如何解决？

**Comment by 501956430** [comment]
有效果截图没

**Comment by zk0301** [comment]
同求，我也遇到这个问题。同组的安卓没有这个问题。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
