### ISSUE TITLE
Apache 基金会貌似不能提issue，输入标签貌似有bug

### ISSUE THREAD

**Issue by shenfu1991** [alibaba/weex#2966]
Apache 基金会貌似不能提issue，iOS端输入标签貌似有bug，如<input><textarea>，第一次可以输入文本，输入完成之后想编辑，发现不能编辑了？？？像是卡住了一样。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
