### ISSUE TITLE
slider 标签应该增加一个属性参数true\false，设置false当滚动到最后一张图不可切回到第一张

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#2968]
如题

**Comment by misakuo** [comment]
The `infinite` property has been added to v0.12

**Comment by 501956430** [comment]
@misakuo  0.12什么时候发布呀？

**Comment by misakuo** [comment]
Is expected in early May

**Comment by fengmingye** [comment]
我也有同样的问题，设置scrollable为false。然后在滑动一下，则setIndex无效，无法再切换到任何一张图片。
这个是原生slide的bug，我改底层控件的代码解决的

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
