### ISSUE TITLE
【Class Bug】动态绑定时针对特定元素无法重置元素属性

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#2970]
特定元素下无法初始还原，详情参考DEMO效果。

slider 切换时根据下标动态标识其他元素的颜色。
demo : http://dotwe.org/weex/2d986766e2d48f88a8de7c7789759886

注意使用：h5 和Weex Playgroound预览效果。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
