### ISSUE TITLE
使用VUE时，安卓的text组件不支持v-bind:class=""

### ISSUE THREAD

**Issue by xiaxingzzz** [alibaba/weex#2972]
在使用类似
v-for
的时候，需要用它来设置特殊样式

**Comment by hanliuxin5** [comment]
你试试 v-bind:style="" ?

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
