### ISSUE TITLE
文字多了，点击全文展开收起效果

### ISSUE THREAD

**Issue by lehahagirl** [alibaba/weex#2973]
我效果是弄出来了，但是我单击一个展开，所有有展开效果的都展开了，我怎么样区分他们呢，我用的方法是单击一下，某个属性变为true或者false，

**Comment by zk0301** [comment]
上代码。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
