### ISSUE TITLE
input或者textarea在安卓端获得焦点时会被软键盘遮挡，因为软键盘是根据光标的位置定位的

### ISSUE THREAD

**Issue by lehahagirl** [alibaba/weex#2974]
input或者textarea在安卓端获得焦点时会被软键盘遮挡，因为软键盘是根据光标的位置定位的，所以总会遮挡一点。怎么解决呢

**Comment by zk0301** [comment]
看WXEditText源码，应该是setBackground为null了。加个背景图片试试。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
