### ISSUE TITLE
Range slider component

### ISSUE THREAD

**Issue by kewats** [alibaba/weex#2975]
Hi everyone,

I am looking for a range slider component, on the lines of ["vue-slider-component"](https://github.com/NightCatSama/vue-slider-component) or a multiselect version of input type = range. I have not been able to find anything yet. Any pointers on this, given the conventional input type = range is [not supported by weex](https://weex.apache.org/references/web-standards.html).

Thanks!

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
