### ISSUE TITLE
More element width position sticky 

### ISSUE THREAD

**Issue by yanxlg** [alibaba/weex#2976]
when more than one sticky elements on the page,the following sometimes not cover the above while scrolling

当界面中存在多个sticky元素时，滚动的时候有时候下面的不会覆盖上面的，有时候可以，希望优化sticky机制，永远固定处于最下面的元素，当有新的sticky元素需要固定时，原来的自动取消固定

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
