### ISSUE TITLE
Activity 状态栏上面有的返回和刷新按钮，怎么1去掉？？？？

### ISSUE THREAD

**Issue by wu143211** [alibaba/weex#2977]
![0410164345](https://cloud.githubusercontent.com/assets/27199046/24853226/efc537e6-1e0c-11e7-8a11-72b19ab129c4.jpeg)

**Comment by hanliuxin5** [comment]
您这个是playground吧，具体到开发应用上需要单独集成weex

**Comment by wu143211** [comment]
是的，那怎么样单独集成weex？？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
