### ISSUE TITLE
we 动态变量问题

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#2978]
DEMO 地址：http://dotwe.org/weex/848ea999acfabfab8fe2dbb256456ce7

![default](https://cloud.githubusercontent.com/assets/20204491/24795945/bc07c154-1bbd-11e7-8543-5d0052114192.png)

**Comment by acton393** [comment]
hi  没看明白， 可以具体描述下问题么？  你这是个问题， 还是提的bug

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
