### ISSUE TITLE
ios 通知跳转的问题

### ISSUE THREAD

**Issue by zhj1002** [alibaba/weex#2979]
ios 里接收到通知之后 ，用户点击通知之后 我能获取到js的路径， 这个是应该跳转的页面路径，但是 我如何从 ios里直接去调到这个 weex页面里呢？

**Comment by acton393** [comment]
@zhj1002  点击通知后，在native中里面render 这个js页面

**Comment by zhj1002** [comment]
@acton393 我现在 在本地 渲染weex页面 我需要 像原生ios 那样 左划 返回 这需要 出现 返回特效 这个能实现么

**Comment by TheHeavenQI** [comment]
进去app后，拿到file路径，用rootViewController去push一个加载该js路径的控制器咯。。。

**Comment by ZhangHJ1002** [comment]
好的 我去试试  谢了啦

**Comment by TheHeavenQI** [comment]
@zhj1002 左滑返回的话，如果不是自定义动画，左滑返回是可以实现的，第一种添加自定义返回手势，第二种打开系统的默认返回手势。。
打开系统返回手势方法：在控制器里面添加：
self.navigationController.interactivePopGestureRecognizer.delegate = self;

**Comment by zhj1002** [comment]
写了好久 就是没有写出来系统原生的返回样式 这次总算妥妥的了  太谢谢了 @TheHeavenQI @acton393

**Comment by TheHeavenQI** [comment]
@zhj1002 大胸弟，你这还算好的了，我前天接到新需求，要求我写6种不同push，pop跳转动画。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
