### ISSUE TITLE
weex-vue开发   页面尺寸问题

### ISSUE THREAD

**Issue by zzc-suancai** [alibaba/weex#2981]
vue里  push页面后   页面的尺寸全屏，跟电池条重合（安卓无问题）   ，   Ios客户端 只能修改主页尺寸，
这个怎么解决了？

**Comment by wilfordw** [comment]
@zzc-suancai 是如何用vue搭起IOS环境的? 我是按照官方教程[Weex iOS SDK 集成指南](https://open.taobao.com/doc2/detail?spm=a219a.7629140.0.0.tFddsV&&docType=1&articleId=104829)，参考[weex-IOS](http://www.jianshu.com/p/2ea29d381c60)集成，最终运行无法显示界面
报
```
anonymous

init
createInstance
[;
2017-04-13 17:44:35.988463 weex-ios-demo[7515:2948924][fg255,0,0;
<Weex>[error]WXSDKError.m:34, [undefined:88:9] ReferenceError: Can't find variable: Vue
```
我是直接` pod install`的

开发环境都是近两天配置的最近版本
```
➜ weex -v
   v1.0.5
 - weex-builder : v0.2.6
 - weex-previewer : v1.3.7

```

最后我想吐槽一下Weex的文档，真的是太反人类了。文档完全跟不上版本，到处都是坑。而且完整性也太差了，光靠文完全无法搭出一个可跑的环境

**Comment by FourOnes** [comment]
@wilfordw then after how to resolved？can you share experience？

**Comment by wilfordw** [comment]
@FourOnes   我是pod版本太低了  所以更新的weex插件也更不上版本  不支持vue  需要把pod版本更新到最新

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
