### ISSUE TITLE
weex页面在移动端显示字体小一倍，web端显示正常 ，是哪里设置不对吗？

### ISSUE THREAD

**Issue by donbe** [alibaba/weex#2982]
如题，求大神抬一手~

**Comment by donbe** [comment]
难道是chrome的bug？关掉这个tab，重新打开一个就正常了，不过偶尔还是会出现在chrome上浏览特别大的的问题

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
