### ISSUE TITLE
stream 网络请求安卓与ios表现不一致

### ISSUE THREAD

**Issue by lehahagirl** [alibaba/weex#2984]
请求在ios里表现正常在安卓里就不行，老是status -1 err_connection.怎么回事，接口是在循环里调的

**Comment by zk0301** [comment]
没遇到过。

**Comment by aoping** [comment]
+1,这个怎么解决啊

**Comment by superchao1123** [comment]
从sdk源码看，应该是报了IOE，具体可见DefaultWXHttpAdapter.sendRequest，引起ioe的原因，我还在和后台同事去找。有知道的大神可以指点下谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
