### ISSUE TITLE
weex list列表在iphone7和iphone7P上下拉加载数据内存暴涨，其他iphone手机均正常。

### ISSUE THREAD

**Issue by cky113999742** [alibaba/weex#2990]
weex list列表在iphone7和iphone7P上下拉加载数据内存暴涨，其他iphone手机均正常。

**Comment by acton393** [comment]
@cky113999742  建议可以profile 看下内存增长主要在哪些方面，是否可以提pr 修复

**Comment by cky113999742** [comment]
@acton393 
![image](https://cloud.githubusercontent.com/assets/14501851/25619298/f35cb844-2f7c-11e7-8928-3368c7e195bb.png)
主要是图片没有得到释放，大部分的内存都被图片占用着。

**Comment by acton393** [comment]
@cky113999742    你的图片库用的是什么， 还有你当前页面图片很多？

**Comment by cky113999742** [comment]
@acton393  用的SDWebImage  商品列表嘛  有很多商品的。一排两个商品。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
