### ISSUE TITLE
Android 0.11.0 bug

### ISSUE THREAD

**Issue by yanxlg** [alibaba/weex#2992]
在0.11.0中dropdown下拉选项被遮罩div挡住bug，选项放在scroller中，div在scroller之前，但是最终显示的时候div是显示在scroller上面，在0.10.0中不存在这种情况，违背了写在下面就显示在上面的原则，在不支持z-index的情况下比较混乱

**Comment by yanxlg** [comment]
而且就算我把scroller写到div里面去，最后的显示效果仍然是div显示在scroller上面，这就奇葩了

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
