### ISSUE TITLE
不支持rem、em 字体页面怎么做动态适配？

### ISSUE THREAD

**Issue by MGXu** [alibaba/weex#2995]

**Comment by bacy** [comment]
px实际不是真的px，默认屏幕是750px，然后根据实际屏幕尺寸缩放

**Comment by dongfanghu** [comment]
我的解决方案是重写text，给他传入fontSize然后进行动态适配

```
      var width = this.$getConfig().env.deviceWidth;
      var scale = this.$getConfig().env.scale/2;

      this.basePX = scale*750/width;
```
这个basePX就成为了在所有的手机上都是一样大的，但是要注意一点安卓的字体大小不支持小数

**Comment by netputer** [comment]
0.11 以后的版本支持 `wx` 基本没有适配问题了

**Comment by craftsman-li** [comment]
@netputer wx怎么用？？？

**Comment by Juice007** [comment]
@craftsman-li 原来单位为px的地方，值除以2，单位改为wx即可

**Comment by SimplyY** [comment]
http://dotwe.org/weex/d8567c69344f2e139789c0928e717ec2
wx not work

@Juice007

**Comment by Juice007** [comment]
@SimplyY dotwe网站的预览有问题。
你可以使用命令`weex test.we`然后用playground APP扫描预览。
此外，不写单位默认就是px
如果hight设为10px，高分辨率屏比低分屏显示得会高一些。
而设为10wx，高分屏和低分屏显示的高度是一样的(这就不会导致小屏手机显示的字体十分小，但可能导致小屏手机显示不完全)。
我觉得用哪个单位都可以，就看你的项目UI是怎么适配的

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
