### ISSUE TITLE
setStyle 对 left 和 top 属性的设置不起作用

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#2996]
尝试用Native Dom Api 的 setStyle 去设置 组件的 left和top属性， 似乎不起作用，其它属性比如透明度，宽，高等都可以

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
