### ISSUE TITLE
iphone手机上火狐浏览器打不开weex生成的h5界面，但是安卓手机是可以的！其他手机的页面渲染兼容性也有一定问题

### ISSUE THREAD

**Issue by JV-BugMaker** [alibaba/weex#2997]

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
