### ISSUE TITLE
h5 modal Prompt ，如果页面有多个input 的时候，无法正确的获取数据

### ISSUE THREAD

**Issue by Alimjan2009** [alibaba/weex#2998]
在开发web 页面，有三个输入框，modal 弹出以后输入完文字以后，没法正确获取数据，获取的是其他input 的值，不是弹出来的对话框的值

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
