### ISSUE TITLE
weex Playground app扫码空白

### ISSUE THREAD

**Issue by mymmoonoa** [alibaba/weex#3002]
就不能正常使用git issue提问吗？的搞个apache订阅也真的是够了. 你要规范英文提问你说不就行了。
---
我用自己的7和同事的5s下载IOS weex Playground app（版本1.6）扫描二维码，页面一直空白。点了run 和save后再去扫描都不可以。（IOS 10.2.1 WIFI和联通/移动4G网络）
点HTML5 preview URI在浏览器中打开就没有问题。
我试了COPY URL然后草料生成二维码也不可以。

是不是你们的软件有bug，还是我使用方式不对

**Comment by acton393** [comment]
保证你手机和二维码内容的服务器是在同一个网段， 如果是国行机器，请检查wifi助手之类的，网络连接

**Comment by 766** [comment]
我也遇到过相同的情况，没有任何更改 第一次打开空白  过了几分钟再打开就ok

**Comment by SheraPrincess** [comment]
为什么我扫开官方的Hello World 都是空白。。华为meta8

**Comment by Cody1988** [comment]
我也遇到了这个问题，
试了一下在手机的浏览器里面是可以打开的，说明不是端口问题；
但是通过扫码，playground是空白页面，这个有解决方案了么

**Comment by liu1020269358** [comment]
我也遇到这种情况，可以用手机浏览器打开但是用 playground 扫码则是空白。
但是我发现是由于我使用了 sass，并且 <style lang="**sass**" scoped> 这样写导致的。如果我改成了 <style lang="**scss**" scoped> 这样，就没有问题了。
并且，在使用 <style lang="**sass**" scoped> 的时候，build是会出错的。
不知道你们会不会是这种情况

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
