### ISSUE TITLE
Slider在WEEX VUE RENDER: 0.11.12 有BUG

### ISSUE THREAD

**Issue by qianlifeng** [alibaba/weex#3004]
WEEX VUE RENDER: 0.11.2下面还是好的（http://dotwe.org）
但是npm上最新的0.11.12不行，首张图片可以加载，但是第二张就是空白。

http://dotwe.org/vue/0c43ffd743c90b3bd9f5371062652e60

**Comment by xiaohuapunk** [comment]
同样遇到此问题

**Comment by T-Zouy** [comment]
同样有此问题，请问有解决么？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
