### ISSUE TITLE
【0.11.0 “list”渲染性能问题】

### ISSUE THREAD

**Issue by xiaohuapunk** [alibaba/weex#3006]
`iOS`版本 `WeexSDK` 升级到 `0.11.0` 后 list 的渲染速度明显变慢了1-3秒（之前版本主要是能看到`cell`一个一个出现的问题）

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
