### ISSUE TITLE
weex vue render^0.11.12 大 BUG：vue文件中style不能加注释，加上注释css会失效，无法渲染

### ISSUE THREAD

**Issue by damnright** [alibaba/weex#3007]
加上注释后，注释后面的css都会失效
0.10.4版本是正常的
还有个问题，既然这里提issue不会受理，以后去哪里提？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
