### ISSUE TITLE
Weex 关于网络请求问题

### ISSUE THREAD

**Issue by MGXu** [alibaba/weex#3008]
Weex android手机上 在使用非CA证书的情况，使用https进行网络通信是否能通？比如：巴西、马来西亚这些国家会不会不通？Weex 是否跟ionic一样的性质，属于web？忘告知谢谢！

**Comment by ChengRuipeng** [comment]
![Uploading image.png…]()

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
