### ISSUE TITLE
Integrate with Quasar Framework

### ISSUE THREAD

**Issue by kokizzu** [alibaba/weex#3009]
They have a really nice components that works with web and mobile 
http://quasar-framework.org/components/

It would make people more interested to use weex if it's ported here.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
