### ISSUE TITLE
weex如何加载sd卡里的js文件

### ISSUE THREAD

**Issue by ambitionJz** [alibaba/weex#3010]
从服务器下到手机上  解压完之后填入路径
就是不显示
路径没有错 
求大神知道

**Comment by likenow** [comment]
NSURL *URL =  [NSURL fileURLWithPath:[NSString stringWithFormat:@"%@/static.js", [NSString documentsPath]]];
[_instance renderWithURL: URL];

**Comment by mlcldh** [comment]
使用本地路径动画，路径前缀是file://

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
