### ISSUE TITLE
web组件怎么样loadDataWithBaseURL

### ISSUE THREAD

**Issue by zk0301** [alibaba/weex#3014]
weex的web组件使用的是webview，但是都是loadUrl的方式。好像没有loadDataWithBaseURL的方法。只能自己扩展了。是吗？

**Comment by acton393** [comment]
可以自己扩展， loadDataWithBaseURL 是个啥意思，加载html 文件？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
