### ISSUE TITLE
如何做到像rn一样更改了js，直接按cmd+r不能刷新模拟器

### ISSUE THREAD

**Issue by nyrf** [alibaba/weex#3016]
文档找了半天也没找到有这个文档？weex-devtool-iOS 文档里写的也只写了半截。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
