### ISSUE TITLE
自定义component的fireEvent，怎么传了一大堆东西

### ISSUE THREAD

**Issue by zk0301** [alibaba/weex#3018]
android0.10.x   自定义component，fireEvent的参数，我就传了一个{“aaa”:"aaa"},  js接到后，toast e， 出来一堆东西。 把整个控件都打印出来了。

自定义module的fireglobalevent就不会。

**Comment by xue5455** [comment]
可以请问下，fireEvent如何在js中接收么？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
