### ISSUE TITLE
0.11更新内容？

### ISSUE THREAD

**Issue by elover** [alibaba/weex#3019]
0.11版本的weex发布也有一个多月了，但是也没有地方能够看到更新了那些内容？

还有想了解下，weex这块有比较稳定的发版本周期吗？

**Comment by zk0301** [comment]
0.11发布了吗？你没说我都不知道。汗，我去看看。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
