### ISSUE TITLE
text 元素变量传 unicode 做图标有问题

### ISSUE THREAD

**Issue by ginuim** [alibaba/weex#3020]
<img width="791" alt="03ccb771-0cfd-40b6-b6bf-bcfa82514364" src="https://cloud.githubusercontent.com/assets/497432/25890788/6ebe5e32-35a1-11e7-8ca6-7295a1aab452.png">
<img width="900" alt="91b06108-f54d-43ce-b6a2-1eb2c00e4956" src="https://cloud.githubusercontent.com/assets/497432/25890790/6ebf975c-35a1-11e7-9e0d-213e355600fe.png">
<img width="388" alt="c034249b-bf4e-490c-a7ab-d55a3d001e7c" src="https://cloud.githubusercontent.com/assets/497432/25890849/aa2f3400-35a1-11e7-977a-425e30b4b6c6.png">
我想做一个组件，引入全局的 iconfont 然后动态传 icon 的 unicode 进去显示不同的图标，但是硬编码到 text 里的 unicode 是可以正常显示图标的，用变量传进去的就不行，不知道为什么

**Comment by hayvane** [comment]
参考此链接：https://segmentfault.com/q/1010000009357817

**Comment by ginuim** [comment]
@hayvane 太感谢了！问题解决了 👍

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
