### ISSUE TITLE
[BUG] Android无法正确获取节点信息

### ISSUE THREAD

**Issue by XImoon** [alibaba/weex#3021]
使用echarts中，需要进行节点信息初始化，需要用到类似于Document.getElementById("id")获取到的节点内容，但是在vue版本中使用refs定义id用this.$ref.id获取到的类型是[object, object]， 导致报错：

TypeError: Cannot assign to read only property 'constructor' of [object Object]

如何解决？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
