### ISSUE TITLE
weex 新版本  text, div等组件都有默认的点击效果，这个怎么去掉，不想要这种效果 

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#3037]

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
