### ISSUE TITLE
Touch手势在html5上不能调用，为什么

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#3038]

**Comment by guoshengwang** [comment]
你的 H5是怎么跑起来的, 怎么配置的,能简单说下么

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
