### ISSUE TITLE
weex animation - height/width 不生效 (ios)? 前面的 issues 我看也提到了 给到的那个参考地址无效

### ISSUE THREAD

**Issue by guoshengwang** [alibaba/weex#3041]

**Comment by acton393** [comment]
如果遇到问题，建议在邮件组 dev@weex.incubator.apache.org 中讨论

readme 中有完整邮件列表

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
