### ISSUE TITLE
android weexSDK应该支持armeabi-v7a放弃armeabi

### ISSUE THREAD

**Issue by myeveryheart** [alibaba/weex#3046]
最近集成android weexSDK折腾了好久才能跑起来，原因就是项目同时用到了Realm数据库，而Realm不再支持armeabi，所以我指定了ndk armeabi-v7a。
这样的话直接跑weex就报错了，后来发现weex只提供了armeabi和x86的so，要把so到拷贝到armeabi-v7a文件夹里。如果我自己的lib依赖weex并且要发布出去，就不好搞了。
虽然armeabi可以兼容armeabi-v7a，但是现在armeabi已经很少了，支持armeabi-v7a才更有意义，对性能提升有帮助。比如著名的数据库Realm就早早的放弃了armeabi。而且，作为一个开源SDK，支持全平台更符合自身定位，用户想输出哪些APK由它们自己选择。

**Comment by xiaolongyuan** [comment]
+1

**Comment by misakuo** [comment]
您好，建议到邮件列表（dev@weex.incubator.apache.org）中讨论该问题

**Comment by allanhuang1109** [comment]
强烈建议提供CPU各个版本的so文件，因为实际开发中，app工程中会用到其他第三方的so（各个abi版本的so文件），而android用不能混合加载so文件

**Comment by zerochl** [comment]
https://github.com/zerochl/weex-android

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
