### ISSUE TITLE
[_instance renderWithURL:URL options:@{@"bundleUrl":URL.absoluteString} data:nil]; 这里参数 data 在 native 渲染时传入后, 在. Vue 里怎么利用这些参数

### ISSUE THREAD

**Issue by guoshengwang** [alibaba/weex#3047]

**Comment by guoshengwang** [comment]
就不能正面回答问题么 ,这邮件组怎么看啊

**Comment by guoshengwang** [comment]
@acton393 你说的这个邮件组怎么 进去查看

**Comment by snaildance** [comment]
options中的参数是在weex.config中获得，data需要传递字典，该数据是直接绑定到你当前加载Vue页面的data对象中的，比如renderWithURL:options:data:@{test:'value'}，那么在你的Vue页面中直接使用就可以了：

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
