### ISSUE TITLE
weex -v 1.0.5 weex.html require a undefined path of js ('./node_modules/weex-vue-render/index.js')

### ISSUE THREAD

**Issue by kevinaskin** [alibaba/weex#3048]

**Comment by JackZhang1988** [comment]
`<script src="./node_modules/weex-vue-render/dist/index.js"></script>`
正确的路径是这个

**Comment by gosongs** [comment]
同样的问题，修改weex.html 中的
```html
<script src="./node_modules/weex-vue-render/index.js"></script>
```
为：
```html
<script src="./node_modules/weex-vue-render/dist/index.js"></script>
```

官方的例子代码错误都没有人修复的吗？？？

**Comment by hupanfeng** [comment]
维护文档的人实在是太没有责任心了

**Comment by bsed** [comment]
维护文档的人实在是太没有责任心了

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
