### ISSUE TITLE
weex H5打开 ,是不是少了什么?

### ISSUE THREAD

**Issue by guoshengwang** [alibaba/weex#3050]
const num = perf.renderTime.length
  perf[`screenTime${num}`] = time
  window.weex.emit('renderfinish', time)

在 perf.js 这块报错了:
 ->   Uncaught TypeError: window.weex.emit is not a function

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
