### ISSUE TITLE
weex pickDate返回在iOS和Android上不一致

### ISSUE THREAD

**Issue by aoping** [alibaba/weex#3052]
在iOS上返回 '2017-07-01'
在android上返回'2017-07-1'
返回不一致

**Comment by aoping** [comment]
然后在Android(5,其他还没试)上'2017-07-1'用new Date('2017-07-1')不能正确返回, 但通过weex debug又可以正确返回,不知道原因在哪里

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
