### ISSUE TITLE
text-overflow:ellipsis三端不一致

### ISSUE THREAD

**Issue by lihqi** [alibaba/weex#3053]
http://dotwe.org/vue/ef009408eebf750b04d1733fbed507a7

**Comment by acton393** [comment]
https://github.com/open-dingtalk/weex-dingtalk-issues/issues/27  如果有遇到问题欢迎在邮件组沟通， 邮件组： https://github.com/alibaba/weex#for-chinese

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
