### ISSUE TITLE
slider中嵌套两个页面中为list的页面  列表高度在安卓中有问题

### ISSUE THREAD

**Issue by 15136356361** [alibaba/weex#3054]
slider中嵌套两个页面中为list的页面 ，安卓中即使屏幕还有很大空白高度，但是list依然显示不全，求解

**Comment by 501956430** [comment]
可能需要自动计算高度

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
