### ISSUE TITLE
如何在键盘弹出时让view浮在键盘上面 

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#3056]
类似编辑器的功能，键盘弹出时，在键盘上面显示一排功能按钮。

**Comment by zdpdsy** [comment]
要么原生自己实现个带功能按钮的keyboard做成componet，否则就是自己实现个vue版键盘

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
