### ISSUE TITLE
_animationInfo.target如果为空时，调用_animationInfo.target->_transform会导致崩溃

### ISSUE THREAD

**Issue by mlcldh** [alibaba/weex#3059]
WXAnimationDelegate里面_animationInfo.target如果为空时，调用_animationInfo.target->_transform会导致崩溃！不知道为什么访问_transform非要写成这种形式，这种形式很容易导致崩溃……最近我们公司web前端写的weex只要使用动画，就非常容易崩溃！

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
