### ISSUE TITLE
list标签性能问题

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#3060]
做长图文列表，持续多次上拉加载数据，导致内存溢出，监控内存视图，每次加载数据，内存都在暴涨，没有优化方案

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
