### ISSUE TITLE
如何在页面加载时候scroll默认显示在最后，就是已经滑动到最低端，我用了dom.scrollToElement(el, {}) 这个会有滑动效果，我这需求是滑动效果不要被看到，页面加载时scroll已经滑动到最后了

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#3063]

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
