### ISSUE TITLE
如何给class添加判断

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#3064]
想给class添加判断，index等于某个值时候这个class有效，但是不知道如何写

**Comment by wangzhenyu1260** [comment]
`<div class='[ index==1 ? 'className1':'className2']'></div>`

**Comment by beghujam** [comment]
谢谢

**Comment by zdpdsy** [comment]
也可以用function判断的
<text :class="[getColorWithPriceChange(item.px_change)]">{{item.last_px}}</text>

getColorWithPriceChange:function(priceChange){
	if(priceChange>0)
		return "riseColor";
	else if(priceChange<0)
	       return "fallColor";
	else 
	      return "stableColor";
 }

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
