### ISSUE TITLE
安卓端BUG。用slider包含四个页面进行侧滑，每个页面下面各有1个list,第二个页面以后的loading和refresh组件不显示

### ISSUE THREAD

**Issue by liaott** [alibaba/weex#3066]
安卓端BUG。用slider包含四个页面进行侧滑，每个页面下面各有1个list,第二个页面以后的loading和refresh组件不显示，目标位置为空白，但是能触发他们的回调函数。而且此时，回退到前面两个页面，其loading和refresh组件也会出现这种问题。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
