### ISSUE TITLE
[iOS]导航栏被顶上去

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#3067]
iOS SDK 0.13.0 底部input获得焦点弹出键盘导致导航栏被顶上去了，又没遇到相同问题的，寻求解放方案。
<img width="322" alt="2017-07-27 00 15 51" src="https://user-images.githubusercontent.com/20204491/28631889-60933ef2-7261-11e7-8b86-40812b9edf71.png">
<img width="324" alt="2017-07-27 00 15 59" src="https://user-images.githubusercontent.com/20204491/28631902-6865bc4a-7261-11e7-9d31-302b5ac28472.png">

**Comment by wangzhenyu1260** [comment]
判断一下平台，给ios加上高度40px`<div v-if="platform === 'ios'" style="height: 40px;"></div>`

**Comment by 501956430** [comment]
@wangzhenyu1260  你说的是设置导航栏的高度吧

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
