### ISSUE TITLE
ios input键盘类型建议增加纯数字键盘UIKeyboardTypeNumberPad

### ISSUE THREAD

**Issue by majunhui** [alibaba/weex#3081]
ios input键盘类型现在选择number，实际用的UIKeyboardTypeDecimalPad键盘，这个是带小数点的键盘，建议改成UIKeyboardTypeNumberPad，同时增加decimal类型，选中UIKeyboardTypeDecimalPad，这条建议没怎么考虑三端兼容性

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
