### ISSUE TITLE
WXSwitch

### ISSUE THREAD

**Issue by caipengrui** [alibaba/weex#3082]
Weex android SDK 整体上是不依赖v7包的，WXSwitch控件中却是依赖于v7包的，建议处理一下

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
