### ISSUE TITLE
项目中图片加载库为fresco,可接入后border-radius不起作用，Picasso正常工作。接入fresco要怎么做呢？

### ISSUE THREAD

**Issue by caprice** [alibaba/weex#3083]
请问android中接入FrescoImageAdapter和FrescoImageView之后，如何支持显示圆角图片？

**Comment by shamao** [comment]
默认支持

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
