### ISSUE TITLE
安卓 List组件不能监听click事件，里面的Cell可以

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#3084]
如题， 奇怪的是iPhone 就可以监听到，看了文档，List应该支持click事件

有没有人遇到同样问题？

weex 0.15.1

**Comment by rccoder** [comment]
@jasonhe88  是安卓么

**Comment by rccoder** [comment]
猜测是某个版本的 weex-vue-render 里 click 被换成了 touch。

然后 **目前，由于会触发大量事件冲突，Weex Android 还不支持在滚动类型的元素上监听手势，例如 scroller, list 和 webview 这三个组件。**

https://weex-project.io/cn/references/gesture.html

**Comment by jasonhe88** [comment]
是的， touchstart / touchend 可以监听到。

这个click是放在list元素， 不是cell元素上的

然而， cell上可以监听到 longpress

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
