### ISSUE TITLE
Android 上header如下情况会崩溃

### ISSUE THREAD

**Issue by 1903514970** [alibaba/weex#3120]
因为项目需求原因，需要在list中使用header，用了slot标签，代码如下，但是在Android上，上下滑动list,
会崩溃。

![b q 8icz ds r 0hmxxn2](https://user-images.githubusercontent.com/15099256/32928793-c69dd816-cb8e-11e7-8626-2b3a4f948326.png)

报错信息如下：

![image](https://user-images.githubusercontent.com/15099256/32929554-b26d8544-cb93-11e7-9f1e-2e5ca67fc9a0.png)

使用weex版本：0.16.2

**Comment by 1903514970** [comment]
自己做了一下，处理。暂时解决了问题。修改方法WXCell中的removeSticky,原因是有可能第一个child可能是BoxShadowHost
将
`mHeadView = getHostView().getChildAt(0)`
替换成
`int childCount = getHostView().getChildCount();
                 for(int i = 0;i<childCount;i++){
                     mHeadView = getHostView().getChildAt(i);
                     if(mHeadView instanceof ViewGroup){
                        break;
                    }
                 }`

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
