### ISSUE TITLE
在weex中用vue语法如何获取当前的时分秒？

### ISSUE THREAD

**Issue by ChenChao1991** [alibaba/weex#3121]
var date = new Date();
var hours=date.getHours();
       这样获取小时不对，我在中国，少了8小时

**Comment by liealis** [comment]
new Date()获取的是操作系统上的时间，你检查一下系统的时区和时间看看

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
