### ISSUE TITLE
iOS Universal Frameowork

### ISSUE THREAD

**Issue by goelay** [alibaba/weex#3125]
Hi,
We are not able to create universal framework for iOS as we don't have cocoa pods in our project. I tried out using files directly but could not succeed in that.  Their are commands to create the universal framework but they doesn't work over here. Please help.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
