### ISSUE TITLE
why playground remove weex_debug support

### ISSUE THREAD

**Issue by lerit** [alibaba/weex#3126]
i found the weex_debug project was remove and the new playground app not support debug.
* * [android] removing the legacy module weex_debug
why it was removed,and does playground will not support debug in the future?

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
