### ISSUE TITLE
为什么在浏览器（Google Chrome  版本 62.0.3202.94（正式版本） （64 位））中运行老是提示：Uncaught ReferenceError: __weex_define__ is not defined。而通过扫描二维码可以在android中显示正常。

### ISSUE THREAD

**Issue by choha** [alibaba/weex#3128]

**Comment by choha** [comment]
<template>
  <div style="width: {{w}}; height: {{h}}; background-color: green;" onclick="update"></div>
</template>
<script>
  module.exports = {
    data: function () {
      return {w: 750, h: 200}
    },
    methods: {
      update: function (e) {
        this.h += 200
      }
    }
  }
</script>   

所有的demo在iframe中都显示空白！

Uncaught ReferenceError: __weex_define__ is not defined
    at Object.module.exports.type (:8081/hello.js:51)
    at __webpack_require__ (:8081/hello.js:21)
    at :8081/hello.js:41
    at :8081/hello.js:44

**Comment by gubojun** [comment]
我也是

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
