### ISSUE TITLE
video fixed 定位才能点击控件

### ISSUE THREAD

**Issue by singlehcc** [alibaba/weex#3129]
我的布局：video放在slider标签里面，slider外层有两个scroller组件，最外层是横向的scroller标签，外层是竖向的scroller标签。 这样布局无法点击视频原生的播放按钮,但轮播图可以切换。 给视频加上fixed定位，播放按钮可以点击。求各位大佬解答？

**Comment by zwwill** [comment]
@singlehcc  weex 的层级是后者在上的，所以看一下你的布局是否被后者盖住了

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
