### ISSUE TITLE
安卓上，设置active样式，触发之后，不能恢复原来的样式，一直处于active状态

### ISSUE THREAD

**Issue by echoLC** [alibaba/weex#3130]

**Comment by KKKits** [comment]
It's the same problem. weex sdk version --- release 0.16

**Comment by linkaipeng** [comment]
发现 0.17.0 上面会有问题，0.16.0 就正常

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
