### ISSUE TITLE
父子组件通信，native和h5效果不一样

### ISSUE THREAD

**Issue by lerit** [alibaba/weex#3131]
` this.$emit('visibleChange', false)   <wd-dialog @visible-change="xx"/>`
native可以，h5无法接收。
` this.$emit('visible-change', false)   <wd-dialog @visible-change="xx"/>`
h5可以，native无法接收。
` this.$emit('visibleChange', false)   <wd-dialog @visibleChange="xx"/>`
native可以，h5可以。
第三种虽然可以，但是vue是不推荐驼峰式传入的。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
