### ISSUE TITLE
list touch事件和滚动冲突

### ISSUE THREAD

**Issue by UDvoid** [alibaba/weex#3133]
问题：在list的cell上要实现左滑删除的功能，使用了panStart、panmove、panend事件识别手势，但是发现list无法正常纵向滚动，请问这个有解决的方案吗？

**Comment by echoLC** [comment]
我也遇到相同的问题，请问下你现在解决了吗

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
