### ISSUE TITLE
Is it Chinese only?

### ISSUE THREAD

**Issue by StormGoth** [alibaba/weex#3136]
Before I decide if I use a project I check the open issues, but this seems to be Chinese exclusively?
Where do I find the international community?

**Comment by fumpierrez** [comment]
Issues are also answered/actioned if you use English. There's also a Gitter in English https://gitter.im/weex-en/Lobby

Community is growing but I'd like Weex to focus more on growing community further

**Comment by arifhussain353** [comment]
@fumpierrez is there any way to use `vuex` with `mapaction` and `mapgatter`?. I am getting error.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
