### ISSUE TITLE
顺便问句这个项目还有没有在维护了

### ISSUE THREAD

**Issue by flicat** [alibaba/weex#3137]
文档写的太不清楚！
weex create 下来的代码 pack:android 的命令都是错的，能再走点心吗？

**Comment by gongyucheng** [comment]
同样有此一问，纠结入坑RN还是weex呢

**Comment by wooter-s** [comment]
RN成熟很多

**Comment by flicat** [comment]
看了一遍文档，错误的地方很多很多，错别字，示例代码错误等等。。。不胜枚举，想确认下这是不是weex的官网： http://weex.apache.org/

**Comment by gongyucheng** [comment]
是啊，RN刚看了下release版本非常快，weex上次release还是17年2月份，是不是不维护了？

**Comment by bsed** [comment]
@gongyucheng  see [https://github.com/apache/incubator-weex/] update time seeing this pic.
![image](https://user-images.githubusercontent.com/10845087/35371861-a3efd8ae-01d1-11e8-9173-d9c73982dd19.png)

**Comment by flicat** [comment]
弃坑！unStar！跟着demo都跑不通的项目，谷歌都搜不出来，谁能告诉我这是什么错误！
This package of weex is not support anymore! Please choose other package.

**Comment by linqingmo** [comment]
在Readme中有提到，仓库迁移了。

Weex 已经于 2017-02-24 迁移至 Apache 基金会，我们都会基于 Apache 的基础设施继续迭代

我们已经启用新的 GitHub 仓库：https://github.com/apache/incubator-weex

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
