### ISSUE TITLE
renderWithURL:(NSURL *)url options:(NSDictionary *)options data:(id)data;

### ISSUE THREAD

**Issue by kangjunfeng** [alibaba/weex#3138]
data 如何在weex页面中获取

**Comment by kangjunfeng** [comment]
已解决
renderWithURL:options:data:@{test:'value'}

vue:
export default{
    data(){
        return {
            test: ''
        }
    }
}

**Comment by kangjunfeng** [comment]
已解决
renderWithURL:options:data:@{testValue:'value'}

vue:
export default{
      data(){ return { testValue: '' }  }
}

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
