### ISSUE TITLE
ios调试启动闪退

### ISSUE THREAD

**Issue by Achilles1988** [alibaba/weex#3140]
pod文件如下：

    pod 'WeexSDK', '0.17.0'
    pod 'WeexPluginLoader', '0.0.1.9.1'
    pod 'WXDevtool', '0.15.3', :configurations => ['Debug']

    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2

版本：
 weex-debugger@1.0.5

步骤：
weex debug xxx.vue   #调试的vue文件是官方demo里的
然后ios端：

    [WXDevTool setDebug:YES];
    [WXDevTool launchDevToolDebugWithUrl:url]; // url是从命令行上抄来的

结果:
![screen shot 2018-02-12 at 5 43 04 pm](https://user-images.githubusercontent.com/1631948/36090820-b600a146-101c-11e8-9e2e-8e700acea4e2.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
