### ISSUE TITLE
Error: weexpack events can be redirected to another EventEmitter instance only...

### ISSUE THREAD

**Issue by arifhussain353** [alibaba/weex#3141]
I follow these steps [weex](http://weex.apache.org/guide/#set-up)  but facing this issue after fresh install of `weex` project. Anything I missed? 
![image](https://user-images.githubusercontent.com/12670763/36611747-45a8fcbc-18f6-11e8-947e-8919d1ac90a5.png)

**Comment by william807803** [comment]
sweety , i have the same problem !

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
