### ISSUE TITLE
[android] picker模块的bug：选择年份是直接从1900开始，而不是定位到当前年份（2018）

### ISSUE THREAD

**Issue by Bob-huang-gdut** [alibaba/weex#3148]
min: '1900-01-01',
max: format(currentDate, 'yyyy-MM-dd')
![image](https://user-images.githubusercontent.com/26543174/37070035-d0370f06-21f0-11e8-9800-7d1322884647.png)
目前在IOS上正常，但在安卓上异常。

**Comment by Bob-huang-gdut** [comment]
min: '1900-01-01',
max: format(currentDate, 'yyyy-MM-dd')

**Comment by Bob-huang-gdut** [comment]
目前在IOS上正常，但在安卓上显示异常。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
