### ISSUE TITLE
weex 临时图片使用问题

### ISSUE THREAD

**Issue by zhuxiaozhuworking** [alibaba/weex#3151]
1. weex 使用本地图片时，iOS客户端中 在bundle 使用“local:///x x x.png”可获取到

2.那么当图片与基础bundle位置不同的时候  该如何使用  类似weex-image-crop-picker这样拍完照给的路径的：

2018-03-09 10:51:41.748604+0800 WeexDemo[6697:2964327] <Weex>[log]WXJSCoreBridge.m:146, jsLog: 当前显示的图片路径是：///////
/private/var/mobile/Containers/Data/Application/A2F3F6B3-84C5-41C5-81DE-C70FC77D2670/tmp/react-native-image-crop-picker/1CBCFB68-B196-4353-963C-BBD56A5AF587.jpg

![wechatimg12](https://user-images.githubusercontent.com/8513778/37187899-762f2e88-2387-11e8-87d7-14d8f894a193.jpeg)

**Comment by acton393** [comment]
@zhuxiaozhuworking   建议可以重写路径规则handler http://weex.apache.org/cn/guide/advanced/path.html#uri-adapter

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
