### ISSUE TITLE
weex build android/weex run android （没有把dist下面的文件夹内的文件copy到安卓模板中）

### ISSUE THREAD

**Issue by wilson-0422** [alibaba/weex#3154]
weex build android （
没有把src/dist下面的文件夹内的文件copy到安卓模板中
'platforms/android/app/src/main/assets/dist'
）

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
