### ISSUE TITLE
weex run ios报错 help~

### ISSUE THREAD

**Issue by niczzZ** [alibaba/weex#3155]
![bc20909a-fdcd-483c-a5a2-a8446ae9a7b5](https://user-images.githubusercontent.com/2193651/37820165-ca9ee5d8-2eba-11e8-97b2-6d513e9b46ed.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
