### ISSUE TITLE
插件添加成功 使用不了

### ISSUE THREAD

**Issue by heshan-song** [alibaba/weex#3156]
我第一次 使用weex 构建项目
安装weex插件，运行 weexpack plugin add nat-media-image

在plugins 目录下 有一个 json 文件
里面是 是一些 插件 列表
{
"type": "maven",
"groupId": "com.instapp.nat",
"name": "weex-plugin-media-image",
"version": "1.0.1",
"dependency": "com.instapp.nat:weex-plugin-media-image:1.0.1"
},

但是 我发现platforms 平台里面的 ios 安卓 目录 里面 没有 所谓的 weex-plugin-media-image 项目，我在vue 页面 也调用不了，是怎么会呢？

**Comment by Z-Janp** [comment]
hello weex plugin add 的机智已经修改了哟。
android 改为和ios 引用方式一样。
生成一份.weex_plugin.json文本文件。

android 根据新版本的plugin加载器导入依赖的插件
`
    compile 'com.taobao.android:weexplugin-loader:1.3'
    compile 'com.taobao.android:weexplugin-processor:1.3'
    compile 'com.taobao.android:weexplugin-annotation:1.3'
`
具体对比一下 `weex create` 生成的项目

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
