### ISSUE TITLE
weex导航问题

### ISSUE THREAD

**Issue by plusyuyu** [alibaba/weex#3157]
使用weex脚手架搭建项目的时候，是可以将整个项目打成一个bundleJS，在这个单独项目中我可以使用vue-router来进行页面的切换。但是现在我考虑做一个登陆功能，需要从登陆页面跳转到项目的主页。请问如何实现？
现在的想法：再使用weex脚手架搭建一个新的项目，专门用于编写登陆页面，然后将其打包成bundleJS。登陆成功后使用navigator模块跳转到主页的bundleJS中，请问这样是否可行？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
