### ISSUE TITLE
weex debug出错

### ISSUE THREAD

**Issue by wy6395727** [alibaba/weex#3158]
运行weex debug出错；

AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "yarn install" or "npm install"

我装了，好像装不了Chromium 这个玩意

**Comment by liuruizhe728** [comment]
同问，现在咋样啦

**Comment by rcupid** [comment]
same problem

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
