### ISSUE TITLE
weex.isRegisteredComponent 无法识别 带有 “-”的自定义组件

### ISSUE THREAD

**Issue by KingBo0259** [alibaba/weex#3167]
如：  weex.isRegisteredComponent('wec-mycomponent’)  无法识别

**Comment by ligaozeng** [comment]
前段会自动转义，我查看了dist里的代码，自动转成驼峰命名，native可以写成wecMycomponent

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
