### ISSUE TITLE
can weex project generate PWA out of the box

### ISSUE THREAD

**Issue by dohomi** [alibaba/weex#3172]
Hello,

Is it possible to create a PWA out of a `weex` project? The docs does not cover this issue but as weex can build for web is there a demo how to built is as an PWA? Thanks

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
