### ISSUE TITLE
weex market 访问不了了，好一段时间了。。。。 你们管不管啊

### ISSUE THREAD

**Issue by alex-zhang** [alibaba/weex#3173]

**Comment by liushengyi** [comment]
地址加个后缀就可以访问了
https://market.dotwe.org/ext/list.htm#15

**Comment by yulinho** [comment]
> 地址加个后缀就可以访问了
> https://market.dotwe.org/ext/list.htm#15

也不行了哦

**Comment by yulinho** [comment]
> 解决了么

不行哦。难道已经废弃了。

**Comment by yulinho** [comment]
> 解决了么

DNS_PROBE_FINISHED_NXDOMAIN

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
