### ISSUE TITLE
weex run ios error 

### ISSUE THREAD

**Issue by shekang** [alibaba/weex#3175]
The following build commands failed:
	CompileC /Users/work_place/weex-pro/platforms/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/WeexSDK.build/Objects-normal/i386/WXResourceLoader.o WeexSDK/ios/sdk/WeexSDK/Sources/Loader/WXResourceLoader.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by shekang** [comment]
XCODE打开Weexdemo报错
![screenshot](https://user-images.githubusercontent.com/13003498/40339411-f6d43182-5dac-11e8-859c-c204e2a46060.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
