### ISSUE TITLE
请问weex里想做一个动态环形图怎么搞，试了好多都不行

### ISSUE THREAD

**Issue by Panamer** [alibaba/weex#3179]

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
