### ISSUE TITLE
run ios error

### ISSUE THREAD

**Issue by 476139183** [alibaba/weex#3180]
iOS pod install 一直失败

================================
Installing WeexSDK (0.18.0)

[!] Error installing WeexSDK
[!] /usr/bin/git clone https://github.com/apache/incubator-weex.git /var/folders/3d/knr_50qx4dxgnb8ggdtr63_w0000gn/T/d20180607-15133-f9wyau --template= --single-branch --depth 1 --branch 0.18.0

Cloning into '/var/folders/3d/knr_50qx4dxgnb8ggdtr63_w0000gn/T/d20180607-15133-f9wyau'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
================================
要翻墙么？

**Comment by 476139183** [comment]
为什么 pod 不行啊

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
