### ISSUE TITLE
默认的ABI可以改了吧

### ISSUE THREAD

**Issue by smoothdvd** [alibaba/weex#3181]
Android Studio 3.2: Changed set of default ABIs: When building multiple per-ABI APKs, Android plugin for Gradle 3.2.0 no longer generates APKs for the following ABIs by default: mips, mips64, and armeabi.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
