### ISSUE TITLE
iOS里WXLogLevel和微信开放平台里的WXLogLevel冲突怎么解决

### ISSUE THREAD

**Issue by smoothdvd** [alibaba/weex#3182]
重名了

**Comment by bmcciscoding** [comment]
修改 weex 的，微信的改不了

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
