### ISSUE TITLE
beforeDestroy is not invoking

### ISSUE THREAD

**Issue by wu464995183** [alibaba/weex#3185]
vue.js beforDestroy can not invoking.

**Comment by wu464995183** [comment]
nobody use it?  my god.  vue`s lifecycle can not used.  owner help me..

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
