### ISSUE TITLE
weex build web时warning

### ISSUE THREAD

**Issue by xiangyunJiao** [alibaba/weex#3188]
执行weex build web时，全都是这种warning，我从官网直接复制的demo，有没有人知道是什么问题吗
[](url)
![image](https://user-images.githubusercontent.com/18900206/42993787-da92ddf0-8c3e-11e8-8650-de2dedd4df72.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
