### ISSUE TITLE
iOS上面圆角和渐变  同时使用不能生效，Android正常

### ISSUE THREAD

**Issue by luocker** [alibaba/weex#3189]
iOS上面  圆角和渐变  同时使用不能生效，
上面圆角，下面直角，加 渐变的时候，圆角全部无效。
全部圆角加渐变的时候是圆角渐变正常。

<div class="div-chart-box-item"></div>
css样式如下：

.div-chart-box-item {
  height: 200px;
  width: 24px;
  /*border-radius: 10px;*/
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
  border-top-left-radius: 10px;
  border-top-right-radius: 10px;
  background-image: linear-gradient(to top,#2cb4ea,#e6f6fd);
}

**Comment by luocker** [comment]
这个应该从哪个类去找问题？麻烦给点提示。先谢谢各位大神！

**Comment by luocker** [comment]
测试页面：

http://dotwe.org/raw/dist/89d6477a318e4d58a57c8a5e3d228462.bundle.wx

**Comment by gnemyg7221** [comment]
相同的问题，目前无法解答

**Comment by doumafang** [comment]
Hey guys,
u can try border and background-image with this demo:http://dotwe.org/vue/7a8c6fcff4ebf347577e948f294c5863
Please use clip-radius="yes" and overflow:hidden to enable this feature.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
