### ISSUE TITLE
 Command failed: call gradlew.bat  assembleDebug

### ISSUE THREAD

**Issue by leopardzhang** [alibaba/weex#3194]
jdk版本1.8 

![egzub5j 11r g8 m3n](https://user-images.githubusercontent.com/25576864/44898763-66d4eb00-ad32-11e8-982c-1386431d1485.jpg)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
