### ISSUE TITLE
Can't include FontAwesome

### ISSUE THREAD

**Issue by conejodan** [alibaba/weex#3197]
Exist any way to include FontAwesome in the proyect?
I follow the tutorial of this page https://segmentfault.com/a/1190000012612962 and in the browser the icon appears, but when deploy in android don't show me nothing.

Do you have any example code for this case?

**Comment by JackChengGZ** [comment]
You should introduce FontAwesome in Android or IOS, similar to introducing icons

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
