### ISSUE TITLE
为什么只支持单类选择器，能不能优化下，变成可选？？

### ISSUE THREAD

**Issue by EvalGitHub** [alibaba/weex#3198]

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
