### ISSUE TITLE
我下载的iOS sdk，自己编译出来的framework好几百兆，咋回事啊？求解，是weexSDK源码配置的问题吗？

### ISSUE THREAD

**Issue by zhangtong217** [alibaba/weex#3200]
大神求解释啊

**Comment by zhangtong217** [comment]
上一次问了，但是看不到了，有人给删了？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
