### ISSUE TITLE
weex开发的app，用appium定位到控件并点击以后，当前driver就失效了

### ISSUE THREAD

**Issue by arronhai** [alibaba/weex#3201]
如题，我们公司App是用weex技术写的，在如下界面时，可以定位到所有选项，
![2](https://user-images.githubusercontent.com/42204523/49356707-813eac00-f707-11e8-8379-6e71f5a75b27.png)
点击状态，优先级和截止时间会有一个弹窗如下。
![1](https://user-images.githubusercontent.com/42204523/49356714-8bf94100-f707-11e8-9d00-b98bbe76026b.png)
在弹出的窗口点击确定或取消后返回到新建任务界面。这时我的driver就失效了，不能定位元素，也不能做任何其他操作。定位元素【任务内容】会报错nosuchelement。我用driver.find_elements_by_xpath('//*')查询当前页面所有元素也一直在加载没有任何反应。
![image](https://user-images.githubusercontent.com/42204523/49356661-4fc5e080-f707-11e8-8404-62f963702ebb.png)

请问这种情况是什么原因引起的？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
