### ISSUE TITLE
使用scroller组件，为组件内的元素item设置box-shadow，并且设置overflow:hidden.滑动时，item的阴影边框在scroller外仍然可见，去掉item的阴影效果则显示正常。

### ISSUE THREAD

**Issue by JChermy** [alibaba/weex#3202]

**Comment by cococa** [comment]
貌似还没解决?

**Comment by JackChengGZ** [comment]
box-shadow这个无法兼容,官方有说过,我也遇到你这个现象,一模一样的,然后是用图片做的阴影

**Comment by cococa** [comment]
@JackChengGZ  就是用图片做背景吗

**Comment by JackChengGZ** [comment]
嗯嗯,是这么做的

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
