### ISSUE TITLE
Android websocket 官网提供的adapter send方法 小米手机出现：android.os.NetworkOnMainThreadException 

### ISSUE THREAD

**Issue by zcl0001** [alibaba/weex#3204]
建议修改官网，目前项目如下修改，加了个线程：
`@Override
    public void send(final String data) {
        if (ws != null) {
                ThreadManager.getNormalPool().execute(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            Buffer buffer = new Buffer().writeUtf8(data);
                            ws.sendMessage(WebSocket.PayloadType.TEXT, buffer.buffer());
                            buffer.flush();
                            buffer.close();
                        } catch (Exception e) {
                            e.printStackTrace();
                            reportError(e.getMessage());
                        }
                    }
                });
        } else {
            reportError("WebSocket is not ready");
        }
    }`

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
