### ISSUE TITLE
关于input组件的问题

### ISSUE THREAD

**Issue by JackChengGZ** [alibaba/weex#3205]
我在安卓机上使用了input组件,在输入框中加了一点内容比如:abcde,然后可以通过日志打印出来,随后,我把input的内容删除,页面上的input是没有任何内容,但是通过日志打印,发现还可以输出一个a;并没有删除完,而且这个现象是偶发的;

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
