### ISSUE TITLE
how to pronounce weex?

### ISSUE THREAD

**Issue by shinriyo** [alibaba/weex#3207]
I can't find how to pronounce weex.
do you pronounce like weeks?
Please write in document.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
`[wi:ks]`, just like "weeks".
