### ISSUE TITLE
onclick touch though

### ISSUE THREAD

**Issue by amdgigabyte** [alibaba/weex#333]
I've got two clicking area on my page,one upon another.
In the H5 version, When I click the upper div, the click handler on the lower div also fires.

**Comment by yanchenta** [comment]
different buddle.

**Comment by MrRaindrop** [comment]
Hi, this is a bug since the outer component should not fire click event by default. This bug has been fixed in the latest version (check the latest `dev` branch). The event bubbling is now prevented by default, and there's no way for developers to enable the bubbling yet.

We welcome all suggestions, ideas and implementations for event bubbling system in weex.
