### ISSUE TITLE
[Discuss] Support viewport config.

### ISSUE THREAD

**Issue by luics** [alibaba/weex#421]
750px is used as the default viewport width in weex. It's really convenient in most cases, however, 1 device(fixed) pixel is hard to implement.

**Comment by Jinjiang** [comment]
Another question & advice from @yahooyee is how to let developers get/calculate the width/height of current viewport.

**Comment by YorkShen** [comment]
`displayWidth: 750(default) ` will cause serious sub-pixel problems, and there is no way to fix it right now. 

For example, if screen width is 720px, the border in the code snippet won't be display.

```
displayWidth: 750(default) 

.a{
     border-width:1;
}

<div class="a">
```

Refer to [DPI](https://developer.android.com/guide/practices/screens_support.html#qualifiers) mechanism in Android, maybe a scale factor(positive, integer, could be 1) which depends on screen width would be a better solution.

**Comment by Jinjiang** [comment]
Proposal:

### DSL Design

Ref: W3C Spec [CSS Device Adaptation](https://drafts.csswg.org/css-device-adapt/#viewport-meta)

Adding item in config script

```
<script type="config">
  {
    "viewport": {
    	"width": "device-width",
    	...
    },
    ...
  }
</script>
```

Supported properties:

* `width`: number or `"device-width"` or `"device-height"`
* `height`: number or `"device-width"` or `"device-height"`
* `initial-scale` (not supported)
* `minimum-scale` (not supported)
* `maximum-scale` (not supported)
* `user-scalable` (not supported)

### JS-Native API Design

* module: `"dom"` | `"instanceWrap"` (both fine)
* method: `"setViewport"`
* args: `[viewportObject]` (just same as viewport object in config script)

It must be called at the beginning of an instance and behind any of other dom method calls, otherwise it will not work.

This also needs implementation from JS framework and native renderer.

**Comment by Hanks10100** [comment]
From another perspective, I think we also should add an absolute unit.

In the current version, Weex will ignore all style units, if we set the viewport (default is 750), all style values are treated as relative values. If we add an absolute unit, it can be very easy to draw a 1 pixel line ( #27 , #1022 ), and writing non-responsive layouts ( #491 #965 #1543 ).

There are two candidate units:

  + `pt`, the absolute units used in CSS and iOS.
  + `dp`, the absolute unit used in Android.

I personally think it's more appropriate to use `pt`, because CSS already has this attribute. Doing so reduces the learning costs of users and avoids introducing our own concepts.


Draw a box with a pixel-wide border:
`` `Css
.box {
   Width: 500;
   Height: 300;
   Border-width: 1pt;
   Border-color: # 666666;
   Border-style: solid;
}}
`` `

**Comment by Hanks10100** [comment]
The proposal of CSS units is separated to #1641 .

**Comment by langxianfu** [comment]
看完了，没看明白

**Comment by yolen** [comment]
就是

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
