### ISSUE TITLE
<input> Data Binding not work

### ISSUE THREAD

**Issue by xiaoshan5733** [alibaba/weex#489]
code: 

```
<style>
.box{
    padding: 20;
}
.demo{
    width: 400;
    height: 80;
    background-color: #fff;
    border-width: 1;
    border-style: solid;
    border-color: #999;
    margin-bottom: 10;
}
</style>
<template>
    <div class="box">
        <input type="tel" class="demo" oninput="inputHandler" value="{{number}}"></input>
        <text>phone number: {{number}}</text>
    </div>
</template>
<script>
module.exports = {
    data: {
        number: '13588888888'
    },
    methods: {
        inputHandler: function(e) {
            var value = e.value
            if (value && value.length >= 11) {
                value = value.substr(0, 11)
            }
            this.number = value;
        }
    },
    ready: function() {
        this.number = '18699999999'
    }
}
</script>
```

**Comment by Jinjiang** [comment]
I've checked that the latest version of JS Framework has cut the value and `updateAttr` to renderer.

cc @MrRaindrop

**Comment by MrRaindrop** [comment]
@xiaoshan5733 latest html5 branch has fixed this problem, please check it out. https://github.com/alibaba/weex/pull/805/commits/f2304c63922100b3daf625af9abb82440c617e44

**Comment by xiaoshan5733** [comment]
@MrRaindrop @Jinjiang 

Am i right ?

![snip20160803_1](https://cloud.githubusercontent.com/assets/854370/17356481/4d68f0ec-598a-11e6-9461-7486944b82a3.png)

**Comment by Jinjiang** [comment]
Yes HTML5 renderer is correct

**Comment by MrRaindrop** [comment]
Hi @xiaoshan5733,

in your code, the value doesn't trigger a diff process when you assign your value to a `value.substr(0, 11)`, since the older value is the same value as this fixed one. So my suggestion is you may want to add a line of code like `this.number  = value` before you fixed the value to 11 bits long. So the working version of code is like

```javascript
inputHandler: function(e) {
  var value = e.value
  this.number = value
  if (value && value.length >= 11) {
    value = value.substr(0, 11)
  }
  this.number = value;
}
```

This is of a bit of hack, anyway it shows how it works. If you think of another way to solve this problem, please don't hesitate to tell me.

**Comment by Jinjiang** [comment]
It also works for me. Considered there is such a long time without any more discussion, this issue will be closed.
Thanks.
